### ISSUE TITLE
className option for marks

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1002]
className should be optional and have no default value, so you have to decide what names you want to use and there are no implicit classes

Related: #253 #6 #126 #490

(Note: for the general plot there is already a top-level className; we'd initially want this only for marks.)

**Comment by RLesser** [comment]
Going to take a first stab at this

**Comment by llimllib** [comment]
This would make my life a lot easier - when you have to do something outside the bounds of plot, being able to specify a class name would be a big help

**Comment by RLesser** [comment]
I can try to have a pull request up this weekend @llimllib, been meaning to do this

**Comment by miketalley** [comment]
This functionality would be an excellent addition. Are there any updates on the progress? It looks like there is a PR, but it hasn't been updated in some time.

**Comment by thinkingfish** [comment]
Adding support for this issue—I want to further describe a few scenarios where I found custom styling particularly important:
- a single plot is embedded in an article as "an additional chart) and needs to blend in with the existing plots of non-observable origin;
- plots rely on Observable Inputs, which can be nearly unusable when mixed with specific CSS rules;
- even when published mostly in entirety, it is still important to match the notebook style with the navigation bar, etc, see our blog [here](https://observablehq.com/@iopsystems/latency-is-a-curve) so the page doesn't feel alien.
