### ISSUE TITLE
Inconsistent Plot time bins

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/plot#1025]
**Describe the bug**
Plot histograms for dates can sometimes have differently sized bins which leads to awkwardly inconsistent "skinny" bars.

**To Reproduce**
See [this notebook](https://observablehq.com/d/54a9e0b4f9175ee6). 
<img width="726" alt="Screen Shot 2022-08-09 at 12 16 43 PM" src="https://user-images.githubusercontent.com/1373882/183704355-b5fb9537-9abf-4f2b-ab1d-25d294a4a7d5.png">

**Comment by mbostock** [comment]
Related https://github.com/d3/d3-scale/issues/245.

Alternative day interval: https://observablehq.com/d/906f777c9f2f0701.
