### ISSUE TITLE
Text with the aggregated value

### ISSUE THREAD

**Issue by ertrzyiks** [observablehq/plot#1036]
Thanks a lot for the great library!

Is it possible to use aggregated value in the text mark?

For example on https://observablehq.com/@observablehq/plot-stack?collection=@observablehq/plot we have a chart with gender split, I would like to show the percentage instead of `Men`/`Women` labels

<img width="1255" alt="Screenshot 2022-08-26 at 11 13 32" src="https://user-images.githubusercontent.com/2437969/186870874-564d360f-4216-408b-aad4-872dcc926cf1.png">

I was able to at least render the values with:
```
Plot.text(congress, Plot.stackX(Plot.groupZ({x: "proportion-facet", text: "count"}, { z: "gender", text: "count"}))),
```
<img width="1280" alt="Screenshot 2022-08-26 at 11 29 03" src="https://user-images.githubusercontent.com/2437969/186873964-726059f2-250e-4859-921e-e08901b5ad73.png">

but no luck show the percentage on the bars.

**Comment by ertrzyiks** [comment]
Not a percentage, but I managed to get the proportion. Sorry about the noise.
```
Plot.text(congress, Plot.stackX(Plot.groupZ({x: "proportion-facet", text: "proportion-facet"}, { z: 'gender' })))
```
<img width="1304" alt="Screenshot 2022-08-26 at 11 36 04" src="https://user-images.githubusercontent.com/2437969/186875333-db8ecdf1-5159-48c5-9251-b84023104e76.png">

**Comment by dgwyer** [comment]
Interesting. Thanks for posting Mateusz. :)

@Fil Apologies for jumping in but out of curiosity I'm guessing it would be possible to further refine the proportion text to be proper percentages? e.g. transform `0.708` to `70.8%`.

**Comment by Fil** [comment]
Yes, with Plot.map you can transform any channel with a custom function.
