### ISSUE TITLE
Bar plot with log scale disappears

### ISSUE THREAD

**Issue by tschaub** [observablehq/plot#1038]
I was surprised to see the marks (`barX`) on my plot disappear when I added `type: "log"` to my scale.  It took a bit of fiddling to discover that I had to add an explicit start (`x1`) value.  I'm wondering if it would be possible to make it so the bar starts at the start of the domain in cases where only one value (`x`) is given.

I wrote up the details here: https://observablehq.com/@tschaub/bar-plot-with-log-scale

If there aren't changes to the behavior that make sense, I would be happy to add a note to the scale or bar docs about using log scales with bars.

**Comment by mbostock** [comment]
I prefer the current behavior because it makes the pitfall of using bars with a log scale clear. A note on the docs would be welcome though.
