### ISSUE TITLE
frameAnchor: bottom is not properly aligned

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1043]
![untitled (14)](https://user-images.githubusercontent.com/7001/188905548-1cd1d391-bf14-4dd7-ae80-03ca189d5d6d.png)

```
Plot.plot({
  marginLeft: 75,
  x: { insetRight: 10 },
  marks: [
    Plot.frame(),
    Plot.barX(
      penguins,
      Plot.groupY(
        { x: "count" },
        {
          y: "species",
          fill: "sex"
        }
      )
    ),
    Plot.text(["Annotation\nat the bottom-right"], {
      frameAnchor: "bottom-right"
    })
  ]
})
```

demo https://observablehq.com/@observablehq/bottom-right-misaligned-1043

**Comment by mbostock** [comment]
We need a different fix than #1061.

**Comment by mbostock** [comment]
The problem in this case wasn’t that the line is wrong relative to its anchor, its that the anchor is in the wrong place when there are ordinal scales. The anchor is drawn here as a red dot:

<img width="659" alt="Screen Shot 2022-11-23 at 1 56 35 PM" src="https://user-images.githubusercontent.com/230541/203626311-e54407b9-58a5-456e-bf04-b04363290b3b.png">

**Comment by mbostock** [comment]
More specifically, the problem is that we’re calling applyTransform when the mark doesn’t have an x/y position.
