### ISSUE TITLE
auto height for band scale consumes margins

### ISSUE THREAD

**Issue by enjalot** [observablehq/plot#1045]
When using Plot.cell with a small y domain and large marginTop and/or marginBottom the auto height calculations don't add to the margins as one might expect, causing a y scale with a collapsed range:
https://observablehq.com/d/223d6091d4190e75

<img width="1260" alt="Screen Shot 2022-09-09 at 4 50 50 PM" src="https://user-images.githubusercontent.com/96189/189444951-238e8b6b-4b87-4863-b3e5-d206d73fcd34.png">

**Comment by Fil** [comment]
direction:
> The automatic height is small when the domain is small, causing the marginBottom to consume all the available range.
> So, if you set a marginBottom you should probably also set the height explicitly… or we could change Plot to compute the auto height to be additive with whatever top and bottom margin you’ve set.
> makes sense to **have the auto height add to the top and bottom margin**, rather than consume them.
