### ISSUE TITLE
image should have a `rotate` option just like dot

### ISSUE THREAD

**Issue by llimllib** [observablehq/plot#1083]
It would be really handy for me if `image` marks had the `rotate` option just like `dot` marks do.

My particular use case is making a diamond chart, which requires rotating the whole plot, which necessitates rotating any of the elements that appear within.

**Comment by Fil** [comment]
I've put up a PR in #1084, feel free to review it. Thanks!

**Comment by llimllib** [comment]
Awesome! Thanks
