### ISSUE TITLE
Arbitrary clip paths

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1109]
It’d be nice to support arbitrary clip paths. I can implement one by wrapping a mark like so:

```js
function clip(mark, renderClip) {
  return {
    initialize(facets, channels) {
      return mark.initialize(facets, channels);
    },
    filter(index, channels, values) {
      return mark.filter(index, channels, values);
    },
    render(facet, scales, values, dimensions, context) {
      const fragment = document.createDocumentFragment();
      const svg = fragment.appendChild(mark.render(facet, scales, values, dimensions, context));
      const clipPath = fragment.appendChild(renderClip(facet, scales, values, dimensions, context));
      svg.setAttribute("clip-path", "url(#clip)");
      clipPath.setAttribute("id", "clip");
      return fragment;
    }
  };
}
```

That should probably extend Mark, though? And it should generate a unique identifier rather than using “clip”.

Then I could have a function that creates a clipPath element like so:

```js
function renderClip(facet, scales) {
  const clipPath = htl.svg`<clipPath>`;
  for (const {a, b} of abDisplayabilityCoordinates.filter(d => d.displayable)) {
    clipPath.appendChild(htl.svg`<rect
      x=${scales.x(a - 0.0025)}
      y=${scales.y(b + 0.0025)}
      width=${scales.x(a + 0.0025) - scales.x(a - 0.0025) + 1}
      height=${scales.y(b - 0.0025) - scales.y(b + 0.0025) + 1}
    />`);
  }
  return clipPath;
}
```

Ref. https://observablehq.com/@mjbo/oklab-named-colors-wheel

**Comment by mbostock** [comment]
Maybe duplicate of #181.

**Comment by espinielli** [comment]
I have tried to add `clip-path` to `Plot.image()` but it seems not handled by `applyIndirectStyles()` (that is what my browsing of the code brings me to...)

I would like to clip an image to a geo path:

```javascript
    Plot.image(italy, {
      x: (d) => d.properties.lon,
      y: (d) => d.properties.lat,

      width: (d) => d.properties.width,
      height: (d) => d.properties.height,
      preserveAspectRatio: "none",
      src: (d) => d.properties.flag,
      clipPath: (d) => `url(#iso-${d.id})`,
      title: (d) => d.id
    })
```

I have some tinkering going on here: https://observablehq.com/d/a8fe9e54cf07cb7a

Any thoughts?

**Comment by Fil** [comment]
Here's a snippet that uses the new render transform:
```
  marks: [
    Plot.geo(perimetro_mexico, {
      render: (i, s, v, d, context, next) =>
        svg`<clipPath id="x">${next(i, s, v, d, context).children[0]}` // create the clipPath "x"
    }),
    Plot.raster(data, {
      x: "longitude",
      y: "latitude",
      fill: "banda_interes",
      interpolate: Plot.interpolatorRandomWalk(),
      render: (i, s, v, d, context, next) =>
        svg`<g clip-path="url(#x)">${next(i, s, v, d, context)}` // reference "x" as clip-path
    }),
```
see https://observablehq.com/d/d5d3052622043025

**Comment by mbostock** [comment]
That’s really nice @Fil. I bet we could package that up into something reusable. Perhaps a clip transform where you supply a geometry channel, and it uses the geo mark under the hood?

**Comment by mbostock** [comment]
We should consider using CSS clip-path instead of SVG, since it is now widely supported and much more convenient since you don’t need a globally unique identifier.

**Comment by Fil** [comment]
clip-path + path is still very poorly supported: https://observablehq.com/d/bf434fc5675c8f13

**Comment by Fil** [comment]
Chrome doesn't seem to support view-box + polygon(coords)—which works under Safari.

**Comment by Fil** [comment]
The Chrome bug has been fixed in 119 https://chromestatus.com/feature/5068167415595008 https://developer.chrome.com/blog/new-in-chrome-119

**Comment by chrispahm** [comment]
@Fil just helped me with an issue applying clip paths to a faceted Ridgeline plot:
https://observablehq.com/@chrispahm/ridgeline-plot-with-average-values

Here we had to remove the `transform` property from the clipPath elements manually in order to get the position right. Fil came up with the following snippet to achieve that:

```js
return svg`<clipPath id=${encodeURI(i.fy)} style="transform: none">${
              next(i, s, v, d, c).children[0]
            }`;
```

**Comment by mbostock** [comment]
Maybe we could offer a Plot.geoClip render transform that you can pass GeoJSON and does this?

![Image](https://github.com/user-attachments/assets/ccb6d14f-c349-4806-89db-29cb4f60d075)

```js
Plot.plot({
  projection: "albers",
  color: {scheme: "YlGnBu"},
  marks: [
    Plot.density(walmarts, {
      x: "longitude",
      y: "latitude",
      bandwidth: 10,
      fill: "density",
      render(index, scales, values, dimensions, context, next) {
        const {document} = context;
        const g = next(index, scales, values, dimensions, context);
        const clipPath = document.createElementNS("http://www.w3.org/2000/svg", "clipPath");
        const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
        const geoPath = d3.geoPath(context.projection);
        path.setAttribute("d", geoPath(nation));
        clipPath.setAttribute("id", "clip");
        clipPath.appendChild(path);
        context.ownerSVGElement.appendChild(clipPath);
        g.setAttribute("clip-path", "url(#clip)");
        return g;
      }
    }),
    Plot.geo(statemesh, {strokeOpacity: 0.3}),
    Plot.geo(nation),
    Plot.dot(walmarts, {x: "longitude", y: "latitude", r: 1, fill: "currentColor"})
  ]
})
```

**Comment by Fil** [comment]
"the **clip** option is set to a GeoJSON object" would be fantastic

**Comment by Fil** [comment]
As @jwolondon remarks in https://observablehq.com/@fil/multiscale-density-spatial-interpolator#comment-451a923b320875f1, the technique with view-box doesn't work in Safari when the page is scaled 😠 
However, that's not what we're doing in #2243, which works fine 😅
