### ISSUE TITLE
Should the projection definition receive the margins?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1124]
Instead of passing {width, height, marginLeft, marginRight, marginTop, marginBottom}, shouldn't we pass 

({width: width-marginLeft-marginRight, height: height-marginTop-marginBottom}),

then somehow add marginLeft, marginTop to every mark? It would simplify the work for the user, and leave less room for error, so it would help ensure that the map's extent/viewport fits the frame.

Framing it it as a question, as I'm not even sure that this is possible without mutating the projection's translate, which would be a no-go.

**Comment by mbostock** [comment]
We could wrap the projection stream to do it, but it would be slower, presumably.

**Comment by Fil** [comment]
I think it's worth it?

As I was writing documentation this (with #1125) was the sole annoying part of using the projection option. A map takes a few seconds to set up, then the projection set up takes a full minute, and I got lazy and didn't add the margins every time.
