### ISSUE TITLE
projection fitSize?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1125]
We'll want a helper or option to fitExtent a projection, or clipAngle, or clipExtent…
Use cases:
- make a map of a certain region of the world
- fit a planar dataset or extent to the identity projection, scaled+translated+angled.

(Not blocking.)

**Comment by Fil** [comment]
"fit to frame", and we'd just pass either a GeoJSON feature, an angle, maybe with some padding?

I also think clip to frame should be activated by default, to make the paths smaller, and to avoid facets bleeding into each other. (In cases this creates an ugly border you could clipExtent with a padding of -1, then use the svg clip: "frame" on top.)

**Comment by mbostock** [comment]
Do we want to depend on projection.fitExtent, or should we just wrap the projection stream ourselves to do the same? The latter might allow more flexibility.

**Comment by Fil** [comment]
I think the latter approach is the most promising.

Ananya suggests we could use the _domain_ option of the projection to denote the scope of what we want to fit to the frame (I guess, with _inset_ to denote some padding).

**Comment by mbostock** [comment]
Fixed in #1135.
