### ISSUE TITLE
Grid color, opacity, and dash-array

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#114]
There’s not an easy way to change the color of grid lines (without also changing the ticks, tick labels, axis labels, etc.). There should be, and it’d be nice if we could demonstrate a ggplot2-style theme.

**Comment by ericemc3** [comment]
It is aesthetically interesting to differentiate the appearance of certain grid lines:

![image](https://user-images.githubusercontent.com/17407796/118007499-7bc00400-b34c-11eb-818b-0625ea3ca5ea.png)

Note : this is possible with vega-lite: with the properties `gridOpacity` or `gridDash` for example, to which one can associate a function.
