### ISSUE TITLE
Tiny inconsistency with negative radius

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1145]
With Plot.geo, if you have a variable channel for _r_, geometries with a negative radius are filtered out. This consistent with Plot.dot, and while it might be suprising if the geometry isn't of a Point or MultiPoint type, it makes sense (for example, the geometry might be a FeatureCollection that contains Point geometries…).

However if you have a constant negative value for r (typically, r: -1), Plot.dot will discard all dots, but Plot.geo will not discard the geometries, and will call pointRadius(-1).

**Comment by mbostock** [comment]
Plot.dot doesn’t discard all the dots if you have a constant negative radius. It tries to render them as SVG circle elements by default, and you get an error in the console:

```
Error: <circle> attribute r: A negative value is not valid. ("-4")
```

If you switch to a different symbol, the dots will reappear as if the radius were positive, e.g.:

![untitled (68)](https://user-images.githubusercontent.com/230541/205339346-08ca7d89-43a2-4a1e-8117-5d115c888bcf.png)

```js
Plot.dot({length: 10}, {x: Math.random, y: Math.random, r: -40, symbol: "square"}).plot()
```

So, this is a bug in both Plot.dot and Plot.geo, but they are technically consistent and I don’t feel like it’s particularly urgent to fix. 🙂
