### ISSUE TITLE
inconsistent definition of identity between scales and projections

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1155]
For regular scales (e.g. x, y, color), "identity" is meant to opt out of any scaling and pass raw values. For projections, this is what _null_ does, and identity means a planar-rescalable projection.

Suggestion to rename the _null_ projection to "identity", and the identity projection to "planar". Another idea would be "planar-up" (for the current "reflect-y") and "planar-down" (for the current "identity").

**Comment by mbostock** [comment]
I’m not happy with any of the alternative words we considered, so I’d prefer to just leave this as-is even if it’s not perfect.
