### ISSUE TITLE
Shorthand for GeoJSON properties

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1172]
It’d be nice if Plot.geo supported shorthand for GeoJSON properties, e.g., 

```js
Plot.geo(counties, {fill: "rate"})
```

would be shorthand for

```js
Plot.geo(counties, {fill: d => d.properties.rate})
```

I’m not sure how to do it, though, because in theory the properties could be on the features directly, and we’d still want it to work in that case.

**Comment by Fil** [comment]
My understanding is that for Plot geo we could change the "string accessor" convention to be:
`field === "id" ? (d => d.id) : (d => d.properties[field])`

After checking for color names etc. To get a field that is not accessible through that convention, you'd have to create your own function accessor.

**Comment by mbostock** [comment]
That wouldn’t be backwards-compatible with the current behavior. But maybe it’s a small enough breakage that it’s okay. Or we could do something like this:

```
d => (d[field] === undefined ? d.properties : d)[field]
```

**Comment by mbostock** [comment]
I’m not sure where we’d make this change, though. Like, would you expect it to work with a bin transform’s call to valueof too? In which case we’d need to change the behavior of valueof globally for GeoJSON rather than just changing the channels of the geo mark.
