### ISSUE TITLE
Spike map

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1178]
Some way of generating this type of map would be nice:

https://observablehq.com/@d3/spike-map

**Comment by Fil** [comment]
Should we add the spike symbol to Plot? It needs a _base width_ parameter, so it can't really be a named symbol.
https://observablehq.com/@observablehq/plot-spike-map

**Comment by Fil** [comment]
Using a symbol (as I do in [this notebook](https://observablehq.com/@observablehq/plot-spike-map)) makes an incorrect use of the *r* scale. The spike would be better defined by a *length* scale. A good approach might be to make the vector mark’s path adjustable with a {draw} object, in https://github.com/observablehq/plot/blob/2b318acb99f6fc0a37512ddc55fef47301a852d5/src/marks/vector.js#L63, which would support angle and length.
