### ISSUE TITLE
Plot Tooltip Line Chart Bug While Notebook is Embedded

### ISSUE THREAD

**Issue by mcollie1** [observablehq/plot#1186]
There seems to be a bug with the tooltip when rendering numbers on a line chart. The tooltip isn't updating based on the data point of the given point along the line, but, instead, showing the same value. 

### Note

This happens when a notebook is embedded. The tooltip works fine within the notebook directly, but not while a notebook cell is embedded

**Comment by mbostock** [comment]
Can you share a notebook or live example that demonstrates the problem? There’s not a lot to go on with this description. Are you using Plot’s _title_ channel or are you using [Mike Freeman’s Plot tooltip plugin](https://observablehq.com/@mkfreeman/plot-tooltip)? I’m closing as I can’t investigate without further information but I will look if you respond.

**Comment by mcollie1** [comment]
Edit:

The numbers are updating, but the dates aren't

**Comment by mcollie1** [comment]
> Can you share a notebook or live example that demonstrates the problem? There’s not a lot to go on with this description. Are you using Plot’s _title_ channel or are you using [Mike Freeman’s Plot tooltip plugin](https://observablehq.com/@mkfreeman/plot-tooltip)? I’m closing as I can’t investigate without further information but I will look if you respond.

https://observablehq.com/@securityscorecard/most-prevalent-issues-over-time-widge
