### ISSUE TITLE
Custom ordinal color schemes

### ISSUE THREAD

**Issue by filipkis** [observablehq/plot#1218]
Hi, 

I would like to be able to somehow specify a custom color scheme so I can create my charts with our brand colors. As far as I saw from documentation and digging through the source code, there is no way to specify a custom scheme. On can use `interpolate` option, but that works only when there is a range, so not with ordinal scales. 

My suggestion would be that you check if scheme is an array or function and then threat it as custom color scheme, otherwise it behaves as it does now.

**Comment by Fil** [comment]
related: #630

We want to find a way to register schemes; for example maybe something like
> Plot.registerScheme({ "rainbow-company" : { ordinal: ["#ef3550", "#f48fb1", "#7e57c2", "#2196f3", "#26c6da", "#43a047", …] } })

would return an instance of Plot that knows about this new scheme.


For ordinal color scales you can already specify
> color: { range: ["#ef3550", "#f48fb1", "#7e57c2", "#2196f3", "#26c6da", "#43a047", …] }

but it's not exactly the same as an ordinal scheme.

**Comment by mbostock** [comment]
You can set the color.**range** option for a custom ordinal color scheme.

<img width="659" alt="Screenshot 2023-01-11 at 6 55 26 AM" src="https://user-images.githubusercontent.com/230541/211838395-fe3105df-2a5d-4429-80be-d8670979f58b.png">

```js
Plot.plot({
  color: {
    range: ["#36a2eb", "#ff6384", "#ff9f40", "#ffcd56", "#4bc0c0", "#9966ff", "#c9cbcf"],
    legend: true
  },
  marks: [
    Plot.dot(penguins, {x: "culmen_length_mm", y: "culmen_depth_mm", stroke: "species"})
  ]
})
```

**Comment by filipkis** [comment]
Thank you!
