### ISSUE TITLE
Undefined option properties change behavior of transform

### ISSUE THREAD

**Issue by tophtucker** [observablehq/plot#1222]
I just spent a while debugging why two Plots looked different. In one case, I was passing its options through JSON.stringify. I was surprised that changed anything, since my values were all `string | undefined`. Stringifying strips out undefined properties, but I'd assumed that having a key with value undefined would never change behavior in Plot. 

But, in the case of transform options, it does; these two are different:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/841829/212037846-a645e5b5-16e0-4e4a-9583-f754e66f6057.png">

Maybe Plot should ignore keys if their value is strictly undefined?

**Comment by mbostock** [comment]
We can switch this to a nullish check:

https://github.com/observablehq/plot/blob/49177a4a967f908463d7fbd2a7708e73256916ee/src/transforms/group.js#L163-L170
