### ISSUE TITLE
Documentation: Use of "date" as a fruit in marks API documentation is confusing to new users

### ISSUE THREAD

**Issue by langenhoff** [observablehq/plot#1233]
API documentation *Plot: Marks and Channels*
The use of "date" (the fruit) as an example is irritating. Suggestion: use a fruit that does not clash with other technical terms from plot.

**Comment by Fil** [comment]
I have fixed the title; we don't want users to be confused.

**Comment by langenhoff** [comment]
Sorry for the stupid question: is there some action required on my part?

Kind regards
Bernhard Langenhoff

--


[SDZ Signatur]<https://www.sdz.de/>

SDZ GmbH
Hauert 20, 44227 Dortmund

Bernhard Langenhoff

Tel.: +49 (0) 2 31 97 50 50 23
Fax: +49 (0) 2 31 97 50 50 50
***@***.******@***.***>



Geschäftsführer: Prof. Dr. Bernd Noche, Mathias Bös
Registergericht: HRB 7883 AG Dortmund, USt-ID-Nr. DE124727166

Wichtiger Hinweis: Diese e-mail kann Betriebs- oder Geschäftsgeheimnisse beinhalten. Sollten Sie diese e-mail irrtümlich erhalten haben, ist
Ihnen eine Verwendung oder Weitergabe ausdrücklich verboten. Bitte senden Sie die Nachricht an den Absender zurück und löschen Sie die Nachricht
anschließend inklusiv aller Anhänge von Ihren Systemen.
Vielen Dank für Ihre Kooperation.

Important Note: This e-mail and any attachment are confidential and may contain trade secrets and may well also be legally privileged or otherwise protected from disclosure. If you have received it in error, you are on notice of its status. Please notify us immediately by
reply e-mail and then delete this e-mail and any attachment from your system. If you are not the intended recipient please understand
that you must not copy this e-mail or any attachment or disclose the contents to any other person.
Thank you for your cooperation.

Von: Philippe Rivière ***@***.***>
Gesendet: Freitag, 20. Januar 2023 12:02
An: observablehq/plot ***@***.***>
Cc: Bernhard Langenhoff ***@***.***>; Author ***@***.***>
Betreff: Re: [observablehq/plot] Documentation: Use of "date" as a fruit in marks API documentation is confusing to new users (Issue #1233)


I have fixed the title; we don't want users to be confused.

**Comment by langenhoff** [comment]
Is adding an issue the appropriate way to suggest such minor things or should I use another channel? I am not sure, but I can't apply a label to an issue, can I?

**Comment by Fil** [comment]
It's OK; a comment on the notebook would have been fine, too. Thanks for the feedback.

**Comment by langenhoff** [comment]
Just for context: https://github.com/observablehq/plot/blob/main/README.md#marks 

below the quote from the marks documentation. For a non-native speaker (like me) it is not immediately obvious, that "Date" in the last line has nothing to do with "date" in the fruit example some lines above.

Quote:

Plot also supports columnar data for greater efficiency with bigger datasets; for example, data can be specified as any array of the appropriate length (or any iterable or value compatible with [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)), and then separate arrays of values can be passed as *options*.

```js
index = [0, 1, 2, 3]
```
```js
units = [10, 20, 40, 30]
```
```js
fruits = ["fig", "date", "plum", "plum"]
```
```js
Plot.dot(index, {x: units, y: fruits}).plot()
```

Channel values can also be specified as numbers for constant values, say for a fixed baseline with an [area](#area).

```js
Plot.area(aapl, {x1: "Date", y1: 0, y2: "Close"}).plot()
```

**Comment by mbostock** [comment]
I agree this is unintentionally confusing! I will pick a different fruit name. 🤦 A related challenge is that we also want a short name so that the axis label doesn’t get truncated with the default margins. 😅

**Comment by mbostock** [comment]
If I go with `"apple"` is that going to be confusing with `aapl`? 🤦
