### ISSUE TITLE
Generate a default (subtle) frame when faceting

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1251]
Ref. https://github.com/observablehq/plot/pull/1238#discussion_r1091025411

![image](https://user-images.githubusercontent.com/230541/216647749-731c9987-9d52-46d1-ad50-69c4b5667d9b.png)

Could be disabled by setting _facet_.**frame** to false, similar to the top-level **line** option.

**Comment by Fil** [comment]
Thinking about this again, the frame is often better for scatterplots, but noisy in other cases (for example, the histogram would be better server with an axis line). A new global **frame** option might be convenient though (which would default to false). It's not that typing "Plot.frame()" is too long, but by analogy with the **grid** option.

**Comment by Fil** [comment]
Another case where it would feel wrong to have this by default is the grouped bar chart.
