### ISSUE TITLE
Hexbin is not fixed to projected coordinates

### ISSUE THREAD

**Issue by mythmon** [observablehq/plot#1257]
https://observablehq.com/d/9adf8455382f0bf6

On the map in the above notebook, I've plotted eBird observations using Plot.geo and Plot.hexbin. When adjusting the translation of the projection, the hex bins stay fixed in screen space, instead of moving with the projection. This causes the binned representation to change, sometimes drastically. The effect is more noticeable when moving the Y slider.

I'm not sure that this is wrong, either from a Plot point of view or from a cartography point of view. However, it did make the person working with me, who is much more versed in birding and cartography than I am, react in horror. It seems to me at least surprising, and probably undesirable. The binning isn't wrong in either case, but I wouldn't expect it to change at all as I pan.

<table>
<tr>
	<td><img src="https://user-images.githubusercontent.com/305049/216885922-5189f207-8d5c-4af8-a0ab-431b2a3456d9.png">
	 </td>
	<td><img src="https://user-images.githubusercontent.com/305049/216885959-c6894f25-d4de-4b74-b3b1-b71707b896d1.png">
	</td>
</tr>
<tr><td>Translated down. Note the single bold hex</td><td>Translated up. Note the three bold hexes</td></tr>
</table>

**Comment by mbostock** [comment]
This is the intended behavior. The hexagons are positioned (and sized) in screen space, so the hexagons stay in the same position even as the x and y scales (or equivalent the projection) changes. Since the dots are moving but the hexagons stay in the same place, the association of dots and hexagons changes.
