### ISSUE TITLE
axis line + inset

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1260]
A slight regression: when we have an inset on a scale, and the line option is set, the line used to start at the inset; now it starts at the frame. (None of the existing tests has that configuration, but there was one in [this branch](https://github.com/observablehq/plot/pull/870).)

![recession-line-inset](https://user-images.githubusercontent.com/7001/217044383-f12dd847-1492-4b39-bb32-cd4ba9137003.png)
![inset+line](https://user-images.githubusercontent.com/7001/217044385-8be9cc91-1b19-49cf-b235-fd4feed382f2.png)

**Comment by mbostock** [comment]
I think it should be possible to propagate the scale’s insets to the implicit frame mark used to draw the line. I’m not totally sure we _should_ do this, though, because I think the idea of the line option is that it draws the edge of the frame, not the edge of the scale domain/range.

**Comment by Fil** [comment]
Yeah, I'm agnostic about this question. I just didn't want it to slip under the radar.

I like the argument with Plot.frame, since in that case it's clear we don't want to inset the frame.

Closing as wontfix
