### ISSUE TITLE
Finalize the design of the render API

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1263]
The render API still has a few quirks that we might want to address:

### Scales

The _scales_ argument is an object of D3 scale functions. This is inconsistent with how we expose the scales elsewhere. Currently internal marks need the scales for a few operations:
- to scale values out of band (for example, on X and Y for scaleProjection in the geo mark, and on color for the raster/contour/density mark); this can be replaced by _scale_.apply
- _isCollapsed_ tests the materialized domain (exposed as _scale_.domain)
- _applyTransform_ needs the materialized bandwidth (in the bar, tick marks…), it's exposed as _scale_.bandwidth
- axes want to call the scale.ticks function _which is not exposed_
- …more which I haven't located yet?…

If we passed the same objects that _plot_.scale("x") returns (_i.e._ scale descriptors), we need to pass the "ticks" function, or to recreate it from the descriptor.

### Facets

The _index_ passed to render is decorated with the facet information : the values of _fx_ and _fy_ for the current facet, as well as a facet index _fi_. (_fi_ is used internally for the raster mark.) This needs to be documented. Example [here](https://observablehq.com/@observablehq/autoplot-matrix).

### svg, parent element

Passing the svg, and the parent element, could help to build marks that need to use these (for instance, to add defs to the svg). They could be referenced in the _context_ argument. For example, #1304 experiments with passing the svg in the context. (This was done in 0.6.7.)

### Event listeners

A mark wants to listen to events (pointermove…), and send events (setting a value and sending a CustomEvent(input)). Needs an "official" api support rather than the mark fishing for the figure element. (Done in 0.6.7.)

### Update

Farther in the future, we might want to have a strategy to update a “layer”; this could happen by passing the previously returned node.

### Documentation

Once this is is decided and done (one way or another), a documentation notebook with examples will help advanced users who want to extend Plot.

(for an earlier version of this issue, see #501)

**Comment by mbostock** [comment]
(Clarified the issue title to make clear that we already have a render API, but that the design isn’t finalized and has the described quirks and outstanding questions.)

**Comment by mbostock** [comment]
Closing as we have done most of the work here, though there may be follow-up feature enhancements.
