### ISSUE TITLE
The auto mark doesn’t render histograms with the area mark correctly

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1274]
E.g.,

<img width="640" alt="Screenshot 2023-02-15 at 9 22 31 AM" src="https://user-images.githubusercontent.com/230541/219105358-3e12e10e-ba35-4a60-85d5-4593e06cb105.png">

```js
Plot.auto(weather, {x: "temp_max", mark: "area"}).plot()
```

On the other hand, the line mark renders fine:

<img width="641" alt="Screenshot 2023-02-15 at 9 21 58 AM" src="https://user-images.githubusercontent.com/230541/219105224-8c9a281d-1275-4aa5-9806-04027fa1a313.png">

```js
Plot.auto(weather, {x: "temp_max", mark: "line"}).plot()
```

**Comment by Fil** [comment]
It uses areaX https://github.com/observablehq/plot/blob/6eab4f235808d7deae1a75373ed20b4b3fbfbb08/src/marks/auto.js#L133; should use areaY instead in this case.
