### ISSUE TITLE
Support bigints?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1278]
Can we just change this:
```diff
function coerceNumber(x) {
-  return x == null ? NaN : +x;
+  return x == null ? NaN : Number(x);
}
```
(doing so does not break a single test, but there might be implications I haven't seen?)

Ref. https://github.com/observablehq/plot/discussions/1099; the use case is to facilitate passing database results to Plot.

**Comment by mbostock** [comment]
Yes, let’s do that.

**Comment by llimllib** [comment]
That will truncate bigints down to double precision (if I understand correctly) instead of erroring which is good, but isn't quite actual bigint support:

```
> Number(9999999999999999n)
10000000000000000
```

(Not trying to complain - just mentioning that it's an improvement but not full support)

**Comment by Fil** [comment]
Sure. Unless JavaScript had a way to "upgrade" computations to bigint (where 1n+1 would give 2n), I don't think we can have full support without completely rewriting everything (scales and all).

**Comment by llimllib** [comment]
👍  like I said, not complaining - this change would fix my problem immediately
