### ISSUE TITLE
validClassName doesn't like camelCase class names.  

### ISSUE THREAD

**Issue by pdebruic** [observablehq/plot#1345]
https://github.com/observablehq/plot/blob/e2749e8bd3f28305f02c7aa6e7f0d9c0f99e93cb/src/style.js#L417

validClassName.test('myNewClassName') fails.

**Comment by mbostock** [comment]
CSS class name selectors are case-insensitive, so consider using `mynewclassname` instead. But we should make this validation case-insensitive since it is a valid name.
