### ISSUE TITLE
valueof crashes on field accessor if some data are nullish

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1350]
example: `Plot.text(gods, Plot.treeNode({text: "field"}))` crashes with `TypeError: Cannot read properties of undefined (reading 'field')`

I wonder if this is not something to solve at a higher level: shouldn't `valueof([undefined, {a:1}], "a")` be `[undefined, 1]`?

**Comment by mbostock** [comment]
I don’t think we need to do this, or that this is a bug. It’s the same crash you get with `valueof(nullishdata, (d) => d.a)` which is what the field `"a"` is short for. You would need to write `valueof(nullishdata, (d) => d?.a)` instead if you want to handle nullish data, but I don’t see what we need to do this automatically.

**Comment by Fil** [comment]
In the case of the tree mark (or the treeNode transform), the fact that nodes are "undefined or string" is due to the internal processing logic—it's particularly difficult to understand why "node:name" works but "name" crashes (not that it would work anyway… let's say "length" would be a better example).

We can keep as is, but I figured it wouldn't hurt if, given a string (field accessor), valueof would return undefined on nullish values, rather than crash.
