### ISSUE TITLE
color legend doesn't account for fillOpacity

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#1356]
Color legends show the color with opacity: 1. Thus the legend might look quite different than the plot, in case you set the fillOpacity < 1

**Comment by Fil** [comment]
True, but it's not always what you'd want anyway. However, it might be useful to support an optional constant fillOpacity option in the legend options:

```js
Plot.dot(penguins, { fill: "island", fillOpacity: 0.2 })
  .plot()
  .legend("color", { fillOpacity: 0.2 })
```

**Comment by mbostock** [comment]
Yes, we should support an **opacity** option for the _color_ legend. (We already support a similar **color** option for the _opacity_ legend!)
