### ISSUE TITLE
Graphs, hierarchies?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#136]

**Comment by river-matt** [comment]
> Related, for graphs:
> 
>     * Plot.compose (#171)  to draw both dots and links
> 
>     * An example of a graph that is already “positioned”: https://observablehq.com/d/c54acc4426268a58
> 
>     * Using forceSimulation in a plugin https://observablehq.com/d/29e9f5c9191789f6

I'm unable to access, or that link is broken. I'd love to check out your approach to 'plugins' for Plot.

Aside: this library is as close as I've seen to providing the same grammar and ergonomics as a product like Tableau. Cool stuff!

**Comment by Fil** [comment]
I've updated and published the two notebooks. Let me know your thoughts!

**Comment by Fil** [comment]
A prototype for circle packing: https://observablehq.com/@fil/plot-circle-packing-136
