### ISSUE TITLE
Circular images

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1413]
E.g. [here](https://twitter.com/tanya_shapiro/status/1641581867781562369), it’d be really nice to have an easy way to apply a circular clip to the image mark

![untitled (45)](https://user-images.githubusercontent.com/230541/229024126-ebb325e9-cccd-42e4-a673-7ac2cc7dffe3.png)

Maybe rx/ry would work? Or maybe better, you specify an r option and then it works well with the dodge transform.

**Comment by Fil** [comment]
`<style>svg image {clip-path: inset(0 0 0 0 round 50%);}`

https://observablehq.com/@fil/spotify-pop-artists

**Comment by mbostock** [comment]
Oh wow, I had no idea it was so easy! Nice! I still think an **r** option would be nice to match the dodge transform. We could have it generate the clipPath style accordingly.

**Comment by Fil** [comment]
**r** would default **width** to _2r_, and add this clip-path? sounds good!

**Comment by Fil** [comment]
Edit: `<style>svg image {clip-path: circle();}` 

[spec](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) / [good browser support](https://caniuse.com/?search=clip-path).
