### ISSUE TITLE
Feedback on documentation

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1415]
_This issue is to collect feedback on the documentation after the launch of editor hints (aka typescript + jsdocs “intellisense“ documentation._ 

### text reducer

Two users simultaneously (in two different channels), asked about the **text reducer** in a bin or group transform. It was not obvious from the README that they needed to specify either both input and output, or a text reducer based on the reduced data. Hopefully could fix this in the reducer editor hint?

### More…

(add your own in the comments)

**Comment by mbostock** [comment]
Not sure this issue is actionable. Perhaps we should close (and refile a more specific issue on the text reducer documentation if needed).
