### ISSUE TITLE
Inconsistent arguments to channel functions

### ISSUE THREAD

**Issue by jamesscottbrown** [observablehq/plot#1419]
The [README](https://github.com/observablehq/plot/blob/main/README.md) states that:

> Channel functions are invoked for each datum (_d_) in the data and return the corresponding channel value.

However, this does not seme to be quite correct.

Suppose that I create a histogram, and want to use channel functions to set the `fill` and `fillOpacity`:

```js

const  getFill = (d) => {
   // Receives arguments corresponding to data rows
   // { species: "Adelie", island: "Dream", culmen_length_mm: 37.3, culmen_depth_mm: 17.8, flipper_length_mm: 191, body_mass_g: 3350, sex: "FEMALE" }
   
  console.log("getFill received arguments:", d);
  return "lightgrey";
}

const  getFillOpacity = (d) => {
  // receives arguments corresponding to *arrays* of the data rows grouped into a bar
  console.log("getFillOpacity received arguments:", d);
  return 0.8;
}

Plot.plot({
  y: {
    grid: true
  },
  color: {
    legend: true
  },
  marks: [
    Plot.rectY(data, Plot.binX({y: "count"}, {
      x: "flipper_length_mm",
      fill: getFill,
      fillOpacity: getFillOpacity,
    }))
  ]
})
```

([Observable notebook](https://observablehq.com/d/9884588d199c4b4c) of this example)

Looking at the console logs shows that the channel funtion for the `fill` is indeed invoked for each datum, but the channel function for the `fillOpacity` is instead invoked once for each *bar*, receiving an *array of data objects* each time.

This is not what I would expect from the documentation.

**Comment by Fil** [comment]
This case is documented like so:
> If a channel is declared only in options (and it is not a special group-eligible channel such as x, y, z, fill, or stroke), it will be computed after binning and be passed the binned data: each datum is the array of input data corresponding to the current bin.

Let's add this under #1415

**Comment by mbostock** [comment]
Yep, to add what @Fil said: the documentation is correct here. The **fillOpacity** function _is_ being passed the current datum and index, it’s just that it’s being invoked _after_ the bin transform, and hence the data has been transformed, and now the current datum is the array of values produced by the bin transform (assuming you haven’t specified a **data** reducer, which defaults to identity). You can change this behavior either by specifying a **fillOpacity** reducer, or by specifying a **data** reducer, on the bin transform.

**Comment by jamesscottbrown** [comment]
It is reasonable that after grouping, the data passed to the channel function is an array of items that have been grouped together.

What is more surprising that some channels are "special group-eligible", and that for these the channel function receives ungrouped data: it is not obvious that for the same data and mark, the meaning of "each datum (d) in the data" is different for different channels.

The statement in the bin section quoted by @Fil is clear, but it is a *long* way away in the documentation.

 I'd suggest adding a sentence to the [marks](https://github.com/observablehq/plot/blob/main/README.md#marks) such as:

> If a [bin](https://github.com/observablehq/plot#bin) or [group](https://github.com/observablehq/plot#group) transform is applied, then whether a channel is computed before or after binning depends on whether the channel is declared in both *options* and *outputs*, and on whether it is a special group-eligible channel such as *x*, *y,* *z*, *fill*, or *stroke*.
