### ISSUE TITLE
Misspelling a frame’s stroke produces a confusing error

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1449]
The frame mark doesn’t have data, but since it extends Mark, it tries to interpret the **stroke** option as a channel. This leads to a confusing error when you have a typo:

```js
Plot.frame({stroke: "bluez"})
```

The crash occurs when Plot tries to iterate over the data, which is null:

<img width="537" alt="Screenshot 2023-04-14 at 8 35 19 PM" src="https://user-images.githubusercontent.com/230541/232181058-97273f3d-50b6-487e-8bbc-76641b8174c6.png">

Since the frame mark doesn’t have data, we should never interpret the stroke as a channel. Though, it would be nice if somehow you could specify the stroke as an abstract value (*e.g.*, `stroke: "Biscoe"`) and that could get passed through the _color_ scale…

**Comment by Fil** [comment]
related #1439

**Comment by mbostock** [comment]
Kind of the same bug, but sometimes I want to create a frame where the fill color is specified abstractly. For example maybe I want the frame to represent the zero value of the color scale:

```js
Plot.plot({
  marks: [
    Plot.frame({fill: 0}),
    Plot.density(faithful, {x: "waiting", y: "eruptions", fill: "density", thresholds: 80, clip: true})
  ]
})
```

This crashes with

```
TypeError: t is not iterable
```

but what I want is the equivalent of this:

![untitled (69)](https://user-images.githubusercontent.com/230541/235317838-fb30e124-e412-4b78-b8ca-4083db730230.png)

```js
Plot.plot({
  marks: [
    Plot.frame({fill: d3.interpolateTurbo(0)}),
    Plot.density(faithful, {x: "waiting", y: "eruptions", fill: "density", thresholds: 80, clip: true})
  ]
})
```

So, maybe the solution here is that a frame has {length: 1} as its data instead of null?

Then perhaps we could re-interpret `stroke: "bluez"` as `stroke: ["bluez"]`, i.e., an abstract value. That would allow you to say `stroke: "adelie"` in the categorical color scale case, which is nice!
