### ISSUE TITLE
Repeating axes on both sides (axis: "both")?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#148]

**Comment by Fil** [comment]
https://observablehq.com/@fil/dual-axis-bar-line-chart is a (kinda complicated) proof of feasibility.

**Comment by mbostock** [comment]
This issue refers to the same scale on both sides, for redundancy.

**Comment by Fil** [comment]
yes, _axis: "both"_ will be much simpler than that.

**Comment by Fil** [comment]
not *that* simple, because there were a few details to take into account: https://github.com/observablehq/plot/pull/631
