### ISSUE TITLE
Gallery additions

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1488]
Notebook: https://observablehq.com/@observablehq/plot-gallery

General
- [x] Make everything unlisted or public
- [x] Add brief descriptions to each section
- [x] Release Plot 0.6.6
- [ ] Reorder examples within sections for progressive complexity and to group related examples

Dot, Image, Text
- [x] [Scatterplot with one ordinal dimension](https://observablehq.com/@observablehq/plot-scatterplot-with-ordinal-dimension)
- [x] [Scatterplot with radius (r) encoding](https://observablehq.com/@observablehq/plot-proportional-symbol-scatterplot)
- [x] [Scatterplot with color encoding](https://observablehq.com/@observablehq/plot-concise-colored-scatterplot)
- [x] [Scatterplot with diverging color scheme](https://observablehq.com/@observablehq/plot-colored-scatterplot)
- [x] [Scatterplot with two ordinal dimensions, group, radius encoding](https://observablehq.com/@observablehq/plot-ordinal-scatterplot)
- [x] [2D bin transform with size encoding](https://observablehq.com/@observablehq/plot-dot-heatmap)
- [x] [Hexbin hexagons with color](https://observablehq.com/@observablehq/plot-olympians-hexbin)
- [x] [Hexbin hexagons with size](https://observablehq.com/@observablehq/plot-hexbin-binwidth)
- [ ] [Beeswarms (dodge)](https://observablehq.com/@observablehq/plot-dodge-cars) (TODO break this apart)
- [x] [Beeswarm with color and faceting](https://observablehq.com/@observablehq/plot-dodge-penguins)
- [x] [Image beeswarm (dodge)](https://observablehq.com/@observablehq/plot-image-dodge)
- [x] [Barley Trellis plot](https://observablehq.com/@observablehq/plot-barley-trellis)
- [x] [Faceted scatterplot of penguin culmens](https://observablehq.com/@observablehq/plot-two-dimensional-faceting)
- [x] [Faceted scatterplot of penguin culmens and facet exclude context](https://observablehq.com/@observablehq/plot-non-faceted-marks)
- [x] [Stacked congress member gender](https://observablehq.com/@observablehq/plot-stacked-dots)
- [x] [Bubble map](https://observablehq.com/@observablehq/plot-dot-sort) (TODO remove sorting checkbox)
- [x] [One-dimensional dot histogram](https://observablehq.com/@observablehq/plot-dot-bins)
- [x] [Wealth & Health of Nations animation](https://observablehq.com/@observablehq/plot-wealth-health-nations)
- [x] Scatterplot with tooltips (Mike Freeman’s plugin)

Bar, Cell, Rect
- [x] [Alternate grouped bar chart example](https://observablehq.com/@observablehq/plot-olympians-grouped-bar-chart)
- [x] [Crimea stacked rects example](https://observablehq.com/@observablehq/plot-crimean-war-recty)
- [x] [Crimea stacked bars example](https://observablehq.com/@observablehq/plot-crimean-war-bary)
- [x] [Gradient bars](https://observablehq.com/@observablehq/plot-gradient-bars)
- [x] [Germany traffic patterns heat map](https://observablehq.com/@observablehq/plot-sorted-heatmap)
- [x] [Pre-binned data using d3.bin](https://observablehq.com/@observablehq/plot-prebinned-histogram)
- [x] [Stacked unit (?) chart](https://observablehq.com/@observablehq/plot-colored-stacked-bar-chart)
- [x] [Another diverging bar chart](https://observablehq.com/@observablehq/plot-state-population-change)
- [x] [Single stacked bar chart](https://observablehq.com/@observablehq/plot-stacked-percentages) or [alt](https://observablehq.com/@observablehq/plot-single-stacked-bar)
- [x] [County bounding boxes](https://observablehq.com/@observablehq/plot-county-boxes)
- [x] [Max Roser’s poverty chart](https://observablehq.com/@observablehq/plot-cumulative-distribution-of-poverty)
- [x] [Stacked histogram](https://observablehq.com/@observablehq/plot-vertical-histogram)!
- [ ] Rename calendar examples to differentiate
- [ ] Remove duplicate binned box plot examples

Area, Line
- [x] [Single-series line chart](https://observablehq.com/@observablehq/plot-simple-line-chart)
- [x] [Multi-series line chart](https://observablehq.com/@observablehq/plot-multiple-line-chart)
- [x] [Multi-series line chart with labeled lines](https://observablehq.com/@observablehq/plot-labelled-multi-line-chart)
- [x] [Wiggle streamgraph](https://observablehq.com/@observablehq/plot-stack-offset) (TODO use wiggle)
- [x] [Expanded (normalize) streamgraph](https://observablehq.com/@observablehq/plot-normalized-stack)
- [ ] [RIAA stacked area (appearance order)](https://observablehq.com/@observablehq/plot-stacking-order-and-reverse) (TODO remove inputs)
- [x] [Index chart](https://observablehq.com/@observablehq/plot-index-chart) ~~(TODO add index date)~~
- [x] [GISTEMP scatterplot with moving average](https://observablehq.com/@observablehq/plot-line-with-moving-average)
- [x] [arealineY composite mark ](https://observablehq.com/@observablehq/plot-arealiney-custom-mark)
- [x] [Minimal faceted area](https://observablehq.com/@observablehq/plot-faceted-areas)
- [x] [Minimal horizon chart](https://observablehq.com/@observablehq/plot-unemployment-horizon-chart)
- [x] [Ribbon chart (value order)](https://observablehq.com/@observablehq/plot-ribbon-chart)
- [x] [Variable-color area](https://observablehq.com/@observablehq/plot-variable-fill-area)
- [x] [Line with missing data](https://observablehq.com/@observablehq/plot-line-chart-with-gaps)
- [x] [Continuous histogram](https://observablehq.com/@observablehq/plot-density-estimation) ~~(TODO rename? remove warning?)~~
- [x] [Rolling minimum and maximum](https://observablehq.com/@observablehq/plot-window-reduce)

Geo
- [x] [Shockwaves](https://observablehq.com/@observablehq/plot-shockwave)

Rule, Tick
- [x] [Germany traffic patterns](https://observablehq.com/@observablehq/plot-sorted-groups)
- [x] [Simple lollipop chart](https://observablehq.com/@observablehq/plot-lollipop)
- [x] [Temperature variation band chart](https://observablehq.com/@observablehq/plot-band-chart-with-rule)
- [x] [Bar chart with emphasis tick](https://observablehq.com/@observablehq/plot-bar-and-tick)

Vector
- [x] [Wind map (of actual wind)](https://observablehq.com/@observablehq/plot-wind-map)
- [x] [Spike map](https://observablehq.com/@observablehq/plot-spike-map-example)
- [x] [Perlin noise](https://observablehq.com/@observablehq/plot-perlin-noise)

Contour, Raster, Density
- [x] [Projected raster vapor](https://observablehq.com/@observablehq/plot-raster-projection)
- [x] [Density skew (weight) interactive](https://observablehq.com/@observablehq/plot-density-weighted)

Arrow, Link, Tree, Vector
- [x] [Barley Trellis plot with arrows](https://observablehq.com/@observablehq/plot-barley-trellis-arrows)
- [x] [Tree diagram](https://observablehq.com/@observablehq/plot-tree-flare)
- [x] [Cluster diagram](https://observablehq.com/@observablehq/plot-cluster-flare)
- [x] [Indented tree diagram](https://observablehq.com/@observablehq/plot-custom-tree-layout)

Axes
- [x] [Axis with wrapped labels](https://observablehq.com/@observablehq/plot-wrap-tick-labels)
- [x] [Ggplot2-style axes](https://observablehq.com/@observablehq/plot-ggplot2-style-axes)
- [x] [Datawrapper-style axes](https://observablehq.com/@observablehq/plot-datawrapper-style-date-axis)
- [x] [New York Times-style axes](https://observablehq.com/@observablehq/plot-nyt-style-axes)
- [x] [Data-based axis](https://observablehq.com/@observablehq/plot-data-based-axis)
- [ ] Axis with overlaid grid lines (TODO)

Delaunay, Voronoi
- [x] Spherical Voronoi (using d3-geo-voronoi)

**Comment by tophtucker** [comment]
I've added all of "Dot, Image, Text" except those with outstanding todos, those with broken thumbnails (I don't have edit permission on the example notebooks), and the one that depends on 0.6.6 (image beeswarm). Moving on to "Bar, Cell, Rect"…

**Comment by mbostock** [comment]
Looks great! Good work!
