### ISSUE TITLE
Getting started documentation request: Vanilla JS with no CDN

### ISSUE THREAD

**Issue by simonw** [observablehq/plot#1496]
The "Getting Started" documentation at https://observablehq.com/plot/getting-started is missing one option, which is the one I want to use.

I'd like to use Observable Plot in a Vanilla HTML + JavaScript app that doesn't get built by webpack etc - so I don't want to use the `npm` option.

The [Plot in vanilla HTML](https://observablehq.com/plot/getting-started#plot-in-vanilla-html) option is almost what I'm looking for:
```html
<div id="myplot"></div>
<script type="module">
import * as Plot from "https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6/+esm";
const plot = Plot.rectY({length: 10000}, Plot.binX({y: "count"}, {x: Math.random})).plot();
const div = document.querySelector("#myplot");
div.append(plot);
</script>
```
Except... I don't want to depend on a CDN for my application. I prefer to load assets from my own `/static/` folder.

So what I'm trying to figure out is the right way to download Observable Plot such that I can have a file - or a bunch of files - in `static/` in my own application, and then write code that looks like this:
```html
<script type="module">
import * as Plot from "/static/observable-plot.js";
</script>
```
I'd prefer if this resulted in a single HTTP request to a bundled file because I can't be sure my users will be deploying to hosts that support efficient HTTP/2 for loading many files at once, but a solution that loads a few dozen ES modules would be OK with me too if the bundle option can't be easily created.

Guidance on how to best do this would be greatly appreciated! I tried to figure it out myself using `npm` and `vite` and suchlike but my JavaScript packaging knowledge isn't up to scratch.

**Comment by mbostock** [comment]
Thanks for the good suggestion. We don’t currently provide a single-file ES Module bundle, but we do provide a UMD bundle you can download add use if you don’t mind using the `Plot` (and `d3`) global.

First you’d need to download these files:

https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6
https://cdn.jsdelivr.net/npm/d3@7

E.g., using curl:

```bash
curl 'https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6' > plot.js
curl 'https://cdn.jsdelivr.net/npm/d3@7' > d3.js
```

Then you can load them like so:

```html
<!DOCTYPE html>
<div id="myplot"></div>
<script src="d3.js"></script>
<script src="plot.js"></script>
<script type="module">
const plot = Plot.rectY({length: 10000}, Plot.binX({y: "count"}, {x: Math.random})).plot();
const div = document.querySelector("#myplot");
div.append(plot);
</script>
```

Perhaps Plot could offer a single-file ES module bundle, but then we’d also have to provide a separate D3 ES module bundle, too. 🤔

**Comment by mbostock** [comment]
I think maybe the answer here is that someone should write a “downloader” tool that downloads the compiled ES modules from jsDelivr (or other CDN) and rewrites the import statements to use relative paths. Then you could just download this URL

https://cdn.jsdelivr.net/npm/@observablehq/plot/+esm

and you’d get the direct dependencies

https://cdn.jsdelivr.net/npm/d3@7.8.4/+esm
https://cdn.jsdelivr.net/npm/isoformat@0.2.1/+esm
https://cdn.jsdelivr.net/npm/interval-tree-1d@1.0.4/+esm

and the transitive dependencies and so on as separate files.

**Comment by simonw** [comment]
I built the first version of that tool! https://github.com/simonw/download-esm

**Comment by mbostock** [comment]
Nicely done @simonw! Thank you for sharing.

**Comment by simonw** [comment]
Wrote about it here: https://simonwillison.net/2023/May/2/download-esm/

**Comment by hrbrmstr** [comment]
Threw together a Golang version based on @simonw's Python module: https://github.com/hrbrmstr/esmdl
