### ISSUE TITLE
text dx and dy cannot accept function

### ISSUE THREAD

**Issue by winner106** [observablehq/plot#1528]
```js
 Plot.text(driving, {x: "miles", y: "gas", text: (d) => `${d.year}`, dy: d.year % 5 === 0 ? -6 : 10})
```
the following code not working
```js
dy: d.year % 5 === 0 ? -6 : 10
```

**Comment by yurivish** [comment]
That is because it is (currently) a constant rather than channel option: https://observablehq.com/plot/features/marks#mark-options

>  Option values that must be the same for all of a mark’s generated shapes are known as constants, whereas option values that may vary across a mark’s generated shapes are known as channels.

There's some discussion in this PR about converting more options to channels: https://github.com/observablehq/plot/pull/909

**Comment by mbostock** [comment]
The `dx` and `dy` options are constant options, not channels. If you want to specify varying values, you need to declare multiple marks. For example, you could filter:

```
[
  Plot.text(driving, {filter: (d) => d.year % 5 === 0, x: "miles", y: "gas", text: (d) => `${d.year}`, dy: -6}),
  Plot.text(driving, {filter: (d) => d.year % 5 !== 0, x: "miles", y: "gas", text: (d) => `${d.year}`, dy: 10}),
]
```

**Comment by winner106** [comment]
thank you very much,  I got it !
