### ISSUE TITLE
Tip text positioning doesn't always pad top correctly

### ISSUE THREAD

**Issue by hellonearthis** [observablehq/plot#1578]
Using. "@observablehq/plot-0-6-7" tip:  In chrome browser (Version 113.0.5672.93 ) on win 10

Notebook that it happens on. https://observablehq.com/@hellonearthis/looking-at-using-ai-classify-an-age-specific-english-word-di#clu

The top padding seems to not happen sometimes.

![image](https://github.com/observablehq/plot/assets/121805/e85639bd-d5d9-4cb8-90e5-4a7b408a9343)

**Comment by Fil** [comment]
I'm able to reproduce by setting

```
title: d => `



Hello`
```

or

```
title: d => `Hello



`
```

In other words, when the title has empty lines at the beginning or at the end.

<img width="276" alt="Capture d’écran 2023-05-18 à 10 11 30" src="https://github.com/observablehq/plot/assets/7001/f661d587-55b5-4f5a-a6f1-ee8773bc93d0">
