### ISSUE TITLE
Tooltips (e.g., for a scatterplot, or for a multi-line chart)?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#158]
Related #4 which talks more generically about pointer interaction.

**Comment by tannerlinsley** [comment]
Brainstorming thoughts:
- HTML and/or SVG?
- Hoist/Portal the tooltip out into parent elements or body?
- Plot inside of the tooltip to create table-like lists with the same x/y/color/size encodings?
- Create multiple, detached tooltips (imagine a textY anchored to each y value in a series along a hovered date)
- Animation would be 😍  It could be done manually at the very least if the right abstractions/inversions-of-control are supplied

**Comment by derekperkins** [comment]
Those are great ideas @tannerlinsley

**Comment by simonw** [comment]
I'm increasingly building visualizations and dashboard that are intended for mobile screens, so something that makes titles Just Work there (presumably through tap events) would be fantastic.

**Comment by reubano** [comment]
Would love to have tooltips! I've been using https://github.com/observablehq/plot/issues/4#issuecomment-823952456.

**Comment by mbostock** [comment]
This is close enough to #4 that I’m going to combine the issues to consolidate discussion. Progress is happening!
