### ISSUE TITLE
Shorthand tip annotation

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1583]
Currently you can add a single tip annotation like so:

```js
Plot.tip(
  [`Apple stock drops 8% after the company misses Q2 revenue targets and reports declining iPhone sales. It reaches a two-year low of $90.34 on May 12.`],
  {
    x: new Date("2016-05-12"),
    y: 90.34,
    dy: 3,
    anchor: "top",
    title: Plot.identity
  }
)
```

Should we support shorthand syntax for the tip mark where if the *data* is a string, then the *data* defaults to a singleton, and the **title** channel defaults to identity?

```js
Plot.tip(
  `Apple stock drops 8% after the company misses Q2 revenue targets and reports declining iPhone sales. It reaches a two-year low of $90.34 on May 12.`,
  {
    x: new Date("2016-05-12"),
    y: 90.34,
    dy: 3,
    anchor: "top"
  }
)
```

Or is that too magical?

**Comment by mbostock** [comment]
Maybe we could just default the **title** channel to *identity* if the data is strings. I think we already do that for the text mark with the **text** channel? So feels parallel.

**Comment by Fil** [comment]
It's tempting but it means a divergence between how strings are handled in this mark vs. others, which risks introducing a bit of confusion.
