### ISSUE TITLE
Separate positive and negative fill colors for areas (for difference charts), or an area clipping channel or mark (and then use two marks).

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#159]

**Comment by Fil** [comment]
My plugin mentioned above is infinitely more complex than filling the space with vertical rules, as Zan suggested.

**Comment by mbostock** [comment]
It looks like since June 29 the [difference chart example](https://observablehq.com/@observablehq/plot-difference-chart@327) no longer uses clipping? But I believe that approach isn’t viable when the curve is affected by multiple points (even in the case of _linear_, but most acutely with _basis_)?

Here is a take using a render transform and a compound mark:

https://observablehq.com/d/1e37e3c09876e460

Before:
![untitled (60)](https://github.com/observablehq/plot/assets/230541/0cbf0c11-46ae-4c85-9626-8b58c004b3ef)

After:
![untitled (61)](https://github.com/observablehq/plot/assets/230541/9ec70806-14d4-40d4-9d7e-129323df1753)

**Comment by Fil** [comment]
Yes I simplified it since in that case the clipping approach was overkill, and I wanted to revisit the implementation when we did #1109  (Also, you may have noticed that I had inadvertently switched the colors!)
