### ISSUE TITLE
`imageFilter` does not apply any filter on the SVG

### ISSUE THREAD

**Issue by AnatoleLucet** [observablehq/plot#1608]
Hey :wave: 

I'm trying to apply a drop-shadow on a line mark. I've tried with `imageFilter: "drop-shadow()"` but I don't see any change nor any CSS filter property in the generated SVG.

For instance ([source from your codebase](https://github.com/observablehq/plot/blob/0490ba6f1dba3403ed050e453e9c0839ecf635a5/test/plots/penguin-species.ts#LL71C13-L71C24)):
```typescript
Plot.plot({
  marks: [
    Plot.barY(
      penguins,
      Plot.groupX(
        {y: "count"},
        {
          x: "species",
          fill: "species",
          imageFilter: "drop-shadow(3px 3px red) sepia(40%) drop-shadow(-3px -3px currentColor)"
        }
      )
    ),
    Plot.ruleY([0])
  ]
})
```

**Comment by Fil** [comment]
This feature hasn't been released yet, it will be in version 0.6.7 (which you can build from main, see https://github.com/observablehq/plot/blob/main/CONTRIBUTING.md#documentation for instructions).

**Comment by AnatoleLucet** [comment]
@Fil Thanks. Is there any way to do something similar in the current version?

**Comment by AnatoleLucet** [comment]
Ok no worries, I just noticed there's an 0.6.7-rc.1 on NPM.
