### ISSUE TITLE
Default to SI (~s) for log tick format instead of exponential, or ,~f?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#161]

**Comment by mbostock** [comment]
This seems like a good idea still?

**Comment by Fil** [comment]
let's do it! I see three places where we can intervene:

1) in src/axis.js : createAxis; simple and tested, but not super satisfying:
> if (scale.base && scale.base() === 10 && tickFormat === undefined) tickFormat = "~s";

2) in src/quantitative.js, ScaleLog; by overwriting its tickFormat function (lots of code, just to replace a string on line 111 of https://github.com/d3/d3-scale/blob/main/src/log.js#L109)

3) in d3's tickFormat, either switch to "~s" (breaking change), or allow to set this differently…

**Comment by mbostock** [comment]
I’ll take a crack at (3).

**Comment by Fil** [comment]
upstream fix https://github.com/d3/d3-scale/commit/13491ee35c64d987fa9c4c1be22636d124f7f191
