### ISSUE TITLE
The pointer transform should consider dx/dy when finding the closest point?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1619]
The pointer transform currently ignores **dx** and **dy** when searching for the closest point. It should probably consider these? (I’d guess it is easy to incorporate them.) E.g.,

```js
Plot.plot({
  marks: [
    Plot.dot(penguins, Plot.pointer({x: "culmen_length_mm", y: "culmen_depth_mm", fill: "red", r: 8, dy: 20})),
    Plot.dot(penguins, {x: "culmen_length_mm", y: "culmen_depth_mm", dy: 20})
  ]
})
```

**Comment by Fil** [comment]
I don't know… we'll use dx for text labels and that would not move the control points.

**Comment by mbostock** [comment]
Good enough for me. 😄
