### ISSUE TITLE
Pointer choses the first of coincident points, but rendering shows the last

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1620]
Because of z-order, the last mark “wins” when rendering, but the pointer interaction chooses the first mark, which is inconsistent.

**Comment by Fil** [comment]
I was wrong when I made that remark. The test is `<=` so the last one wins.

https://github.com/observablehq/plot/blob/5c2f198aee917448a613f3be4a831a933283d7e0/src/interactions/pointer.js#L131
