### ISSUE TITLE
the voronoi mark should consider the pointer as indicating which cell to show

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1622]
The voronoi diagram is computed at render for the subset (grouped by Z) of the index, but with Plot.pointer what we mean is "show this cell from the (unpointed) voronoi", not "create a voronoi from this one point".

**Comment by mbostock** [comment]
I prefer to frame this more generally as: the Voronoi mark should compute the Voronoi diagram during initialization, and then render a subset of cells using the passed index at runtime. In other words, the Voronoi mark shouldn’t know about the pointer transform, but it should respect the index that is passed to the render function, which may be a subset of the index during initialization.
