### ISSUE TITLE
Document piecewise/polylinear scales

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1637]
The documentation for continuous scales only covers two-element domains and ranges, but we support an arbitrary number of elements. This is most useful for color scales. We should document how this works.

Ref. https://github.com/observablehq/plot/pull/1633#issuecomment-1563159407

**Comment by Fil** [comment]
Revise this in light of #1637

**Comment by Fil** [comment]
duplicate of #2107 (or, the other way around), closed by #2112
