### ISSUE TITLE
Ability to exclude tip channels

### ISSUE THREAD

**Issue by net** [observablehq/plot#1638]
Arguably only the channels in the channels mark option should be rendered in the tip, if the channels option is given.

**Comment by mbostock** [comment]
Thanks for the feedback! You can suppress this behavior by specifying a **title** channel and supplying the content yourself. We don’t distinguish between “extra” channels declared in the **channels** option _vs._ normal channels. We may support a way to suppress specific channels using custom formatting (e.g., setting the format to null for a given channel); that is covered by #1612, so I’m going to consolidate this issue into that one.

**Comment by net** [comment]
Maybe I'm missing something, but I don't see how to supply bold text for channel labels or color squares for color channels with the title option to match the default tip rendering.

**Comment by net** [comment]
Is the channels mark option just for rendering tips? I can't find any documentation on it outside of the channels tip mark. If so it really seems more intuitive to me that it override the rendered channels rather than append to the rendered channels; in that way it can also be used for full control over the order channels are rendered in the tip.

**Comment by Fil** [comment]
> Is the channels mark option just for rendering tips?

no

> I can't find any documentation on it

There's a mention [here](https://observablehq.com/plot/features/transforms): "additional channels can be declared using the mark channels option", but tbf it doesn't say that this is available outside of initializers.
