### ISSUE TITLE
Optionally clip marks to the canvas area?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#165]
And related, you might want overflow: visible on the SVG element?

**Comment by Fil** [comment]
We can imagine two use cases:

1. hiding the values that exceed the domain's bounds 
2. putting them a few pixels to the left of the min (resp. right of the max); maybe linked to the unknown/others properties (see #446)

Any idea for a syntax?

**Comment by mbostock** [comment]
Motivating application: https://observablehq.com/@observablehq/plot-horizon-chart

Here I could see us supporting a `clip: true` option for the *x* and *y* scales. But in some cases I could see us wanting to control the clipping on a per-mark basis. I’d rather implementing the clipping functionality centrally, though; I don’t want each Mark to have to implement it on its own.
