### ISSUE TITLE
Faceting breaks suggested react implementation

### ISSUE THREAD

**Issue by danielgamage** [observablehq/plot#1654]
In the 0.6.7 release (excited to see tooltips, btw! :) ), faceting seems to break [the suggested react integration](https://observablehq.com/plot/getting-started#plot-in-react) with the virtual Document implementation.

### Broken example

https://codesandbox.io/s/plot-react-forked-r0iiwi?file=/src/App.js:419-503

Notes:
- This works in 0.6.6 (can downgrade in package.json in the link)
- This also seems to work in non-react-SSR contexts like Observable ([example](https://observablehq.com/d/7175926c2b421c49))

Potentially related to the other recent facet issue, but I won't connect it to this since I'm unsure!

**Comment by mbostock** [comment]
Fixed. I copied over the latest implementation that the comment links to:

https://github.com/observablehq/plot/blob/main/docs/components/PlotRender.js

Note that interaction doesn’t work server-side rendering in React. (I couldn’t figure out how to implement it without React’s virtual DOM preventing Plot from getting access to the real DOM elements.) But you can use the useEffect approach and render on the client.
