### ISSUE TITLE
className for ramp legend gets appended with '-ramp'

### ISSUE THREAD

**Issue by akrawitz** [observablehq/plot#1661]
When I provide a `className` of `"testing"` for a ramp legend:
```js
    Plot.legend({width: 320, color: {type: "linear"}, className: "testing"})
```
The resulting `<svg>` has a class of `"testing-ramp"` instead of simply `"testing"`.

This is unexpected based on the documentation here:
https://observablehq.com/plot/features/legends#legend-options

I think this is due to #1446.

**Comment by mbostock** [comment]
This is intended. I can clarify the behavior in the documentation, though.

**Comment by akrawitz** [comment]
Thanks for clarifying and adding to docs!
