### ISSUE TITLE
spurious "high cardinality" warning

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1667]
We're sometimes seeing "high cardinality" warnings when in fact the cardinality is not so high.
Here's a slightly contrived example (simplified down from a real-life use case):

```
Plot.plot({
  height: 200,
  marks: [
    Plot.frame(),
    Plot.lineY(aapl.slice(0, 9), {
      x: "Date",
      y: "Close",
      stroke: (d) => d.Date.getUTCDay(),
      fy: (d) => d.Date.getUTCDay(),
      marker: true
    })
  ]
})
```

Here we have 5 facets, four of which have 2 data points, and the last one has 1—which triggers the warning.
![](https://github.com/observablehq/plot/assets/7001/887a1c75-94f3-4447-b17a-5a94781d01f0)

we should probably check that G.size is greater than, say, 10, before warning:
https://github.com/observablehq/plot/blob/df3a3add051049986c029fdad727bd64c929e622/src/style.js#L255-257

“high cardinality” is also tested in Plot.auto, I think.

**Comment by mbostock** [comment]
A further reduction, we can eliminate the facets since groupIndex is called separately for each facet:

```js
Plot.lineY(aapl.slice(0, 1), {x: "Date", y: "Close", stroke: (d) => d.Date.getUTCDay(), marker: true}).plot()
```

So yeah. We should definitely not issue this warning in the case of a single data point. Maybe we should start there? Or do you think there are other cases in 2–10 that are spurious too?

**Comment by Fil** [comment]
It's fun seeing a message about "high cardinality" with a cardinality of 3, but you're right: that's not the issue. See #1668.
