### ISSUE TITLE
"median" window reducer stopped working in v0.6.7

### ISSUE THREAD

**Issue by leoluk** [observablehq/plot#1690]
As of plot `v0.6.7`, this code no longer works:

```js
Plot.plot({
  marks: [
    Plot.line(
      data,
      Plot.windowY(
        {
          k: 4,
          anchor: "end",
          reduce: "median"
        },
        {
          x: "date",
          y: "cat"
        }
      )
    )
  ]
})
```

`mean` works while `median`, `variance` and others don't.

Example notebook: https://observablehq.com/d/1a581f1609384865

Perhaps I'm holding it wrong, but [the docs](https://observablehq.com/plot/transforms/window#window-options) look borked too:

<img width="530" alt="image" src="https://github.com/observablehq/plot/assets/859697/ae8cce45-2bb9-43a9-a66e-5ac165455049">

**Comment by mbostock** [comment]
Thanks for the report! We will investigate.

**Comment by Fil** [comment]
The fix is merged in main, and will be in the next [release](https://github.com/observablehq/plot/releases). The documentation is fixed already :)
Thank you!
