### ISSUE TITLE
Empty bin behavior in `group*`

### ISSUE THREAD

**Issue by hausdorff** [observablehq/plot#1695]
`binX` optionally allows empty groups as a semi-hidden feature via `filter: null`. `groupX` and friends do not (as far as I know) have equivalent behavior. This makes sense since it's hard to know all the groups to zero out _a priori_. But for `tip: true` if you set (_e.g._) `x: { domain [...] }`, you _can_ get empty groups, and the gaps in interaction model are noticeable.

I could imagine a few solutions to this. One solution is to have an `impute` or something alongside the reducer APIs in marks like `group`. @mbostock suggests that `group` might take a `domain`, similar to the behavior of `x`. I do not have a clear sense of the implications of either change but my view is that something like `impute` is likely to be more generally useful and less duplicative. The disadvantage is that if you continue down that route you may end up re-implementing Arquero.

**Comment by Fil** [comment]
I'm trying to explore this suggestion here: https://observablehq.com/@observablehq/empty-groups-and-tip-true-1695

In this —admittedly contrived— example, I make the empty groups “grab the pointer” and show a tip that says “nothing in this group”, but I don't really like the feel of it.

In this case, wouldn't it feel nicer if instead of ((empty group)) we did not show a tip at all? We can probably agree that when the **title** is "", the tip could just not show at all (but still grab the pointer). For now, you'll have to imagine it :)

**Comment by hausdorff** [comment]
Hmm, could be missing the point, but I think the `((empty group))` tips are actually confusing here because of the "visual ontology" of the chart itself, rather than because having tips for empty groups is confusing in and of itself.

_cf_., the appearance of `((empty group))` in these contexts:

* You get an `((empty group))` for the 0 of each bin, _e.g._,
  <img width="379" alt="Screenshot 2023-06-16 at 5 46 21 PM" src="https://github.com/observablehq/plot/assets/1409156/787b3d3a-8405-4c94-ab02-8b539f48142a">
* Interspersed throughout the groups are additional 0-groups, _e.g._,
  <img width="354" alt="Screenshot 2023-06-16 at 5 58 59 PM" src="https://github.com/observablehq/plot/assets/1409156/71d4ebac-4de3-4034-91f0-1ab1a10fbc85">

In contrast, for our (real-world) use case, I think it probably does make sense for the tip below to say there are 0 services in `experimental` and `deprecated` buckets.

<img width="697" alt="Screenshot 2023-06-16 at 6 07 15 PM" src="https://github.com/observablehq/plot/assets/1409156/64e89834-b3fc-41ba-b3df-a375d60adbe2">

**Comment by Fil** [comment]
Now I see, thank you for the example! Here is how I would do this with the current codebase: add the domain (“imputed”) to the data, and replace the count reducer by a “count-1”.
<img width="644" alt="Capture d’écran 2023-06-17 à 09 28 55" src="https://github.com/observablehq/plot/assets/7001/d887a477-accf-42b5-8b5f-fe44377a3659">

**Comment by Fil** [comment]
Closing since this seems to solve the issue. Can reopen if necessary.
