### ISSUE TITLE
barycentric extrapolation should not override interpolation

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1700]
I have made a mistake when designing the “extrapolation” part of the barycentric interpolator. Adding points to the frame can create huge distortions when the frame doesn't include all data points—for example when we zoom in on a region.

If we think that points that live inside the convex hull should be governed by the normal triangulation (as I do now), we have to rethink how extrapolation works.

**Comment by Fil** [comment]
I have explored a solution here: https://observablehq.com/@observablehq/barycentric-extrapolation-1700

**Comment by mbostock** [comment]
Looks good to me!
