### ISSUE TITLE
Plot Cheatsheets are not reachable anymore. It redirects instead.

### ISSUE THREAD

**Issue by hastebrot** [observablehq/plot#1702]
For some reason https://observablehq.com/@observablehq/plot-cheatsheets-layouts?collection=@observablehq/plot-cheatsheets redirects to https://observablehq.com/plot/?collection=%40observablehq%2Fplot-cheatsheets.

Same for https://observablehq.com/@observablehq/plot-cheatsheets-layouts. I can reach this page via Google Search, but once I navigate to another notebook in the collection, it will redirect me to https://observablehq.com/plot/.

![Screenshot 2023-06-19 at 14 03 32](https://github.com/observablehq/plot/assets/496255/1c322daf-dbeb-4e9a-acfb-80bace5d3a9f)

**Comment by hastebrot** [comment]
Hmm, on second sight this looks intentional, e.g "Transforms" cheatsheet notebook redirects to "Transforms" plot documentation page. And looking at the last edit date the cheatsheets are maybe out-of-date.

**Comment by Fil** [comment]
Yes we have obsoleted them, at least for now. Seemed better to focus our efforts on the integrated documentation website.
