### ISSUE TITLE
Portal support for tips

### ISSUE THREAD

**Issue by tannerlinsley** [observablehq/plot#1719]
Plot is great for spark lines and what not, but tips start to get clipped or overlapped easily in smaller dimensions. Being able to have tips portal up to the body or specified location would be 👨‍🍳 💋 🤌
<img width="182" alt="Screen Shot 2023-06-23 at 3 51 58 PM" src="https://github.com/observablehq/plot/assets/5580297/47d47d52-60b5-4bf5-998d-4260a6f4e870">

**Comment by tannerlinsley** [comment]
cc @derekperkins

**Comment by mbostock** [comment]
Can you workaround using `position: relative; z-index: 2; overflow: visible;` on the SVG?

We intentionally didn’t do portals because it makes it much harder to keep the tip in sync with the plot (e.g., with responsive plots that resize with the window).

**Comment by tannerlinsley** [comment]
I got this to work :) Thanks Mike! I'll close this for now until it becomes more of a concern (possible as we continue to roll out charts across various UI sections of our app)
