### ISSUE TITLE
Arrow sweep strategy

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1739]
To make an arc diagram such as https://observablehq.com/@d3/arc-diagram, I want to use the arrow mark with a bend angle of 90°, to draw the half-circles connecting a source to a target in the graph.

However currently this always draws the arc in a “clockwise”[1] manner from the first point (x1, y1) to the second point (x2, y2), which means that in most cases the arrow will go either to the left or to the right, depending on whether y1 > y2.

[1] clockwise, becomes counter-clockwise when bend is < 0.

Visually, what I get is the image on the left; what I want is the image on the right:
<img width="565" alt="Capture d’écran 2023-07-08 à 16 30 37" src="https://github.com/observablehq/plot/assets/7001/46f694d1-8a31-49dc-bc66-dad2673bbd6d">

To reach this goal, I can:
1. check how the source and target are ordered in the y domain, and reverse them as needed. This implies that the channels now depend on the scale (not good); 
2. draw both source-target and target-source arrows, and clip them to the frame—provided the main axis is the left edge of the frame (also not very good);
3. write a render transform that reverses the sweep-flag on the generated path (it works, but… 😵‍💫).

PR #1740 introduces a new option **sweep** that allows to control this at render time.

**Comment by mbostock** [comment]
Could this be done as an initializer that swaps the source and target based on the y position?

Could this be done as an option on the arrow mark that computes the sweep flag based on the y position of the source and target? (And similarly for the x position?)

Again, I don’t think we want to use a render transform here. The render transform is the “big hammer” that we probably only want to use for animation and interaction.

**Comment by Fil** [comment]
I have a PR ready, where it's happening in the render function; I'm just struggling to write the documentation because it's hard to explain in clear terms what is happening.

**Comment by Fil** [comment]
#1740 adds a **sweep** option on the arrow mark to control the "sweep order", and flip the sweep flag as necessary.
