### ISSUE TITLE
Incorrect tip when y1 and y2 have different labels

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1748]
Reported by @ramonaisonline:

![image](https://github.com/observablehq/plot/assets/230541/fa300d91-9f5a-4137-8a70-fcf0c8985ce1)

The label “low” here feels like a bug because that label only applies to y2 and not y1. I would prefer to see “**high–low** 59.4–52.7” in the tooltip, which would make the meaning more clear: y1 is the high and y2 is the low. Alternatively we could break them out into separate lines.

(On the other hand when there is a consistent label such as “**temperature** 59.4–52.7” it makes sense to show a single line.)

**Comment by mahi98jat** [comment]
Hey @mbostock ! I would like to work on this issue #1748 about the "low" label in the tooltip. I'd be happy to take a shot at fixing it. Can you please assign it to me?

**Comment by mbostock** [comment]
@mahi98jat Sorry, we don’t assign tasks to outside maintainers. You’re welcome to contribute an unsolicited pull request if you like though! I may be working on this one myself.

**Comment by mahi98jat** [comment]
@mbostock Thank you responding! I'd love to contribute.
