### ISSUE TITLE
Should *any* constant property be expressible, somehow, as a data-driven channel if desired?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#175]
Mike's comment:
> My working assumption is that Marks currently get to decide whether a property is a constant or a channel (or either, e.g., with maybeColor), so if a given Mark doesn’t expose what you want, we either need to change the Mark definition to make it more flexible, or extend the Mark to create a new one. I do think it ends up being simpler if a Mark implementation can declare something as a constant property, rather than needing to support every property as possibly being data-driven. Also, even for constant properties, you can make things somewhat data-driven by declaring multiple marks (as in the Marimekko example) and possibly filtering the data.

**Comment by Fil** [comment]
This question comes up often, and it's not easy to remember which of the properties are constants (basically you discover by trying and failing).

Maybe marks should accept constants (without checking that they may be field names), but *when their typeof is function*, use the function. It would need to be passed the datum.

**Comment by mbostock** [comment]
I don’t think we should do anything immediately here, and this issue has been open for a while, so I am going to close so we can focus on more actionable items. We can always revisit this issue if we keep being frustrated by certain options only being channels, but I think switching to everything potentially being a channel will add complexity and burden to mark implementations that we should avoid if possible.

**Comment by tobiassjosten** [comment]
Would it be an option to pick some properties and make those into channels? I'm thinking specifically of `dy` and `dx` for the text plot, which I right now would have loved to offset differently depending on the data.

**Comment by Fil** [comment]
Yes, see the work in progress #909
