### ISSUE TITLE
Typing of `binX` seems to be incorrect

### ISSUE THREAD

**Issue by on3iro** [observablehq/plot#1762]
Hey folks,

we just tried using `binX` and apparently its type is not correct (see screenshot):

![image](https://github.com/observablehq/plot/assets/8681413/85e22693-fd77-461b-9526-2a03dae7e94f)

The type does not expect `y` as a property. However inside the plot-docs there are examples showing exactly that use case, e.g.:

```ts
Plot.binX({y: "sum"}, {x: "culmen_length_mm", y: "body_mass_g"})
```

**Comment by mbostock** [comment]
It works for me:

<img width="651" alt="Screenshot 2023-07-23 at 11 25 00 AM" src="https://github.com/observablehq/plot/assets/230541/5d6a8415-1f64-4c76-8720-78f654213fdc">

```js
function binTypeTest() {
  const data = [];
  type ChartAxisHistogramData = any;
  return Plot.plot({
    marks: [
      Plot.rectY(
        data,
        Plot.binX(
          {y2: "sum"},
          {
            x: "x",
            y: (axisData: ChartAxisHistogramData) => {
              axisData;
              return null;
            },
            fill: "feature1Value",
            mixBlendMode: "multiply"
          }
        )
      )
    ]
  });
}
```

Perhaps you are running an old version of TypeScript? There were some improvements to generics in TypeScript 5; you might try upgrading.

**Comment by on3iro** [comment]
@mbostock thanks for looking into this. All of our relevant dependencies are up to date unfortunately :/
