### ISSUE TITLE
Tip & faceting

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#1778]
I happened to notice an oddity with selections and faceting: https://observablehq.com/d/a03f70ae5c5962c4 

It might be related to https://github.com/observablehq/plot/issues/1776 but I can still reproduce the behavior I'm seeing with `PlotF` from the [notebook](https://observablehq.com/@observablehq/facet-and-pointerx-1777) linked in https://github.com/observablehq/plot/pull/1777 so it does not look like the fix for that one also fixes this one.

<img width="522" alt="image" src="https://github.com/observablehq/plot/assets/114388/eabea9f0-9a2c-4a82-9c1d-51ec4b8e9bdf">

In this plot, the selection can sometimes be `null` even though the user is hovering over an item. Giving the plot a wide `width` fixes it, so it might have to do with the transition between facets and the sequencing of the events that triggers. Interestingly, moving from left to right seems to work, but not right to left.

**Comment by Fil** [comment]
Thanks for the report! It's a different bug, which happens when two facets change their value at the same time: they both dispatch an event, and the last one wins.

**Comment by yurivish** [comment]
🎉 Thanks for the fix!
