### ISSUE TITLE
Flickering tip

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#1805]
I recently built a page that has some charts using `tip`s as chart annotations controlled by a range slider, and noticed that the tooltips sometimes "flicker" before being rendered at their final position. I was following along with tip development a while back and if I remember, there's some layout computation that happens post-initial render, so I wonder if it might have to do with that.

I created a mini test case [here](https://observablehq.com/d/6ea54bc9b4b83de8). It's hard to get a screenshot, but in Chrome & Safari on macOS I see the tip text appear at the bottom right of the annotated datum for just a moment while I slide the slider, before re-appearing at the top left as requested by the `anchor` option, along with the rest of the tip.

**Comment by mbostock** [comment]
Thanks for the test case. Yes, this is because the tip renders asynchronously — we need the tip to be attached to the DOM in order to compute exact text metrics as described here:

https://github.com/observablehq/plot/blob/63415aa43c1fafb2b18c1cb7f73a3bea9066504f/src/marks/tip.js#L217-L218

We can probably find a way to hide the tip text so that it’s not briefly visible before the tip finishes rendering.

**Comment by Fil** [comment]
please paste this in your notebook to test #1826: 

~~~js
Plot = import("https://esm.sh/gh/observablehq/plot@834810e5e05193191a97ab6d750c4f329a97bd55")
~~~

It's not perfect in the sense that the tip doesn't have time to show, but at least it's not showing in the wrong place.

**Comment by yurivish** [comment]
Thank you @fil and @mbostock! This is much better – and yeah, I suspect with SVG layout there may always be tradeoffs to make. And cool, I didn't know you could import specific hashes with esm.sh; I've been cloning the repository and rebuilding locally to try out Plot branches. Thanks for the tip.

**Comment by Fil** [comment]
I recently learned this trick from @mootari; the documentation at https://esm.sh is worth a read!
