### ISSUE TITLE
Unable to override default tree delimiter

### ISSUE THREAD

**Issue by thenbe** [observablehq/plot#1849]
The custom delimiter should replace the default delimiter, instead of being appended to it.

Repro: https://observablehq.com/d/96ac483a54482567

<details><summary>Code</summary>
<p>

```javascript
data = [
	'foo;bar;http://www.example.com',
	'foo;bar;https://www.example.com/posts/1',
	'foo;baz;https://www.example.com/posts/2',
];

Plot.plot({
	axis: null,
	height: 100,
	margin: 10,
	marginLeft: 40,
	marginRight: 120,
	marks: [Plot.tree(data, { delimiter: ';' })],
});
```

</p>
</details>

### Expected

In Plot.tree, declaring a custom delimiter `;` should result in a tree where only `;` is used as a delimiter.

### Actual

In Plot.tree, declaring a custom delimiter `;` results in a tree where _both_ `;` and `/` are used as delimiters.

**Comment by Fil** [comment]
Thanks for the report! See #1850 for a potential fix

**Comment by mbostock** [comment]
Oh, yikes. Good report! Thank you.
