### ISSUE TITLE
binX() typescript definition missing support for `fill`

### ISSUE THREAD

**Issue by seanlaff** [observablehq/plot#1862]
Per the docs at https://observablehq.com/plot/transforms/bin#bin-options
```ts
Plot.plot({
  y: {grid: true},
  color: {legend: true},
  marks: [
    Plot.rectY(olympians, Plot.binX({y: "count"}, {x: "weight", fill: "sex"})),
    Plot.ruleY([0])
  ]
})
```
```
Object literal may only specify known properties, and 'fill' does not exist in type 'BinXInputs<RectYOptions | undefined>'
```

**Comment by Fil** [comment]
It works for me in VS Code; can you give more details as to in what context you are seeing this error message?

**Comment by mbostock** [comment]
Note that TypeScript 5 or later is required to infer the types correctly from context; otherwise you have to specify the generic type explicitly.

**Comment by seanlaff** [comment]
Oh interesting- Im in vscode 1.82.0 (with "use workspace version of typescript") and see the error. Here's a minimal reproduction:

package.json
```json
{
  "dependencies": {
    "@observablehq/plot": "0.6.10",
    "typescript": "5.2.2"
  }
}
```
demo.ts
```ts
import * as Plot from "@observablehq/plot";

const data = [
  { name: "foo", sex: "M" },
  { name: "bar", sex: "F" },
];

Plot.plot({
  y: { grid: true },
  color: { legend: true },
  marks: [
    Plot.rectY(data, Plot.binX({ y: "count" }, { x: "weight", fill: "sex" })),
    Plot.ruleY([0]),
  ],
});
```

**Comment by lhwong** [comment]
> Note that TypeScript 5 or later is required to infer the types correctly from context; otherwise you have to specify the generic type explicitly.

Can anyone elaborate on how to do this to solve the problem?

**Comment by mbostock** [comment]
When you click on the `{}` curlies next to TypeScript in the bottom of your VS Code window, what do you see as your TypeScript version?

<img width="387" alt="Screenshot 2023-09-20 at 5 35 23 PM" src="https://github.com/observablehq/plot/assets/230541/91c505ea-0ad6-4cdf-96a4-b9a25668733f">

**Comment by lhwong** [comment]
> When you click on the `{}` curlies next to TypeScript in the bottom of your VS Code window, what do you see as your TypeScript version?
> 
> <img width="387" alt="Screenshot 2023-09-20 at 5 35 23 PM" src="https://github.com/observablehq/plot/assets/230541/91c505ea-0ad6-4cdf-96a4-b9a25668733f">
> 

I am using version 5.1.6.

**Comment by lhwong** [comment]
The following is a Angular project in which the issue can be simulated.

https://stackblitz.com/github/lhwong/myApp

**Comment by lhwong** [comment]
After upgrading Angular to pre-release version and using typescript 5.2.2, the problem persists.

**Comment by lhwong** [comment]
Managed to resolve the issue by replacing
    Plot.rectY(data1, Plot.binX({y: "count"}, {x: "Earnings", fill: "Listing", tip: true})).plot();

with
    const options = {x: "Earnings", fill: "Listing", tip: true};  
    Plot.rectY(data1, Plot.binX({y: "count"}, options)).plot();

**Comment by xvvvyz** [comment]
Ran into this as well. I solved it by explicitly passing RectYOptions to binX. e.g: `Plot.binX<RectYOptions>`
