### ISSUE TITLE
Example in ReadMe not self contained 

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#1882]
Depending on how strict you want to be with the examples in the changelog.md being self contained, the following example:

```
Plot.plot({
  height: 1080,
  marginLeft: 100,
  axis: null,
  x: {domain: [0, 1]}, // see https://github.com/observablehq/plot/issues/1541
  color: {domain: d3.range(10), unknown: "#ccc"},
  marks: [
    Plot.dot(miserables.nodes, {x: 0, y: "id", fill: "group", sort: {y: "fill"}}),
    Plot.text(miserables.nodes, {x: 0, y: "id", text: "id", textAnchor: "end", dx: -6, fill: "group"}),
    Plot.arrow(miserables.links, {x: 0, y1: "source", y2: "target", sweep: "-y", bend: 90, headLength: 0, stroke: samegroup, sort: samegroup, reverse: true})
  ]
})
```

from https://github.com/observablehq/plot/blob/main/CHANGELOG.md
uses the variable `samegroup` which is not defined.

**Comment by Fil** [comment]
Thanks. I think it's simple enough to be readable, and the image above the code links to https://observablehq.com/@observablehq/plot-arc-diagram?intent=fork which has the complete code.
