### ISSUE TITLE
react import of @observablehq/plot results in d3 error message `The requested module 'd3' does not provide an export named 'unixDay'`

### ISSUE THREAD

**Issue by cindyloo** [observablehq/plot#1890]
Chrome Version 117.0.5938.149 (Official Build) (arm64)
mac os Ventura
react v.17+

imports:
import * as Plot from "@observablehq/plot";
import { useRef, useEffect, useState } from "react";
import Stack from '@mui/material/Stack';
import Slider from '@mui/material/Slider';
import { CalendarPicker } from "@mui/lab";

trying to plot times as javascript new Date()

**Comment by Fil** [comment]
Is D3 up to date? unixDay was added in https://github.com/d3/d3/releases/tag/v7.7.0

**Comment by cindyloo** [comment]
this appears to not be in the npm installation of @observablehq/plot... is that not part of your updates?

**Comment by mbostock** [comment]
D3 is a dependency of Plot. You appear to have an older version installed that does not meet the version requirements in the package.json.

https://github.com/observablehq/plot/blob/32cd30116503a99c0497968b8f736a7769c0b1ff/package.json#L91

**Comment by cindyloo** [comment]
interesting b/c I uninstalled d3 and still received that message.. I'll have another look

**Comment by cindyloo** [comment]
had to delete `node_modules`, package-lock and `npm install`. Working now ty
