### ISSUE TITLE
Serialize Plot configuration as json

### ISSUE THREAD

**Issue by crambelsoupy** [observablehq/plot#1900]
Hi Team, Thanks for a great library. So, I've had read the docs and the API reference but haven't worked out if it's possible to serialize the configuration of a Plot object into Json or another string-based form, is this possible? The use case I have is I'd like to be able to transport a plot "configuration" across https and persist in a database.

**Comment by mbostock** [comment]
Serializability is a non-goal for us — assuming you mean something other than serializing arbitrary JavaScript. Plot is designed to be extended through JavaScript functions, whether as transforms, channel definitions, reducers, and myriad other ways. I expect you could make a serializable subset of Plot, but it’s not our goal to support this use case. You might consider Vega/Vega-Lite instead which is expressly designed for to be serializable and hence has its own DSL.
