### ISSUE TITLE
Feature request - Support for shared zooming and tooltip in facet

### ISSUE THREAD

**Issue by selvavm** [observablehq/plot#1917]
Often times one wants to zoom a timeseries data to understand the pattern. So, it would be nice if I zoom on one chart, all charts in the facet also zooms. Then if I hover on one chart, I should be able to see the simultaneous values in all charts.

**Comment by mbostock** [comment]
The zooming is covered by #1590.

The tooltip coordination across facets could be done with the filter render transform #1871.

I recommend we close this issue as duplicate, unless we want to reframe it as a more built-in solution to a tooltip that is shared across facets — in which case we might also want to consider a tooltip shared across *z*, kinda the opposite of #1574 #1671.
