### ISSUE TITLE
Add a function to Object.prototype cause Plot to generate empty chart

### ISSUE THREAD

**Issue by rockie-yang** [observablehq/plot#1925]
When I try to add a function to Object.prototype, Plot on version 0.5 and 0.6 will generate an empty chart. 

While it works properly in version 0.4.3. 

Illustrate the issue on observabehq https://observablehq.com/d/18d7f1591b7a4aa8. 

Can you please explain the reason behind it? 

If in this case we shall not touch any of the Object.prototype

**Comment by Fil** [comment]
It's a really intriguing bug. If you set Object.prototype._hello = "x"; and try the first test plot (aaplBollinger), it draws 1 line on the y axis. If you set Object.prototype._hello = "xxxxx" it draws 5 lines!

**Comment by rockie-yang** [comment]
That is in order to get most natural grammar by patch functions to prototype. 

For example, the function pick in underscore use.

    _.pick({name: 'moe', age: 50, userid: 'moe1'}, 'name', 'age');

And in ramda, it use

    R.pick(['a', 'd'], {a: 1, b: 2, c: 3, d: 4}); 

I would argue that the most natural way shall be either

    {a: 1, b: 2, c: 3, d: 4}.pick(['a', 'b'])

or 

    {a: 1, b: 2, c: 3, d: 4}.pick('a', 'b')

**Comment by mbostock** [comment]
You shouldn’t modify global prototypes such as Object.prototype. All bets are off when you do that!

**Comment by rockie-yang** [comment]
Thanks a lot @Fil and @mbostock for clarification. Does D3 has this prerequisite as well?
