### ISSUE TITLE
Selection of plot data using sliders

### ISSUE THREAD

**Issue by Hvass-Labs** [observablehq/plot#1926]
Hello,

I'm currently trying out Observable Plot in a normal HTML web-site using Javascript. It looks very well designed and implemented!

But I really need a range-slider for selecting a part of the data in a plot. For example, in a time-series plot with the dates on the x-axis and the values on the y-axis, I would like to select the start and end-dates using two sliders, and then using Javascript I want to pull out the data for that range.

I found this Notebook which looks really good:

https://observablehq.com/@bumbeishvili/data-driven-range-sliders

But it looks like it is only for bar-plots and I would need it for other kinds of plots such as line-plots. I'm also not a real Javascript programmer and the code is completely undocumented, so it would probably take me a long time to figure out how to modify it for my needs.

It would be incredibly useful if this was a standard feature in Observable Plot. Is this something you would consider adding in the near future?

Thanks!

**Comment by Fil** [comment]
yes, see #5
