### ISSUE TITLE
Disabling the stroke channel from the tooltip does not work for Plot.line()

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#1944]
When I use Plot.line() and try to disable the channel stroke from being displayed in the tooltip, it still shows.
To reproduce, I used an example from the Plot documentation which shows how to disable channels when displaying a tooltip. I just changed the Plot.dot() to Plot.line() and the column sex (from the stroke channel) is shown in the tooltip (despite being set to false) https://observablehq.com/d/7f9a4af27fea7c74

**Comment by mbostock** [comment]
That’s because the **color** channel is automatically being promoted to the **z** channel by the line mark. So you’ll need to add `z: false` to disable that, too.
