### ISSUE TITLE
Download option for embedded plot 

### ISSUE THREAD

**Issue by harrylojames** [observablehq/plot#1946]
It would be great to be able to add a download as option to the plot (similar to observable notebooks). This would be useful for embedded plots. The particular scenario I have in mind is Quarto HTMLs. 

For example, Plotly has a toolbar with a download option. 

![image](https://github.com/observablehq/plot/assets/51630653/62ae7f1d-4ce7-4bf5-9c8c-3305bfab7df7)

**Comment by Fil** [comment]
Here’s some code making use of [bubkoo/html-to-image](https://github.com/bubkoo/html-to-image) to convert to **PNG**:
https://observablehq.com/@fil/hello-html-to-image

Saving as **SVG** is also possible, with a different approach:
https://observablehq.com/@fil/plot-figure-to-svg

We want to ensure that these exports are possible, but I don't think we'll want to weave this type of tooling directly into Plot. Maybe there is a need for some kind of module/function that integrates the functions demonstrated in those notebooks?

**Comment by harrylojames** [comment]
@Fil Thank you for your reply! I had stumbled on those approaches and they work great. A module/function that integrates all of that to achieve what I described (overlaying a download option) would fit the bill for me.
