### ISSUE TITLE
remove the dark mode toggle?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1955]
Do we expect users to click on this link or use their system defaults?

**Comment by mbostock** [comment]
It’s possible to do this with some hacky CSS, but it’s pretty brittle and I expect it would break months from now with some future VitePress release. So I filed https://github.com/vuejs/vitepress/issues/3946, and I think wait for that or do nothing.

**Comment by Fil** [comment]
closed by https://github.com/observablehq/plot/pull/2109
