### ISSUE TITLE
Documentation page about axis mark turns empty if an interactive selection is made

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#1972]
![image](https://github.com/observablehq/plot/assets/7562919/0d6c35d8-d2e0-471c-a45f-59ea6e186fb3)

https://observablehq.com/plot/marks/axis
If I go to the middle and change for the interactive chart facetAnchor to be null, the whole page turns empty.
(Browser Google Chrome Version 120.0.6099.217 (Offizieller Build) (64-Bit) on Windows PC)

**Comment by Fil** [comment]
it logs this error: `invalid facet anchor: null`

**Comment by Fil** [comment]
Thanks for the report!
