### ISSUE TITLE
lineWidth is not working for text inside hover text (tip mark)

### ISSUE THREAD

**Issue by gl2324** [observablehq/plot#1981]
I am trying to put some longish text inside the [tip mark](https://observablehq.com/plot/marks/tip). The usual options to ensure automatic line breaks are not working like they are on Text or Labels as illustrated in this example

```js

responses = [
  {name: "Family in feud with Zucker­bergs", value: 0.17},
  {name: "Committed 671 birthdays to memory", value: 0.19},
  {name: "Ex is doing too well", value: 0.10},
  {name: "High school friends all dead now", value: 0.15},
  {name: "Discovered how to “like” things mentally", value: 0.27},
  {name: "Not enough politics", value: 0.12}
]

Plot.plot({
  y: {percent: true},
  marks: [
    Plot.axisX({label: null, lineWidth: 8, marginBottom: 40}),
    Plot.axisY({label: "↑ Responses (%)"}),
    Plot.barY(responses, {x: "name", y: "value", tip: {lineWidth: 8  }
}),
    Plot.ruleY([0]),
    
  ]
})
```

The x axis labels are wrapped but the hover text is not.

**Comment by mbostock** [comment]
Wrapping in the tip mark only applies when you use the **title** channel, not when you display all channels.

**Comment by gl2324** [comment]
Thanks for the quick reply.  Are there plans to implement this feature - automatic line wrapping on all channels in the tip mark - in the future?
