### ISSUE TITLE
Inverted Y axis with zero: true

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#1985]
If all values are the same, then the Y axis appears upside-down.

Example: https://observablehq.com/@yurivish/upside-down-y-axis

<img width="636" alt="image" src="https://github.com/observablehq/plot/assets/114388/ffbdc1ef-ebb0-4a18-bb83-f7cdeb9420f3">

If at least one value differs from the rest, then the Y axis appears right-side-up:

<img width="665" alt="image" src="https://github.com/observablehq/plot/assets/114388/355904c8-81b0-419d-913c-9a1fd0215d5e">

**Comment by mbostock** [comment]
Heh! Good one. We will investigate.

**Comment by aimerie** [comment]
I'm experiencing this as well. I'm glad to see there is an open bug already! Any idea if this will make the next release?
