### ISSUE TITLE
How to set numeric tick interval?

### ISSUE THREAD

**Issue by vwkd** [observablehq/plot#1994]
## Description

According to the types, `tick` can be a `RangeInterval` which can be a number defining the tick interval.

> a number (for number intervals), defining intervals at integer multiples of *n*

However, this conflicts with another type of `tick` which can be a `number` defining the tick amount.

From testing, it seems setting `tick` to a number is always interpreted as tick amount.

How can I set a numeric tick interval?

## Steps To Reproduce

```js
const data = [
  {x: 0, y: 0},
  {x: 1, y: 1},
  {x: 2, y: 2},
  {x: 3, y: 3},
  {x: 4, y: 4},
  {x: 5, y: 5},
]

Plot.plot({
  x: {
    ticks: 1
  },
  marks: [
    Plot.line(data, { x: "x", y: "y" })
  ]
})
```

## Expected Result

Tick interval of `1`, i.e. tick amount of `5`.

![tick_interval2](https://github.com/observablehq/plot/assets/33468089/e5a38bab-268b-4def-b9f7-263954ad9e98)

## Actual Result

Tick amount of `1`, i.e. tick interval of `5`.

![tick_interval](https://github.com/observablehq/plot/assets/33468089/72102b6f-061b-4567-8941-119f772a4037)

**Comment by mbostock** [comment]
You’d need a utility like this:

```js
function numberInterval(interval) {
  if (0 < interval && interval < 1 && Number.isInteger(1 / interval)) interval = -1 / interval;
  const n = Math.abs(interval);
  return interval < 0
    ? {
        floor: (d) => Math.floor(d * n) / n,
        offset: (d) => (d * n + 1) / n, // note: no optional step for simplicity
        range: (lo, hi) => d3.range(Math.ceil(lo * n), hi * n).map((x) => x / n)
      }
    : {
        floor: (d) => Math.floor(d / n) * n,
        offset: (d) => d + n, // note: no optional step for simplicity
        range: (lo, hi) => d3.range(Math.ceil(lo / n), hi / n).map((x) => x * n)
      };
}
```

Then you could say:

![untitled - 2024-06-08T102118 607](https://github.com/observablehq/plot/assets/230541/6b48954c-38e6-417e-a833-d1b6051d2b32)

```js
Plot.line(data).plot({x: {ticks: numberInterval(1)}})
```

where `data = d3.range(10).map((i) => [i, i ** 2])`.

Or, for an interval of 0.5:

![untitled - 2024-06-08T102200 363](https://github.com/observablehq/plot/assets/230541/a00c34d9-0442-4b79-8d83-0abdcbed150e)

```js
Plot.line(data).plot({x: {ticks: numberInterval(-2), tickFormat: String}})
```

As the last example shows, Plot doesn’t do a good job of specifying a default format if you specify a custom interval, so we’d probably want to fall back to number.toLocaleString.
