### ISSUE TITLE
schemeObservable10 Bug after Release

### ISSUE THREAD

**Issue by Cattiva** [observablehq/plot#2022]
Hi all,

since today, I'm experiencing a bug with all my plots that I'm using in a quarto document with ojs cells.

The Error message reads as:
**OJS Runtime Error: The requested module '/v135/d3@7.9.0/esnext/d3.mjs' does not provide an export named 'schemeObservable10'**

I'm importing the latest release of plot for the tooltip capabilities as 
```
Plot = import("https://esm.sh/@observablehq/plot")
```
If I comment this line out or roll back to the previous version, it works as expected.

Seeing that new releases of plot (v0.6.14) and d3 (v7.9.0) just came out, both containing schemeObservable10 in their release notes, I'm guessing something is wrong with the newest version.

Maybe you might have a look into this.

Best regards
Alex

**Comment by mbostock** [comment]
This seems to be a bug in esm.sh: it is loading d3-scale-chromatic@3.0.0, but the latest version of d3-scale-chromatic is 3.1.0. I suggest that you use jsDelivr instead, which does not have this bug.

```js
Plot = import("https://cdn.jsdelivr.net/npm/@observablehq/plot/+esm")
```

**Comment by Cattiva** [comment]
Many thanks for the very quick update :) Can confirm, it works now.

**Comment by mbostock** [comment]
I filed a bug with esm.sh here https://github.com/esm-dev/esm.sh/issues/810.

**Comment by maelp** [comment]
I have the same bug when importing the lib through uwdata/vgplot, it tells me this

```
error during build:
[vite-plugin-pwa:build] ../node_modules/.pnpm/@observablehq+plot@0.6.15/node_modules/@observablehq/plot/src/scales/schemes.js (51:2): "schemeObservable10" is not exported by "../node_modules/.pnpm/d3@7.9.0/node_modules/d3/src/index.js", imported by "../node_modules/.pnpm/@observablehq+plot@0.6.15/node_modules/@observablehq/plot/src/scales/schemes.js".
```

**Comment by mbostock** [comment]
You need to upgrade your transitive dependencies if you run into this issue. When the next version of D3 is released it will automatically upgrade transitive dependencies. https://github.com/d3/d3/pull/3886

**Comment by julien-signal** [comment]
Sharing my findings in case it helps somebody:

We use NPM workspaces and I ended up doing something like that in the root `package.json` file.

```
   "overrides": {
      "@observablehq/plot": "0.6.16",
      "d3": "7.9.0",
      "d3-scale-chromatic": "3.1.0"
    }
```

At first it didn't work *but* after deleting and regenerating the `package-lock.json` file, it did.
