### ISSUE TITLE
Rect mark doesn't work with `scale: { type: "log" }`

### ISSUE THREAD

**Issue by MaxwellBo** [observablehq/plot#2058]
<img width="557" alt="image" src="https://github.com/observablehq/plot/assets/5368490/3a5fb1b8-f075-42e8-a2f3-1eea27916176">

works, but `log` doesn't

<img width="558" alt="image" src="https://github.com/observablehq/plot/assets/5368490/8d8dfaf3-466e-45fc-9a71-c366cc0fee4e">

Curiously all other scale types work including `symlog`

<img width="558" alt="image" src="https://github.com/observablehq/plot/assets/5368490/42da508d-f6ec-4a34-8092-2737490017bf">

**Comment by mbostock** [comment]
The rect mark does work with a log scale. What doesn’t work is trying to encode the value zero with a log scale, which lives at infinity.
