### ISSUE TITLE
Dot / circle with centroid radius value isn't responsive to accessor changes

### ISSUE THREAD

**Issue by akre54** [observablehq/plot#2064]
Steps to reproduce:
* Visit https://observablehq.com/@observablehq/plot-us-bubble-map
* Change the map cell:
```diff
    Plot.dot(population, Plot.centroid({
-      r: "population",
+      r: d => d.population,
```
* Change it again:
```diff
    Plot.dot(population, Plot.centroid({
-      r: d => d.population,
+      r: d => d.population * 2,
```

Video:

https://github.com/observablehq/plot/assets/931368/0b7f4af0-e480-4243-9082-bebf425b4932

I would expect that the radius size of the bubbles double in response to this change, similar to the way that the legend updates. This also means that responsive values from notebook variables don't actually update the svg. I can confirm that this [works as I'd expect](https://observablehq.com/@akre54/leaf-values-for-miriam-glass-etching) using `Plot.image` and the `width` property. Is there something different with `r`?

**Comment by akre54** [comment]
Thanks @mbostock. Appreciate the quick response. I'm not seeing where the documentation is for setting the range or domain on a Mark. The Scales documentation seems to [imply](https://observablehq.com/plot/features/scales#continuous-scales) that I can pass a `domain` property, but I'm not seeing how to use that with the example map.

Is this right?

```ts
r: {
  value: 'population',
  range: [0, 5000],
  domain: [0, 10000],
},
```

This seems to work as I'd intend (where `negIconScale` is a viewof `Inputs.range`)

```ts
Plot.image(
  negGeoJson,
  Plot.centroid({
    src: negative.src,
    width: d => d.properties.earlier * negIconScale,
  })
),
```

Is `width` just treated differently as not a channel?

**Comment by mbostock** [comment]
It’s not a mark option; it’s the _r_ scale which is defined at the plot level. Edit the `r: {range: …}` line in the linked notebook.

**Comment by akre54** [comment]
Oh got it - I just grabbed a random notebook and I missed that. Thanks
