### ISSUE TITLE
Tooltip: mouseover information is output from the display

### ISSUE THREAD

**Issue by XavierBaume** [observablehq/plot#2068]
When I move the mouse over an element to the right of the heatmap, the information is removed from the view. I haven't managed to find any relevant code to counter this problem.

The visualisation is available at the following link: https://observablehq.com/d/8fe20474cd096a25

<img width="799" alt="Capture d’écran 2024-05-28 à 17 02 40" src="https://github.com/observablehq/plot/assets/145542531/ca18ab4c-74ed-43cb-ba83-7ce7a82b6f2c">

**Comment by mbostock** [comment]
The notebook you linked to is using D3, not Plot. We recommend switching to Observable Plot so that you can use Plot’s tip mark.
