### ISSUE TITLE
markerEnd and variable aesthetics

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#2093]
When using **markerEnd** on a line with variable aesthetics, the marker is shown on each and every segment:

<img width="498" alt="Capture d’écran 2024-06-17 à 11 13 02" src="https://github.com/observablehq/plot/assets/7001/8419da94-f32c-4f96-a8d3-fdeb450f1d3e">

This seems wrong, and it would be better to apply markerStart only on the first segment, and markerEnd only the last segment. marker should also probably be applied more sparingly to avoid duplications between the end of a segment and start of the following segment.

There is a work-around, but it doesn't feel great:

<img width="500" alt="Capture d’écran 2024-06-17 à 11 14 13" src="https://github.com/observablehq/plot/assets/7001/db5f3cd3-51d7-4cfb-ad9d-c9fccff02219">

see https://observablehq.com/@observablehq/plot-whirlpool-arrows

**Comment by mbostock** [comment]
Seems like `applyGroupedMarkers` should be able to do the “right thing” with respect to groups.
