### ISSUE TITLE
Document piecewise (polylinear) scales

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#2107]
Polylinear scales were released in [v0.2.5](https://github.com/observablehq/plot/releases/tag/v0.2.5), but I don't think they are documented besides the changelog https://github.com/observablehq/plot/blob/main/CHANGELOG-2021.md#025

(Here's an example https://observablehq.com/compare/bfbb63a16a2d77b5...ec5bc88b2782ca63)

**Comment by jketcham** [comment]
The data used in the example is from Tempe Bicycle Action Group's 2024 'Bike Count.' Volunteers were assigned intersections around Tempe, AZ to count bicycles at in two different shifts: one in the morning (7am-9am) and one in the evening (4pm-6pm). Counts were conducted during the last week of March on Tuesday, Wednesday and Thursday, and were bucketed by the volunteers into 15 minute bins, with additional attributes to indicate wrong way cycling, sidewalk riding, helmet usage, etc also tallied in the 15 minute bins.

More info available at: [https://www.biketempe.org/bike-count-data/](https://www.biketempe.org/bike-count-data/)
And another notebook with the data is here: [https://observablehq.com/@jketcham/tempe-bike-count-2024](https://observablehq.com/@jketcham/tempe-bike-count-2024)

Thanks @Fil!
