### ISSUE TITLE
Missing AreaY example in docs

### ISSUE THREAD

**Issue by gvanhorne** [observablehq/plot#2117]
Plot Area Mark documentation refers to a missing example

# Expected Behavior
Either show an example where the baseline of an area chart is y = 0, or remove reference to the area chart of Apple's stock price.

# Current Behavior
No example is provided.
![image](https://github.com/user-attachments/assets/dfd07f4c-cc0a-4ef0-8973-2b72844c16d2)

# Steps to reproduce
1. Goto https://observablehq.com/plot/marks/area#areaY
2. Verify whether an example is provided

**Comment by mbostock** [comment]
The example is shown at the top of the page:

```js
Plot.areaY(aapl, {x: "Date", y: "Close"}).plot()
```

I’ll delete this errant sentence that’s remains from moving content around. Thanks for the report!
