### ISSUE TITLE
Plot.tree creates overlaps

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#2125]
Is this the expected result?

~~~
Plot.tree(["/lib.esnext.regexp.d.ts","/lib.esnext.string.d.ts","/lib.webworker.asynciterable.d.ts","/plot/marks/difference.d.ts","/plot/marks/waffle.d.ts","/plot/transforms/shift.d.ts","/node_modules/@types/command-line-args/index.d.ts","/node_modules/@types/command-line-usage/index.d.ts","/node_modules/@types/hast/index.d.ts","/node_modules/@types/istanbul-lib-coverage/index.d.ts","/node_modules/@types/linkify-it/build/index.cjs.d.ts","/node_modules/@types/linkify-it/index.d.ts","/node_modules/@types/markdown-it/dist/index.cjs.d.ts","/node_modules/@types/markdown-it/dist/markdown-it.d.ts","/node_modules/@types/markdown-it/dist/markdown-it.min.d.ts"]).plot()
~~~

<img width="603" alt="Capture d’écran 2024-08-06 à 20 50 05" src="https://github.com/user-attachments/assets/e654fe7f-9b0c-4a08-9418-6a1c0548a260">

**Comment by mbostock** [comment]
Yes, it’s expected. Plot.tree doesn’t know how long the labels are.

**Comment by Fil** [comment]
My point is that plot/marks collides with lib.webwork…

**Comment by mbostock** [comment]
> My point is that plot/marks collides with lib.webwork…

The nodes don’t collide, just the labels overlap (because the orientation of leaf and internal nodes is different, and because the tree layout doesn’t make any accommodation for labels when laying out nodes). This is the expected behavior for the tidy tree algorithm.
