### ISSUE TITLE
Erroneous type definition for the tip {maxRadius} option

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#2134]
If you say `tip: {maxRadius: 100}`, the **maxRadius** option is correctly passed through to the pointer, affecting the interaction as expected; however our typescript defs reject it.

<img width="634" alt="Capture d’écran 2024-08-14 à 18 50 15" src="https://github.com/user-attachments/assets/93f49a9c-8624-4281-bfe1-c022d15a30e7">

**Comment by mbostock** [comment]
Fixed in #2132.
