### ISSUE TITLE
vertical︎↕︎ is displayed with the emoji font-variant

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#2146]
In #2141 I see an issue with Inter, the new font, which displays horizontal↔︎ as text and vertical︎↕︎ as emoji. (I don't know why it doesn't happen in main.)

![Capture d’écran 2024-08-23 à 11 23 49](https://github.com/user-attachments/assets/7deaf198-18f7-46a0-838c-99b584153a34)

This should be solved in the far future when browsers support [font-variant-emoji](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-emoji), but in the meantime we need to fix it somehow. I tried the variation selector `U+FE0E`, but it's filtered out for some reason, whether I write as `&#xFE0E;` or `&#65038;`. I think I'll just do a `span::after`.

**Comment by mbostock** [comment]
The reason it only happens in the design-tweaks branch is the difference in the font stack. In design-tweaks it is the [VitePress default](https://github.com/vuejs/vitepress/blob/d06273285951f4a3cd2f44245e145fb136e1385f/src/client/theme-default/styles/vars.css#L264-L265):

```
'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'
```

In main it is:

```
Inter, var(--vp-font-family-base)
```

Which expands to:

````
Inter, -apple-system, BlinkMacSystemFont, "avenir next", avenir, helvetica, "helvetica neue", ubuntu, roboto, noto, "segoe ui", arial, sans-serif
```

In other words, the VitePress default will bias towards choosing color emoji variants, whereas our font stack in main does not. I have one idea I want to try.

**Comment by Fil** [comment]
[e2d7730](https://github.com/observablehq/plot/commit/e2d77304d2198039023c79be4f0edcb50b849b00)
