### ISSUE TITLE
Donut or Pie chart

### ISSUE THREAD

**Issue by kzmKZuzmo** [observablehq/plot#2166]
Hey is there a way to create plot with donut or pie chart ?

**Comment by Fil** [comment]
duplicate of #80 (see also #85)

**Comment by kzmKZuzmo** [comment]
hey @Fil  so plot gonna be have or not the pie or donut ? I can't understand from (of https://github.com/observablehq/plot/issues/80 (see also https://github.com/observablehq/plot/pull/85)) that whether it will contain or not

**Comment by Fil** [comment]
It means we're working on it, but it's not a high priority; #85 shows one way to do it.
