### ISSUE TITLE
Waffle pattern does not account for strokeWidth

### ISSUE THREAD

**Issue by mootari** [observablehq/plot#2186]
When a Waffle mark has a stroke applied, the pattern size does not account for the added stroke width which causes neighboring strokes to bleed through at the edges.

Example:
```js
Plot.waffleX([6], {gap: 6, stroke: "black", strokeWidth: 5}).plot({height: 200})
```
<img width=600 src="https://github.com/user-attachments/assets/064a1411-e785-426c-bc17-10a9dc7f46b9">

**Comment by Fil** [comment]
Confirmed, will fix. Note that this only happens when the stroke is a constant, so a stopgap measure could be to write `stroke: () => "black"`.
