### ISSUE TITLE
`TypeError: o[n] is not a function` for empty color domain

### ISSUE THREAD

**Issue by jeremy-rifkin** [observablehq/plot#2210]
I'm setting up a plot where the data set used for the plot may be empty. In such cases, I end up passing `color: { legend: true, domain }` where `domain` is an empty array but this leads to an error. Here's a demo that produces the error due to an empty data set and empty domain https://observablehq.com/d/f1142c360da5114b.

Locally I see:

```
TypeError: I[i2] is not a function
    piecewise piecewise.js:9
    legendRamp ramp.js:95
    legendColor legends.js:53
    createLegends legends.js:76
    plot plot.js:325
    render_chart main.ts:110
    do_query main.ts:278
    onreadystatechange utils.ts:6
    http_get utils.ts:3
    do_query main.ts:263
    query_keystroke main.ts:66
    timeoutId utils.ts:23
    setTimeout handler*debounce/< utils.ts:22
    App main.ts:33
    <anonymous> main.ts:288
```

**Comment by Fil** [comment]
Minimal repro: `Plot.legend({color: {domain: []}})`.

**Comment by Fil** [comment]
Note that you could specify `type:"ordinal"` to fix it.

**Comment by mbostock** [comment]
Yeah, I think the bug here is that this should be interpreted as an ordinal scale rather than a linear scale. Something here…

```
  // If the domain or range has more than two values, assume it’s ordinal. You
  // can still use a “piecewise” (or “polylinear”) scale, but you must set the
  // type explicitly.
  if ((domain || range || []).length > 2) return asOrdinalType(kind);
```
