### ISSUE TITLE
How to aggregate other channels when grouping?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#265]
This works, the definition of the *text* channel is awkward:

![untitled-46](https://user-images.githubusercontent.com/230541/112065739-6b489580-8b22-11eb-8476-b8d4e145b647.png)
```js
Plot.plot({
  marks: [
    Plot.barX(penguins, Plot.stackX(Plot.groupZX({fill: "species", normalize: true}))),
    Plot.text(penguins, Plot.stackXMid(Plot.groupZX({text: ([d]) => d.species, z: "species", normalize: true}))),
    Plot.ruleX([0, 100])
  ]
})
```

I’d prefer something like this:

```js
Plot.plot({
  marks: [
    Plot.barX(penguins, Plot.stackX(Plot.groupZX({fill: "species", normalize: true}))),
    Plot.text(penguins, Plot.stackXMid(Plot.groupZX({text: "species", z: "species", normalize: true}))),
    Plot.ruleX([0, 100])
  ]
})
```

But this would require that the group transform know that *text* is a channel, and to aggregate it (by selecting the first value, presumably). And currently the group transform doesn’t need to know how to interpret the passed-in options, other than the ones that are specifically eligible for grouping (namely x, y, z, fill, stroke).

**Comment by oluckyman** [comment]
Just for the reference put an up to date working example here (as I landed on this issue while googling for an example of labelling sections on a stacked bar chart)
![image](https://user-images.githubusercontent.com/642673/126766202-68c2d15f-ff19-4ce0-bde7-17d7700f6c1f.png)

```
Plot.plot({
  marks: [
    Plot.barX(
      dtDiagnostics,
      Plot.groupY({ x: "count" }, { y: "subject", fill: "class" })
    ),
    Plot.text(
      dtDiagnostics,
      Plot.stackX(
        Plot.groupY(
          { x: "count" },
          { y: "subject", z: "class", fill: "white", text: (d) => d[0].class }
        )
      )
    )
  ],
  marginLeft: 100
})
```
