### ISSUE TITLE
Quartile/percentile reducers?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#309]
Maybe I’m overoptimizing for brevity here, but I feel like it’d be nice to have named quartile reducers for boxplots. You can always use `data => d3.quantile(data, 0.25)` instead, but `"quartile1"` is shorter.

**Comment by yurivish** [comment]
A common shorthand for tail latencies in the computer performance world is “p99” for 99th percentile and p999 for the 99.9th (and so on, eg. p50 for median).
