### ISSUE TITLE
Plot for VegaLite

### ISSUE THREAD

**Issue by dsrivast80** [observablehq/plot#316]
We need to add documentation to explain: 
- Similarities and differences between Plot and VL
- Examples to illustrate differences (and how Plot is easier in a lot of cases to use and get started with)
- When to use Plot over VL (and also when to not use Plot, where VL is better)
- Examples to illustrate the utility of Plot

**Comment by enjalot** [comment]
https://observablehq.com/@observablehq/plot-vega-lite
