### ISSUE TITLE
Create a "Getting Started" Guide for Plot

### ISSUE THREAD

**Issue by dsrivast80** [observablehq/plot#319]
We got strong feedback from the Friends Preview that we need to create a quick "Getting Started" guide so users can quickly understand the utility of Plot, and how to use it.

Quote from one of the ambassadors: 
"I was wondering how many of these (plethora of docs) I had to read before I could use Plot / make a single graph"

This will be imperative for success (adoption, engagement and retention) of Plot especially from folks new to dataviz/Observable.

**Comment by mbostock** [comment]
Is this sufficiently covered by the Plot cheatsheets #318 and the [Plot documentation](https://observablehq.com/@observablehq/plot)?
