### ISSUE TITLE
Add a "full series" option to the stack transforms

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#351]
See discussion at #325 and https://github.com/observablehq/plot/pull/348#issuecomment-830659582

**Comment by mbostock** [comment]
Datadog calls this “default zero” interpolation: https://docs.datadoghq.com/dashboards/functions/interpolation/#default-zero

I wonder to what degree this is specific to time series. I can certainly imagine cases where it’s _not_ specific to time series, but when it is, it seems like the bin transform with filter: null is an option for fixing the missing data.

**Comment by Fil** [comment]
It's worse than this: using the empty bin approach is necessary for a continuous ("binnable") domain, but far from sufficient—as soon as you have *z* or facets, you need a point (real or fake) for each element of the domain times each of the series.

**Comment by mbostock** [comment]
But the bin domain is the same across all groups and facets, so as long as you have at least one data point in a given group,  you’ll get all the bins?

**Comment by Fil** [comment]
In https://observablehq.com/d/f6a7975f2ad4519a there is no empty bin, but if we push up the number of bins to 200, we start to get the same issue of "interpolating above missing bins". Outlined in red in the image below, all the areas should drop to zero since there is no data point in this position.

<img width="624" alt="Capture d’écran 2021-08-12 à 22 39 00" src="https://user-images.githubusercontent.com/7001/129266908-a8500fb9-bf3f-49e1-b9e9-f20c0cd5e889.png">

(I'm not sure that we can find a generic way to do both operations, maybe imputing missing values is something that should be left to the data-wrangling section?)

**Comment by mbostock** [comment]
But that example doesn’t use filter: null on the bin transform, right?

**Comment by Fil** [comment]
possibly superseded by #499 and #500

**Comment by Fil** [comment]
closing since this example is solved with _filter: null_.
