### ISSUE TITLE
Adding a caption breaks the width option

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#356]
At least in Observable:
https://observablehq.com/d/d43f43d1f047af73

**Comment by git-ashish** [comment]
@Fil The referenced notebook doesn't appear to be public. Could you please share that? 
I tried adding captions to some plots along with width and it seemed to work.

**Comment by Fil** [comment]
I have just shared it.

**Comment by git-ashish** [comment]
Looks like its an issue with Observable's CSS which restricts the width of a `figure` element to 640px. 
![image](https://user-images.githubusercontent.com/2697421/117465392-4774ce00-af6f-11eb-8f2e-d4d65c3bc03a.png)

I have tested it locally and it seems to be working as expected. The specified width gets applied to the plot.

**Comment by git-ashish** [comment]
However, wondering if the dimensions should be applied to outermost element i.e. `figure`

**Comment by Fil** [comment]
see also #397
