### ISSUE TITLE
Support server-side rendered SVG?

### ISSUE THREAD

**Issue by knutwannheden** [observablehq/plot#359]
I would like to use Plot in a Svelte application and would prefer if I could render the SVG plots server-side, as for example explained in this [StackOverflow answer](https://stackoverflow.com/a/48107263/1732086) how it can be done with D3 and JSDOM. Since Plot builds on D3 I suppose the same approach should also work with Plot. But since Plot always directly calls `d3.select()` this currently doesn't seem to be possible.

It would be cool if Plot could also be used for server-side rendering as a plot can be a lot more compact in terms of data.

I would like to point out that I am very new to JavaScript and web frontend development, so I wouldn't know what limitations and further implications this may have.

**Comment by mbostock** [comment]
Plot depends on the global `document` being defined. If you set that (say using JSDOM), Plot will work.

**Comment by knutwannheden** [comment]
Excellent! I will try this out.

**Comment by knutwannheden** [comment]
FWIW, I am getting some weird `ReferenceError: global is not defined` error, but that is probably related to JSDOM or SvelteKit.

**Comment by Fil** [comment]
see all the [test/plots/](https://github.com/observablehq/plot/tree/main/test/plots), they are generated in node

**Comment by cristianvogel** [comment]
I have run into this issue in Svelte-kit.

I simply cannot get Plot to work as expected, even with the simplest example. 

for example.
`{#if $dataSets.length}
    {#each $dataSets as metadata, index }
        <thead class="tableTitle">{metadata.title.toUpperCase()}</thead>
        <BarChart data={metadata.columnsWithHeaders}/>
        <TableHTML data={metadata.columnsWithHeaders} {index} />
    {/each}
{/if}`

then in BarChart component 

`<script>

    import * as Plot from "@observablehq/plot";
    import { onMount} from "svelte";

    export let data
    let graphPlot

    onMount( () => {

        let d = [
            {units: 10, fruit: "fig"},
            {units: 20, fruit: "date"},
            {units: 40, fruit: "plum"},
            {units: 30, fruit: "plum"}
        ]

        graphPlot = Plot.dot(d, {x: "units", y: "fruit"}).plot();
    })

</script>

{@html graphPlot}
`

No error, no plot. 

Can anyone give me a clue how to get this working?

**Comment by didierfranc** [comment]
@cristianvogel you must append svg element created by Plot to an existing element in the dom to be able to visualize it.

```svelte
<script>
let container;

onMount(() => {
  const plot = Plot.plot(...)
  container.appendChild(plot)
})
</script>

<div bind:this={container} />
```
