### ISSUE TITLE
Support SVG patterns

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#362]
`fill: "url(#hatched)"` should be detected by the color matcher, and treated as a constant rather than a field

reference: https://www.w3.org/TR/SVG11/painting.html#SpecifyingPaint

**Comment by mbostock** [comment]
I think this should work as a regex

```js
/^\s*url\(.*\)\s*$/i
```

**Comment by Fil** [comment]
Example with textures.js https://observablehq.com/@fil/qatar-population-pyramid

**Comment by Fil** [comment]
https://texturemap.org/ seems interesting also

**Comment by Fil** [comment]
Cheysson example https://observablehq.com/@fil/cheysson-plot
