### ISSUE TITLE
marginRight in y facet does not translate label of x

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#375]
Observed when I applying facet y on a dot plot:

When I change marginRight  within the facet y object, 
it updates the dot plot and the x axis  with the ticks (as expected) but does not translate the label of x to the new end of the axis

![image](https://user-images.githubusercontent.com/7562919/117732848-de03f200-b1f0-11eb-84ed-f9f9f3d9f2bf.png)

(see the age label in: https://observablehq.com/d/1d9e39bd4f83a69a)

**Comment by mbostock** [comment]
We tried to fix this in #402 but I think we should take another crack at it.

**Comment by EE2dev** [comment]
👍
