### ISSUE TITLE
Grid styling options

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#385]
It is aesthetically interesting to differentiate the appearance of certain grid lines: 

![image](https://user-images.githubusercontent.com/17407796/117987005-6c37bf80-b33a-11eb-8fff-3a1fe58485ca.png)

Note : this is possible with vega-lite: with the properties `gridOpacity` or `gridDash` for example, to which one can associate a function.

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by Fil** [comment]
Please copy this comment onto #114 and close the issue.
