### ISSUE TITLE
More Facets options

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#386]
I would love to use Plot to reproduce this kind of graph designed with vega-lite. The facets here automatically extend over several lines (facet-wrap concept). It is possible with vega-lite to specify the number of columns and also the width and height of each small graphic rather than the overall composition width and height.

![image](https://user-images.githubusercontent.com/17407796/117987561-e10af980-b33a-11eb-83df-0c728be4ee42.png)
 
This makes it possible to implement a robust and adaptive display:

![image](https://user-images.githubusercontent.com/17407796/117987582-e5371700-b33a-11eb-81b9-fdb5e89447d5.png)
 
Finally, it would be useful to be able to adjust the vertical position of facet labels. The default vertical centring is not ideal in this example, we would like to align the label to the bottom of each facet:
https://observablehq.com/@yurivish/dog-age-distributions 

![image](https://user-images.githubusercontent.com/17407796/117987639-f54ef680-b33a-11eb-85db-95e02d12af74.png)

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by Fil** [comment]
The grid faceting is covered by #277 and #332.

**Comment by mbostock** [comment]
You can also generate separate plots and then use CSS flexbox.

**Comment by mbostock** [comment]
This is now covered by #277 for grid facets and #393 for tick position. Doing some sort of flexbox integration might also be interesting, so we could file a separate issue for that if grid facets are not sufficient.
