### ISSUE TITLE
ruleX/ruleY are somewhat counter-intuitive

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#391]
When I see the following 2 lines together, I frequently have a mental short-circuit because `barY()` evokes (properly) a _vertical_ bar (extending along the Y axis), but `ruleY` actually refers to a _horizontal_ line:
```
Plot.barY(penguins, Plot.groupX({y: "count"}, {x: "species", fill: "sex"})),
Plot.ruleY([0])
```

![image](https://user-images.githubusercontent.com/17407796/117991148-149b5300-b33e-11eb-90ec-6e6fcfc8741a.png)

I would suggest a generic and simplier `Plot.rule`, and also the possibility to specify 0 directly without the array `[0]` being imposed:
`Plot.rule({y:0})`

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by mbostock** [comment]
Thanks for the feedback, but I don’t plan on changing the design here.
