### ISSUE TITLE
Attaching the plot to an existing element

### ISSUE THREAD

**Issue by abdelaliz** [observablehq/plot#396]
Calling the plotting functions (Plot.*) appends a new SVG element to the document. Would it be possible to add an optional argument specifying the existing element to which the plot should be attached ? 

🙏🏼

PS: my js knowledge is still very limited otherwise I would have taken a jab at a PR.

Thank you again for deeply changing the dataviz world

**Comment by Fil** [comment]
Good question. There's need for a specific argument, you can use the DOM element's native .appendChild method:
https://observablehq.com/@fil/attach-plot-dom-396

**Comment by tophtucker** [comment]
Fil beat me to it! If you want to see an example outside of Observable, here's one: https://codepen.io/tophtucker/pen/wvJMNdP

**Comment by abdelaliz** [comment]
@tophtucker @Fil both of you are just awesome. Thanks a million. 🙏🏼🙏🏼
