### ISSUE TITLE
Tooltips (hover to read values).

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#4]
It’d be nice to have a tooltip that shows the value nearest the mouse.

**Comment by kierangilliam** [comment]
Hi! Is there any way to do interaction with Plot? I tried viewing the above links but most of them are dead. Even if it's a hacky solution, I'd like to know if there is some way to do interaction.

**Comment by Fil** [comment]
I have fixed the links; if you play with them, I would be happy to have feedback.

**Comment by rdbcasillas** [comment]
Thanks @Fil for adding super useful interactivity. I am using Plot via npm. Will the tooltip functionality be available from within the package anytime soon?

**Comment by Fil** [comment]
I can't give a specific date but interaction is definitely on the roadmap.

**Comment by tannerlinsley** [comment]
I've been doing some (comparatively basic) voronoi/tooltip functionality in React Charts and would love to offer any help here that I can, if any. I can say from experience in both building and using several different interaction models for my charts that element-based interaction models are usually easier to build and use compared to arbitrary closest-to-point/trie-like ones. In fact, the same great features that make encoding data to cells, bands, shapes, etc such a breeze in plot would make building this "invisible" interaction layer so much easier than what I've been going through lately 😂 .

Put me to work!

**Comment by reubano** [comment]
Reference [metricsgraphics](https://metricsgraphicsjs.org/examples.htm#rollovers)

**Comment by tophtucker** [comment]
Some great reference examples for different chart types by @tannerlinsley: https://codesandbox.io/s/github/tannerlinsley/react-charts/tree/beta/examples/simple?from-embed
