### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by cmoog** [observablehq/plot#401]
Loving this new API 👍, great work all around.

TypeScript declaration files would be a solid UX improvement, making the API surface even more approachable for new comers.

**Comment by Fil** [comment]
I've never done this but a pull-request, even if it's incomplete, would help to get us started.

In particular I don't know how to test the coverage of ts declarations in CI.

A good starting point is probably the README.md API docs, which is the reference (source of truth).

**Comment by kentr** [comment]
> Because Plot uses D3 under the hood, I believe this would be preceded by having up to date and well maintained TS declarations for D3. Currently the [Definitely Typed package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3/index.d.ts) has some pain points that I've run into when using TypeScript with D3, which I imagine would affect the TS declarations for Plot.

@Fil I've been experimenting with type declarations for Plot, so I'd like to know if any of the pain points that you referred to have been resolved with the recent work on the D3 types.

I'm referring to these updates: 

* DefinitelyTyped/DefinitelyTyped#38939
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56119
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54021
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54044
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54101

**Comment by Fil** [comment]
Thank you for the work you are doing on d3 types! I'd be happy to see your experiments with Plot.

**Comment by kentr** [comment]
@Fil Ah, I mixed up my previous reply. I thought that the comment I quoted was from you, but now I see that it was not.

Those D3 updates are the work of some other wonderful people. I can't claim any credit for them. I'll create a PR for the Plot type experiments. They are very new, so it will be more of a starting point as you suggested than an actual request to merge.

**Comment by sgehrman** [comment]
Does Plot work with typescript or not?  I'm getting errors.

**Comment by dgrcode** [comment]
@sgehrman It does work with typescript, although there are no type declarations (as far as I know).

If you want to remove the type errors, what I've done to get it working is to create a file in your project declaring the types. For me that looks like the following:
```ts
```

**Comment by mbostock** [comment]
Fixed in #1320! And more documentation to follow immediately.

**Comment by mbostock** [comment]
Released in [0.6.5](https://github.com/observablehq/plot/releases/tag/v0.6.5).

**Comment by cmoog** [comment]
Wow, I just tried these out and they are incredible! The types, documentation, everything!
