### ISSUE TITLE
Vector field plots : x, y, size, color and orientation channels

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#407]
Wondering wether Plot could, eventually, take advantage of  all the set of x, y, size, color and orientation visual properties such as in:
https://observablehq.com/@d3/vector-field

**Comment by Fil** [comment]
Yes, absolutely. We need a symbol Mark (https://github.com/observablehq/plot/issues/41), and for that mark orientation will make sense as a channel.

Here's a draft that we could build up https://observablehq.com/@fil/plot-symbols

**Comment by ericemc3** [comment]
It's already well advanced, congrats!
