### ISSUE TITLE
Proportional symbol mark?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#41]
Speaking in general, we have several possibilities for proportional symbols:
- svg:circle is concise (and possibly the most cpu-efficient); scale with r/size.
- svg:path + d3.symbol is useful for certain types of scatterplots, but difficult to extend; scale with transform:scale
- svg:text + emoji works if we're careful to center the mark properly; scale with transform:scale

Note that svg:use + defs covers the three cases, and removes the difficulty of having to define complex symbols when we're not happy with the set in d3.symbols.
See https://observablehq.com/@fil/svg-use

So if we want a variant of Plot.dot that allows various symbols, I would try to code it with `<use>`. The range of the symbol scale is a list of objects that would have an id and be added to the defs, or a list of ids—but then how do we pass the objects themselves? The mark could default to `<use href=#square>`. And it would accept an orientation channel!

(discarding svg:polygon which has no advantage that I know of over svg:path.)

**Comment by Fil** [comment]
Linked to https://github.com/observablehq/plot/issues/170

**Comment by Fil** [comment]
See also the preattentive symbols by Heman Robinson https://observablehq.com/@heman/preattentive-symbols-176

**Comment by mbostock** [comment]
Fixed in #652 #649.
