### ISSUE TITLE
Count distinct values in group operation

### ISSUE THREAD

**Issue by kristian-kyvik** [observablehq/plot#412]
Hi,
I was wondering if there was any way I could group and count distinct values. Something I could achieve using the following in vega-lite: 
`vl.y().distinct`

**Comment by Fil** [comment]
You can create your own reducer, for example in https://observablehq.com/@fil/plot-count-distinct we read species in "y" and count the number of distinct values with `(series) => new Set(series).length`.

It could be nice to have a shorthand reducer for this, maybe `{ y: "distinct" }`.

**Comment by Fil** [comment]
see also #420
