### ISSUE TITLE
Broken link in test/README.md

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/plot#418]
This [README FILE](https://github.com/observablehq/plot/blob/main/test/README.md) contains a link to [this URL](https://github.com/observablehq/plot/blob/main/DEVELOPMENT.md#testing) which returns a 404 error. 
<img width="552" alt="Screen Shot 2021-05-26 at 7 27 39 AM" src="https://user-images.githubusercontent.com/1373882/119652268-dc8f1800-bdf3-11eb-8b6d-b805c5d65106.png">

**Comment by Fil** [comment]
it was moved in a6146af5e306609a2896e30cc5f457861a1cf62e
