### ISSUE TITLE
Shorthand for horizontal and vertical links

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#428]
> Plot.link(subdata, {x1: "low", x2: "high", y: "country" }),

could be a shorthand for 
> Plot.link(subdata, {x1: "low", x2: "high", y1: "country", y2: "country" }),

**Comment by mbostock** [comment]
We already have rule for this, no?

**Comment by Fil** [comment]
Ah ha, true. But this remark raises questions:
* the suggestion would remove friction; it seems like a "high-friction" change to mentally switch from a link to a ruleX
* alternatively, should we remove ruleX ruleY in favor of linkX, linkY (or conversely, rename Plot.link as Plot.rule)?
* links are represented as svg paths (possibly with a curve, or a swoopy connector), whereas rules are svg lines.
* should we turn everything into paths?

**Comment by mbostock** [comment]
I’m fine with shorthand for Plot.link. It just doesn’t seem that urgent given you can already do this with rule, and I don’t think it’s much of a burden to change the mark type. I definitely wouldn’t remove rules, and I don’t think it matters much how they’re rendered internally.
