### ISSUE TITLE
style.font property invalid

### ISSUE THREAD

**Issue by josephg** [observablehq/plot#431]
If you apply a font property to a plot:

```
  style: {
    font: '10px sans-serif',
  },
```

It comes out in the SVG like this:

```xml
<svg style="font: sans-serif 10px 10px;" ....>...</svg>
```

This is invalid, and the font is not applied. (It should be "10px sans-serif" not "sans-serif 10px 10px".)

**Comment by Fil** [comment]
Are you generating charts with jsdom, or a browser?

Here's what I see with the following test:
`Plot.plot({ style: { font: "10px sans-serif" } }).getAttribute("style")`

* jsdom: `font: sans-serif 10px 10px;`
* chrome, firefox: `font: 10px sans-serif;`
* safari: `font-style: normal; font-variant-caps: normal; font-weight: normal; font-stretch: normal; font-size: 10px; line-height: normal; font-family: sans-serif;`

Same with `Plot.plot({ style: "font: 10px sans-serif;" }).getAttribute("style")`.

You could define `style: { fontSize: "10px", fontFamily: "sans-serif" }` which works everywhere.

Related https://github.com/observablehq/plot/pull/377

**Comment by josephg** [comment]
Using jsdom. Looks like a jsdom bug I suppose. I’m working around it in the way you suggested.
