### ISSUE TITLE
inset defaults by Plot.bin

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#440]
The docu says:

> Plot.binX changes the defaults for insetLeft and insetRight; Plot.binY changes the defaults for insetTop and insetBottom; Plot.bin changes all four.

If I am not mistaken it seems that it should be:
> Plot.binX changes the default for insetLeft to 1 pixel; Plot.binY changes the default for insetTop to 1 pixel; Plot.bin changes insetLeft and insetTop to 1 pixel each.

**Comment by Fil** [comment]
In https://github.com/observablehq/plot/blob/068f8d8125a910ee1a528c8b299a79c27ca1a9a5/src/transforms/bin.js#L237 the defaults for (insetLeft, insetRight) and for (insetTop, insetBottom) where applicable, become either [1, 0] or [0.5, 0.5]; it's always a total inset of 1px but it might be distributed differently depending on the screen's DPR (https://github.com/observablehq/plot/blob/main/src/style.js#L3).

Reference commit https://github.com/observablehq/plot/pull/246/commits/154757f09c357a75347dd3735767207881720dcc
