### ISSUE TITLE
Crosshairs

### ISSUE THREAD

**Issue by tannerlinsley** [observablehq/plot#443]
Similar to tooltips and an interaction layer, cursors would be 🔥 and IMO, fit pretty naturally into the API by possibly being able to bind arbitrary marks (like `ruleX` and `text`) to your current cursor position. This would probably share a lot of logic with whatever is needed to implement brushing, I would imagine 🤔

**Comment by derekperkins** [comment]
Cursors are very helpful, especially if you could sync them across a faceted chart.

**Comment by mbostock** [comment]
Can you elaborate on what you mean by cursors? Is it like keyboard focus navigation of the plotted data (as opposed to pointer-based)?

**Comment by tannerlinsley** [comment]
What I have in my mind is essentially x+y crosshairs that intersect at either your mouse/touch coords or (if we had an interaction model), the closest datum’s coords. 

But now that you bring up, accessible keyboard-driven crosshairs would be awesome as well.

**Comment by mbostock** [comment]
Okay, retitled the issue to use the term that speaks more clearly to me. Did “pointer-bound marks” refer to something else, or was it to distinguish between crosshairs at the pointer vs. crosshairs that snap to the closest data point?

**Comment by tannerlinsley** [comment]
No, it was mostly my own attempt to speak in "plot" vocabulary. I imagined the crosshairs as "marks" that were bound to the cursor position (or some interaction coordinate).

**Comment by tannerlinsley** [comment]
And who knows, that may be the case for the implementation, but I agree that crosshairs is a bit more descriptive for the concept as a whole.

**Comment by tannerlinsley** [comment]
You bet! I especially love how everything in Plot is "just a mark/transform/etc". This is just one situation where that's really helped me think more clearly about how the API could technically be more flexible/powerful by using the same language/api for everything else.

**Comment by ryoqun** [comment]
sorry for begging. but i want this feature really and waited almost a year. :)

**Comment by Fil** [comment]
Sorry I should have mentioned here that I made a prototype “reticule” plugin (in July 2021) to address this:
https://observablehq.com/@fil/reticule-plot-plugin
