### ISSUE TITLE
What should scale.reverse do?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#448]
After I fixed {reverse} in https://github.com/observablehq/plot/pull/415 I've tried to check all the uses of reverse in scales.

The documentation states that it *reverses the domain*.

As we've seen in #415 this didn't work for threshold and quantile scales (now fixed by reversing the range).

Other questions are:

* make sure that "reversing the domain" never mutates the domain we pass?

* (on color scales) why do we flip the interpolate if the scale has a truthy reverse option (we don't flip the range if we are on an ordinal scale). This results (I think?) in an erroneous mapping in the color legend (though not in the plot itself (??)); see seattle-temperature-band.

* reverse: true on a radius scale r results weird because the sqrt is not flipped.

We need unit tests for all of this.

**Comment by mbostock** [comment]
I believe this was covered by #538.
