### ISSUE TITLE
Arquero shorthand

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#449]
Currently to use Arquero, you say:

```js
Plot.plot({
  marks: [
    Plot.tickX(table.indices(), {y: table.column("age"), x: table.column("percent")})
  ]
})
```

But with a little magic, we could support shorthand for Arquero, treating it like an array of objects:

```js
Plot.plot({
  marks: [
    Plot.tickX(table, {y: "age", x: "percent"})
  ]
})
```

Specifically:

1. If _data_ is an Arquero table, then data is _data_.indices().
2. If _data_ is an Arquero table, then field names are interpreted as _data_.column(_field_).

**Comment by Fil** [comment]
It seems to me that the shorthand notation already works.

However, it's not optimal in the sense that:
1. Plot calls `arrayify` on the table (running the [iterator](https://github.com/uwdata/arquero/pull/81))—using `table.indices()` would avoid that step, but respecting an arquero table as being "arrayified" would work too;
2. Plot instantiates the channels in `valueof` with `Array.from(data, field("fieldname"))`—it could just call `table.column("field")` if it was passed an arquero table.

If we want that optimization, we need a good method to detect an arquero-like table. Maybe when `typeof data.column === "function"`? Then, `arrayify` would pass it unchanged, and `valueof` would call `data.column()`?

**Comment by mbostock** [comment]
Sorry, I should have clarified; you’re right that it already works, but I want it to be faster by being equivalent to the longer one.

FWIW, Inputs.table depends `typeof data.columnNames === "function"`, but I think here we’d maybe want to use `typeof data.indices === "function" && typeof data.column === "function"`, if those are the functions we’d use to implement it:

https://github.com/observablehq/inputs/blob/8fbbcf76f40445346637a764825454e4f7fcc76f/src/table.js#L351

**Comment by Fil** [comment]
We detect an arquero table by its column method. In that case, we accept it as "already arrayified", and use the column accessor to construct any string channel, rather than the field accessor.
Furthermore, we tweak the range so that it uses the indices method (if present), rather than iterate.

With this, I think we're using arquero in an optimal way, while still allowing to define channels with function accessors running on the table iterator.
