### ISSUE TITLE
Gantt chart in Plot

### ISSUE THREAD

**Issue by paweld2** [observablehq/plot#457]
I created a simple gantt chart using plot:
https://observablehq.com/@paweld2/gantt-chart-with-plot

Does it make sense to implement a Plot.gantt(...) mark?

**Comment by Fil** [comment]
It's a great example, thanks for sharing!

For me there is no need for a specific mark in Plot (which focuses on lower level marks such as bars and links), but you could package this into a "gantt chart component", a function that took the necessary options with good defaults, and returned the plot.

**Comment by morozovkirill** [comment]
@paweld2 thank you for your example.

I've enhanced it a little with more suitable connections between dependencies by adding new d3 curve type. If someone can make it more elegant, I would be grateful.

[https://observablehq.com/d/7c5bb00a09585a3e](url)
