### ISSUE TITLE
Is 'title' working on observable?

### ISSUE THREAD

**Issue by dayglo** [observablehq/plot#458]
I cant see to get titles working in any chart.

Even on one of the main observable docs for Plot there's a chart with 'title' channel and it doesn't seem to show up when i hover...

https://observablehq.com/@observablehq/plot-stack 

![image](https://user-images.githubusercontent.com/848198/126343061-d80bf5d8-10bc-4dd8-90ca-cb8c7c941ccb.png)

Am I misunderstanding something?

**Comment by Fil** [comment]
it's working for me
<img width="399" alt="Capture d’écran 2021-07-20 à 16 40 07" src="https://user-images.githubusercontent.com/7001/126343635-1c2e3831-d132-4476-bc7a-bf6df480b98d.png">

maybe a browser issue?

**Comment by tophtucker** [comment]
Note that it's the native browser tooltip, so you have to leave the mouse there for a second or two for it to appear.

**Comment by dayglo** [comment]
You're right, I was being ridiculously impatient. Thanks!

**Comment by tophtucker** [comment]
You bet, it's a good question! @Fil has experimented with a richer flexible instant tooltip (as a plugin) here: https://observablehq.com/@fil/experimental-plot-tooltip-01
