### ISSUE TITLE
Clamped / truncated plot

### ISSUE THREAD

**Issue by dzach** [observablehq/plot#477]
Hi
Is there any complete example for using Plot with plain html/javascript?
In example code from https://observablehq.com/@observablehq/plot plots seem to be clamped to x=100.

With this example:
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script src="https://cdn.jsdelivr.net/npm/d3@6"></script>
	<script src="https://cdn.jsdelivr.net/npm/@observablehq/plot@0.1"></script>
</head>
<body>
<script>

Promise
	.all([d3.csv("athletes.csv")])    // copied in full, exists locally
	.then(doit);

function doit (data) {
	var athletes = data[0];
	var plt = Plot.rect(athletes,Plot.bin({fillOpacity: "count"}, {x: "weight", y: "height", fill: "sex"})).plot();
	document.body.appendChild(plt);
}
</script>
</body>
</html>
```
I'm getting this plot:

![](https://raw.githubusercontent.com/dzach/gitted/master/.github/images/Plot_issue_heatmap.png)
Curiously, values seem to be clamped at x=100, but some appear close to x=0.

Using Firefox 90.0.2 (64-bit) on Kubuntu 18.04

The plots themselves look fine in https://observablehq.com/@observablehq/plot, and work without problems, other than the one mentioned here, when served locally like the html file above, or when the files are opened directly with the browser.

Searched for long, but didn't find anything similar.

**Comment by mbostock** [comment]
Try `d3.csv("athletes.csv", d3.autoType)`.

**Comment by dzach** [comment]
Ah, that did it. Now I can enjoy the rest.
Thanks you!
