### ISSUE TITLE
Rank and/or quantile transform

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#483]
It’d nice to have a map transform that converts quantitative values into ranks (1, 2, 3, …) or the equivalent *p*-quantile in [0,1]. This would be an alternative to the quantile scale.

**Comment by Fil** [comment]
Should this be part of d3-array?
https://observablehq.com/d/c1eb24e6680046d7

**Comment by mbostock** [comment]
I figured we would build it and see if it’s useful before we decide.

One nuance on implementation: if the same value is repeated, then they should have the same rank, and ranks should be skipped. So for example [3, 1, 3, 4, 2, 0] is mapped to [4, 2, 4, 6, 3, 1] (assuming 1-based ranking). Also I think all non-comparable values would need to be replaced with NaN (or undefined?).

**Comment by mbostock** [comment]
Also if we use d3.sort we will need to fix https://github.com/d3/d3-array/issues/217 such that all undefined values (null, NaN, and undefined) are moved to the end.

**Comment by Fil** [comment]
I've added a "same value" test (with a test on `! a <= b` to make sure two Date objects representing the same date have the same rank).

I'm not sold on starting at 1. I see the cosmetic appeal, but it makes this slightly more difficult to, for example, use the rank to lookup a value in another array `"🥇🥈🥉"[rank]`.

**Comment by mbostock** [comment]
I’m not convinced we want 1-based ranking either. That was just my first thought… we can start with 0-based if you like.

**Comment by Fil** [comment]
The inherent difficulty of writing this "simple" function makes me think it should be in d3-array. And it's already nice to use in Plot:

<img width="376" alt="Capture d’écran 2021-08-04 à 18 37 52" src="https://user-images.githubusercontent.com/7001/128219998-bbc69b93-6d79-40fe-a5c5-945f6d64dd5e.png">

**Comment by Fil** [comment]
pull-request for d3.rank https://github.com/d3/d3-array/pull/228

**Comment by mbostock** [comment]
Added in #570.
