### ISSUE TITLE
stroke reduce for lines

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#503]
in applyGroupedChannelStyles we reduce the stroke (or fill) with the "first" reducer: `([i]) => S[i]`

what syntax could we use to make this reduction explicit and configurable? By analogy with Plot.group we might have:

> Plot.line(data, {stroke: "median"}, {stroke: "value", x: …})

**Comment by mbostock** [comment]
Perhaps akin to what we do for Plot.bin’s per-dimension options, using [maybeValue](https://github.com/observablehq/plot/blob/cd19abab613474824c44e87f1839fb46aa3e39b3/src/mark.js#L246-L251)?

```js
Plot.line(data, {stroke: {value: "value", reduce: "median"}, x: …})
```

**Comment by Fil** [comment]
Related: https://github.com/observablehq/plot/issues/617

**Comment by mbostock** [comment]
Folding into #724.
