### ISSUE TITLE
Symmetric diverging domains centered around the pivot

### ISSUE THREAD

**Issue by zanarmstrong** [observablehq/plot#504]
Please see the example [here](https://observablehq.com/@zanarmstrong/pivot0-expected-equaldarknessfromcenter). 

When I set a diverging color scheme w/ pivot 0, I expect it to look like this. With +4 and -4 to be similarly dark (one a light green and the other a light pink). 

![Screen Shot 2021-08-17 at 2 10 09 PM](https://user-images.githubusercontent.com/7397271/129801060-0ebdeb7f-d9e6-47c8-acbf-3a8dd36256d5.png)

Instead I saw this: 

![Screen Shot 2021-08-17 at 2 11 10 PM](https://user-images.githubusercontent.com/7397271/129801179-9dae2a63-43d5-4054-b12f-c55ebaffe60f.png)

My hunch is that it's calculating the ramp from the pivot to the min and max, leading to a different ramp if the min is closer to the pivot than the max.

**Comment by mbostock** [comment]
Yep, this is the documented behavior:

> For most quantitative scales, the default domain is the [min, max] of all values associated with the scale.

And you can confirm with the code here:

https://github.com/observablehq/plot/blob/cd19abab613474824c44e87f1839fb46aa3e39b3/src/scales/quantitative.js#L143

https://github.com/observablehq/plot/blob/cd19abab613474824c44e87f1839fb46aa3e39b3/src/scales/quantitative.js#L188-L193

We could certainly change the default domain for diverging scales, but I think you’d want an option for whether the diverging scale should be symmetric around the pivot or not. . Maybe *symmetric* = true? Or *center* = true?

The other thing to consider is that if we use a default domain of [pivot-delta, pivot+delta] where delta = max(|value - pivot|), then the color legend will show values that don’t exist in the chart, like this:

<img width="583" alt="Screen Shot 2021-08-17 at 2 25 08 PM" src="https://user-images.githubusercontent.com/230541/129802737-7340b586-b65a-42f5-bebb-3bd50980b080.png">

So… it might be better to somehow truncate the interpolator rather than extending the domain to be centered around the pivot. I think that would be possible, too, which would get you what you wanted.

I’m going to retitle this to describe a feature request, but please let me know if you have thoughts on how we’d support this use case.

**Comment by zanarmstrong** [comment]
yes - my expectation is that if type is diverging and a pivot point is set, then the domain would no longer be [min,max] but would become: _[pivot-delta, pivot+delta] where delta = max(|value - pivot|)_. Thanks for making the calculation concrete. 

I feel like there is a pretty strong expectation that a diverging color scheme is symmetric (unless made non-symmetric for a very specific reason). I'm actually struggling to come up with a reason for it not to be symmetric. Even if I wanted to deal with an extreme outlier, then I would want to clamp the delta at some smaller value, while maintaining the symmetric expectation. 

It's funny... even though technically the domain would no longer be [min,max], it conceptually feels like it's achieving the same goal of the max distance from the pivot defining the domain, along with the constraint that the colors are symmetric from the center. 

In Python's [Matplotlib](https://matplotlib.org/stable/tutorials/colors/colormaps.html) and Seaborn: 
> _"For the Diverging maps, we want to have monotonically increasing 𝐿∗ values up to a maximum, which should be close to 𝐿∗=100, followed by monotonically decreasing 𝐿∗ values. We are looking for approximately equal minimum 𝐿∗ values at opposite ends of the colormap."_ 

Example in colab [here](https://colab.research.google.com/drive/1Lm8SuwQThNV2ZU7yi2HyYvXeAT_bBo8T#scrollTo=kiDL9VxYllyQ).
![Screen Shot 2021-08-17 at 5 14 21 PM](https://user-images.githubusercontent.com/7397271/129816753-16556d8b-6248-4b98-8353-9f13817b6495.png)

I don't actually see a straightforward way to make it non-symmetric. 

Diverging color schemes seem a little more awkward / less supported in ggplot2. [scale_fill_gradient2](https://ggplot2-book.org/scale-colour.html) let's you define a high/low/mid color and midpoint value. It also [looks symmetric](https://eliocamp.github.io/metR/reference/scale_divergent.html)even when the data is not, but I didn't test it yet.

And, to show that this isn't just about matplotlib/python & R, [here](https://www.storytellingwithdata.com/blog/2020/5/6/picking-the-right-colors) is Storytelling with Data's description of diverging: 

> _A diverging color ramp is like two sequential ramps facing opposite directions, stitched together tail-to-tail at your data’s natural midpoint. If your data includes both negative and positive numbers, for instance, then you would choose a dichromatic (two-hued) palette, ideally with your key color (for positive) and its complementary color (for negative), and use a neutral gray color for the midpoint (where the tails are stitched together)._

> _It’s important to note that the diverging color ramp’s midpoint is not the midpoint of your data range, but rather at the meaningful midpoint that is the threshold between positive and negative. (A data range from -10 to 90 should not have a color ramp that uses 40 as its midpoint. The color ramp, in fact, should run from -90 to 90, with a midpoint of 0.)_

In each case, I think the assumption that it's symmetric is pretty strong. 

-----
_a few additional notes_

_the color legend will show values that don’t exist in the chart_ --> I actually don't have a problem with that; I think it can be nice to see the full extent of the color space (but this might be just me). And, at the same time, it's not clear to me why that has to be true? Why is the legend's domain being defined by the color domain rather than the data's domain? 

I'm not sure what you mean by truncate the interpolator. Do you mean clamp at the min of the distances? Instead of extend to the max?

**Comment by zanarmstrong** [comment]
One more: How is this handled in Data Wrapper? 

It was pretty cool. You first get a continuous color palette. 

![Screen Shot 2021-08-17 at 6 18 13 PM](https://user-images.githubusercontent.com/7397271/129821191-a8f2f3ca-d2cb-4db4-a7bf-8b1a2d2f19a6.png)

If you choose a diverging in the dropdown, it centers as expected halfway between min/max. 

![Screen Shot 2021-08-17 at 6 16 08 PM](https://user-images.githubusercontent.com/7397271/129821248-d322370e-862a-42eb-9c06-c7b7f59d5c27.png)

But, there is a custom range selector in the UI with min / center / max. So the interface encourages you to make a decision about what those should be. 

![Screen Shot 2021-08-17 at 6 16 18 PM](https://user-images.githubusercontent.com/7397271/129821288-58e2e736-a724-485a-80ca-be4fbd061676.png)

Which is actually really nice because often "max" isn't the ideal either. It might make more sense to choose to clamp at 5% or 10% or 15%, rather than have the color determined by whatever the most extreme value happens to be. For example, if we consider +5% a pretty big change, then perhaps setting a 5/-5 extent makes more sense. 

![Screen Shot 2021-08-17 at 6 22 26 PM](https://user-images.githubusercontent.com/7397271/129821510-7263ec61-a616-4bdb-a1b4-9528483e453f.png)


----
ps - thanks for the much better title on this issue :)
