### ISSUE TITLE
Generate tspans to pass to a text mark?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#506]
It’d be nice if instead of the *text* channel of strings, you could use the *children* channel and generate SVG tspan elements using htl.svg. Then you can more easily apply custom layout to text, for example for multiple lines. #327

**Comment by mbostock** [comment]
#313 is far more convenient for multiline text, but this would be nice if you want to apply some custom formatting to the text, say for bold or italics, or to apply hyperlinks to some of the text.

**Comment by yurivish** [comment]
Would it make sense to support something like this for tick labels too, for when you really want to customize the contents of individual ticks? E.g. making a multi-line tick with one of the lines in bold.

**Comment by mbostock** [comment]
@yurivish See #460.

**Comment by mbostock** [comment]
Going to start with multiline text in #677. Will reopen this issue if there is sufficient demand.
