### ISSUE TITLE
Axis label helper?

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#510]
If I make a plot with custom axis labels I want them to match the style of the built-in labels, and often wind up searching for unicode arrows to copy-and-paste.

Might it make sense for Plot to provide helper functions to make it a little easier to stay consistent with the default convention?

```javascript
Plot.formatAxisX = text => text + ' →'
Plot.formatAxisY = text => '↑ ' + text
````

**Comment by mbostock** [comment]
I think this would make the most sense as a “labelArrow” option which if set to true will add an arrow as appropriate to the axis label depending on the orientation of the axis. This could also be used to disable the arrow if you don’t like it, and to explicitly enable the arrow on ordinal scales if desired. The default value would be “auto” for today’s behavior.
