### ISSUE TITLE
For text, allow x and y to be specified as constant numbers

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#523]
For manual labels, it’d be nice if you could specify *x* and *y* as constant numbers. Currently they can either be a channel or null; in the latter case the labels are placed in the center of the chart.

Related, it might also be nice to have an *anchor* option which allows the text to be positioned somewhere else relative to the surrounding frame; this would eliminate the need to hard-code *dx* and *dy* (e.g., in the [geofacet example](https://observablehq.com/@data-workflows/geofacet)). The *anchor* option could accept values such as *top*, *top-left*, *top-right*, *right*, etc.

**Comment by Fil** [comment]
Related https://github.com/observablehq/plot/issues/153

**Comment by mbostock** [comment]
Related multi-line text #677 #313 #327. Specifically #677 introduces a *lineAnchor* property which controls vertical position of lines relative to the anchor point.

**Comment by mbostock** [comment]
I don’t think we want to introduce this convention of literal positioning, and especially that we’d want *x* and *y* to behave differently for text marks. But I could see a *frameAnchor* option that controls the position for otherwise position-less marks; it would default to middle for the current behavior.
