### ISSUE TITLE
Optional outputs argument for bin and group transforms in 0.2.0

### ISSUE THREAD

**Issue by juba** [observablehq/plot#525]
First, many thanks for this incredible library, and please forgive me if this issue is due to my lack of JavaScript knowledge rather than a problem in Plot.

In the 0.2.0 changelog it is said that : 

> The outputs argument to the bin and group transforms is now optional; it defaults to the count reducer for y, x and fill for Plot.binX, Plot.binY, and Plot.bin respectively, and the same for the group transforms.

However if I try something like : 

```js
Plot.rectY(data, Plot.binX({ x: "bill_depth" })).plot()
```
I get an `invalid reduce` error, as `{x: "bill_depth"}` is seen as the `outputs` argument, not as `options`. The only way I can make it work to use the default `outputs` value is with : 

```js
Plot.rectY(data, Plot.binX(undefined, { x: "bill_depth" })).plot()
```

I've tried to fork and change the code to make this work, but I can't find a way as both `options` and `outputs` are optional, like in the `moby-dick-letter-frequency` test example :

```js
Plot.barY(letters, Plot.groupX({y: "count"}))
```

Is using `undefined` to get default output values the intended behavior, or am I missing another way to call these transforms ?

Thanks !

**Comment by mbostock** [comment]
> Is using undefined to get default output values the intended behavior, or am I missing another way to call these transforms ?

Yes, that’s the intended behavior. In certain cases you can also omit both arguments.
