### ISSUE TITLE
ignore infinite values when setting a scale domain?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#528]
I was doing an error plot and because one of the values was infinite (log(0)), the *y* scale collapsed. it would be more useful in that case to ignore the infinite value (as NaN), and report the missing / invalid point when we have some way of logging warnings.

**Comment by husain3012** [comment]
I would like to work in this

**Comment by mbostock** [comment]
If we want to do this, it should probably happen when we coerce numbers (#532):

https://github.com/observablehq/plot/blob/916d04bbef6d684f0dcf53cd954d6a3165b269bd/src/scales.js#L189-L194

For example, we could check that the value is finite:

```js
function coerceNumber(x) {
  return x == null || !isFinite(x = +x) ? NaN : x;
}
```

However, I’m not sure that this is a good universal behavior… it feels convenient to treat infinite values as undefined to make sure that the chart renders correctly, but the infinite values _are_ (technically) defined so it might be preferable to throw an error or show a warning instead. #536

**Comment by Fil** [comment]
The line is blurry: a mathematician would say that 1/0 and log(0) are undefined, but JavaScript wants them Infinite.

In my use case, the data was the magnitude of a computational error over 100 tests. When the error for one of the 100+ tests fell to 0 (a situation which I hadn't anticipated), the _y_ axis crashed, which was not helpful.

This patch works [very well](https://observablehq.com/d/f3b6742d2557e92c); in this notebook, I tried several alternatives… in each case it means you have to understand why the chart collapsed, then think about a solution.

(I'd also want a warning, of course.)

**Comment by Fil** [comment]
This proposal is also consistent with #279.

In other words, this chart:
```
Plot.plot({ x: { type: "linear" }, marks: [
  Plot.dotX([0, 0.1, 1, 2, 10], Plot.map({x: d => d.map(d => Math.log2(d))}, {x: d => d}))
]});
```

should not fail, but behave as this one (which is our log-degenerate.js test case), only with log(d) on the *x* axis:
```
Plot.plot({ x: { type: "log" }, marks: [ Plot.dotX([0, 0.1, 1, 2, 10]) ] });
```
