### ISSUE TITLE
Instead of filtering oppositely-signed values for log scales, require an explicit sign

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#534]
The current log scale detects automatically whether the data is positive or negative; for mixed data, the first signed valid determines whether the scale as a whole is positive or negative. What if instead, the scale threw an error, and required you to set the scale type to “logp” for positive values or “logn” for negative values (or switch to symlog or sqrt if you want both).

**Comment by mbostock** [comment]
(Or maybe a sign: -1 option.)

**Comment by mbostock** [comment]
This could also be required if any zero values are detected. I.e., log scales will error by default but will ignore zeroes and opposite-signed values if you specify a *sign* option.

**Comment by Fil** [comment]
The example I have in mind for this particular scenario is a chart showing the elevation of a piece of land on a map. The user could try a log scale for some reason (aesthetic?), but then when the focus of the map starts to include values below zero (say, a bit of the ocean), if a negative value creeps in as the first valid point, the whole chart might get inverted…

This seems highly unpredictable, and I think we should reconsider the automatic sign detection (#278). Having "log" scales only work for positive values would be more resilient, and probably more generally understandable. (Users who want a log scale on negative values could do it via an explicit scale transform, so I don't think we'd need to add a `sign: -1` option?).

If the data has negative values, #536 might mention that *n values have been ignored*.

For zero-log, also see #528.

**Comment by mbostock** [comment]
I feel the user should make two separate decisions here. The first is whether the log scale’s sign should be positive or negative; this currently happens automatically based on the first defined (and nonzero) value. The second is what to do with opposite-signed and zero values; these are currently ignored (treated as undefined).

So, we could retain the current behavior where the sign is determined automatically based on the data, but instead of ignoring opposite-signed and zero values, we could throw an error. If the user wants to ignore these values, they could set `sign: 1` to ignore nonpositive values, or `sign: -1` to ignore nonnegative values. Or equivalently they could use `type: "logp"`  or `type: "logn"` if we prefer that to a _sign_ option.

**Comment by yurivish** [comment]
There's also `logp` in the sense of `log(1 + x)` ([Math.log1p](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log1p)), which is sometimes used to log-scale data that includes zero values and could perhaps be a scale type (simulating it with a scale transform doesn't work because the axis labels become off-by-one and can't be compensated for with `tickFormat` since tick values would no longer be nice). I'm not sure how this fits in, but perhaps it could be another log scale type to allow the option of a log scale that includes zeroes.

**Comment by mbostock** [comment]
I’m not sure how to proceed here. We could add a *sign* option to make it more explicit whether you want a negative or positive domain, but you can also do that by setting the domain explicitly. I don’t think we want to throw an error; in general Plot tries to ignore erroneous input and make a best effort attempt at display. So that leaves generating a warning when invalid input values are ignored, which is already covered by #493 and #536.
