### ISSUE TITLE
Limit the maximum default range for r scales?

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#537]
Currently Plot.dot() can create very large circles with the default r scale. E.g. see here: https://observablehq.com/d/ac556fbbda8d6cbe
Why not set the default range to be at most [...,20]?

**Comment by Fil** [comment]
Per the documentation:

> for radius, the default range is designed to produce dots of “reasonable” size assuming a sqrt scale type for accurate area representation: zero maps to zero, the first quartile maps to a radius of three pixels, and other values are extrapolated. This convention for radius ensures that if the scale’s data values are all equal, dots have the default constant radius of three pixels, while if the data varies, dots will tend to be larger.

Of course whether this heuristic works well depends on the distribution of values in the radius channel; in the case of countries’ areas, it does not work well. You have:

d3.quantile(data.map(d => d.area), .25) == 2830

the ratio of the largest country’s area to this number is 5786 (which is 76^2); so the largest circle is going to have a radius of 76 * 3 px.

**Comment by EE2dev** [comment]
Thanks @Fil for the in depth explaination of the heuristics!

I understand that the heuristics works as designed. And that there are always cases when the default range is not optimal. I just wonder if there is any reason to allow the default range r to exceed a certain threshold.
