### ISSUE TITLE
threshold scales probably need an extent option

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#542]
To create a meaningful legend for a threshold scale, we need not only the thresholds (where the color changes), but also need to know where to start and end. In particular when the thresholds are derived from quantiles.

Suggestion would be to add **extent** as an array `[lo, hi]` or a function `(data, min, max) => [lo, hi]`.

We might also want to respect the **nice** option when computing these bounds.

**Comment by mbostock** [comment]
I don’t think the extent is necessary; we can use the same approach as the [D3 color legend](https://observablehq.com/@d3/color-legend) for threshold scales.
