### ISSUE TITLE
Plot.text should default to tabular figures / numbers

### ISSUE THREAD

**Issue by visnup** [observablehq/plot#577]
If you plot some numbers as text with a `text-anchor: end`, it'd be nice if the numbers were [tabular and aligned horizontally](https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures) by default.

For example:

```javascript
Plot.plot({
  marks: [
    Plot.ruleX([0], { stroke: 'lightgray' }),
    Plot.text(
      [
        ["a", 3.4],
        ["b", 2.1],
        ["c", 12.8]
      ],
      { y: "0", text: "1", textAnchor: "end", dx: 7.5 }
    )
  ],
  width: 100
})
```

Produces:
![untitled](https://user-images.githubusercontent.com/10444/137234852-85782242-d45f-4abe-a2a2-83db06cd1fb2.png)

Where the decimal is not quite aligned due to the thinner `1` in `2.1`.

I'm pretty sure there are some arcane CSS styles that may fix this.

**Comment by tophtucker** [comment]
imo even regardless of textAnchor!
