### ISSUE TITLE
Numeric intervals for rect

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#590]
Currently rect expects a D3 time interval for the _interval_ option, but I think it’d be pretty easy to also accept a number for that option. It’d be useful like for a heatmap where you don’t want (or need) the bin transform, e.g.

https://observablehq.com/@credmond/the-gradient/2

**Comment by Fil** [comment]
> If the interval is specified as a number n, x1 and x2 are taken as the two consecutive multiples of n that bracket x.

is it something else?

**Comment by mbostock** [comment]
Oops, we already did that! I just forgot. 😬
