### ISSUE TITLE
Plot.text, when rotated, interprets dx and dy differently from other marks

### ISSUE THREAD

**Issue by CobusT** [observablehq/plot#591]
When you rotate Plot.text, the `x` and `y` attributes is correctly interpreted as horizontal and vertical positions, but the `dx` and `dy` seems to be switched.

```
Plot.plot({
  x: {domain: [-10,10], grid:true},
  y: {domain: [-10,10], grid:true},
  marks: [
    Plot.frame(),
    Plot.text([1], { x: 5, y: 0, dx: -50, dy: 0, rotate: -90, text: ["test"]}),
    Plot.dot([1], { x: 5, y: 0, dx: -50, dy: 0})
  ]
})
```

I would expect the dot and the text to be in the same position.
<img width="852" alt="Screen Shot 2021-11-14 at 6 42 54 PM" src="https://user-images.githubusercontent.com/10869236/141714001-55e55d14-9fc2-4e1e-a7a3-3c7c863d1dde.png">

**Comment by mbostock** [comment]
This is the expected/intended behavior.

**Comment by CobusT** [comment]
Interesting. Fair enough, but it felt strange that x and y are not affected by the rotation, but dx and dy are...
But if that is intentional and/or intuitive to others, I will adapt :-)

**Comment by Fil** [comment]
It's not intuitive, but it's the SVG spec. Very useful when your text follows a text-path and needs to be a little above the path:
<img width="511" alt="Capture d’écran 2021-11-15 à 21 40 01" src="https://user-images.githubusercontent.com/7001/141850738-2b705355-1a3a-4087-9ba5-27716db6f584.png">
