### ISSUE TITLE
Mark callback?

### ISSUE THREAD

**Issue by j-f1** [observablehq/plot#592]
When creating a plot using Observable Plot, I found that using the APIs was a good experience; however, it is essentially impossible to do anything outside of them. It would be nice to have an ”escape hatch” (a `customize` option callback that takes either a d3 selection or just an HTML node?) in various places to allow for arbitrary customization.

proposal:

```js
Plot.dot(athletes, {
  x: "weight",
  y: "height",
  stroke: "sex",
  customize: el => el.on('mouseenter', (e, d) => alert(d.sport))
}).plot({
  x: {
    customize: el => el.selectAll('.tick').remove()
  },
})
```

**Comment by Fil** [comment]
Related: https://github.com/observablehq/plot/issues/501#issuecomment-901442755

**Comment by mbostock** [comment]
This description feels too general to be actionable, so I’m going to close, but please continue to share your ideas and perhaps we can rally around something more concrete that we can work on. I also want to note that Plot already has a significant “escape hatch” in the sense that you can provide your own Mark implementation by implementing _mark_.render or simply by passing a render function in the marks array. This is described here:

https://github.com/observablehq/plot/blob/main/CHANGELOG.md#marks
