### ISSUE TITLE
barY: axis isn't responsive: could it be (eg: by skipping values?)

### ISSUE THREAD

**Issue by shiraleeana** [observablehq/plot#595]
Hello 👋 

I've been doing some basic things with `barY` – and would love to only show every nth tick mark, but unlike `line` and `area`, barY tick marks always just bunch up:

![Screen Shot 2021-11-26 at 4 05 49 pm](https://user-images.githubusercontent.com/316112/143529932-4181a827-a4e5-4ee3-a6f8-0d01909f7c8a.png)

Versus a quick change to line:
![Screen Shot 2021-11-26 at 4 06 04 pm](https://user-images.githubusercontent.com/316112/143529936-6e39a786-5601-4967-b358-0d5fc6b08c7c.png)

I can understand why dropping tick values on a column graph is a no no – but it seems that simply scaling a barY chart may not always work (as it gets too small).

Was thinking someting like this:
<img width="222" alt="Screen Shot 2021-11-26 at 4 09 18 pm" src="https://user-images.githubusercontent.com/316112/143530009-8c63b990-54cf-4754-b20b-6577fbbcdee3.png">

(Bonus question – is it possible to change tick mark label colours?)

**Comment by mbostock** [comment]
When you use barY, you’re implying that the x-axis is ordinal, and therefore the regularity (period, e.g. annual) of the bars cannot be inferred. For a temporal axis you should be using rectY instead, together with the interval transform as shown here:

https://observablehq.com/@observablehq/plot-interval

(That said, you can suppress certain ticks by specifying the tick values explicitly as the _ticks_ scale option.)

We don’t currently have a way to change the tick label color, though as the tick labels default to currentColor, you can change the color of the entire chart by setting the CSS color property (such as by using the top-level _style_ option). If you just want to change the tick label colors, you’ll need to select the tick elements generated by Plot and apply a style manually.

**Comment by shiraleeana** [comment]
Fabulous, thank you, Mike.
