### ISSUE TITLE
Custom styles for axis and ticks.

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#6]
What if we want to change the color and font of axes?

**Comment by morozovkirill** [comment]
It would be nice to set different font size for ticks on different axes. Now it's impossible even through class name selector. May be name the styles like "tickX"/"tickY"?

**Comment by Fil** [comment]
Related: #126 ?

**Comment by irenedelatorre** [comment]
It would be nice to add a class in the axis group (axis-x, axis-y). This is something that d3.js does, and it lets you style the axis as the user wants / needs. Plot already includes this information in the aria label.
