### ISSUE TITLE
Only apply font-variant: tabular-nums to axis ticks

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#601]
We’re currently applying it to everything, which doesn’t look great on axis labels and text marks that aren’t strictly numbers. I think it’d probably be a better default to only apply to axis ticks (which are typically numeric or dates, both of which would benefit from tabular numerals) and perhaps selectively text marks where the _text_ channel is formatted numbers (and perhaps dates). It doesn’t look good in swatches, either.

**Comment by Fil** [comment]
Related: #253

**Comment by mbostock** [comment]
Did we fix this for legends, too?

**Comment by Fil** [comment]
hmmm, no… give me a minute

**Comment by mbostock** [comment]
I’ve done half of it :)
