### ISSUE TITLE
dx, dy not supported for Plot.image

### ISSUE THREAD

**Issue by floledermann** [observablehq/plot#653]
The [documentation](https://github.com/observablehq/plot/blob/main/README.md#image) says that all the standard mark options should be supported for Plot.image, however, setting dx or dy to a constant value on an image mark has no effect for me.

Testcase, including example using Plot.dot where dx / dy works as expected, at 
https://observablehq.com/@floledermann/plot-image-testcase

**Comment by mbostock** [comment]
This was fixed in #629 and has been merged to main and will be released soon.
