### ISSUE TITLE
Expose values from proportion and proportion-facet reducers

### ISSUE THREAD

**Issue by mwhitaker** [observablehq/plot#655]
As discussed on [Observable Talk](https://talk.observablehq.com/t/getting-values-for-proportion-reducers-in-plot/6040) I was looking for a way to access the values produced by either the **proportion** or **proportion-facet** reducer so that I could use those values in the **title** property of a binned plot.

@Fil suggested a [solution](https://observablehq.com/d/c1ac45ab25a21e9f) that uses the internal `scope` argument and requested that I submit this as an issue.

**Comment by mbostock** [comment]
I see two things to do here:

1. Document the _scope_ property for reducers.
2. Consider a hook that transforms the output of a reducer.

I see the second thing as related to #643, where the *text* and *title* channels have an implicit localization format applied after computation; but, it’d be nice if there were a way to control that behavior more explicitly without having to re-implement the reducer. I’m sure it’s possible to implement as another (perhaps custom) transform, but having a built-in hook would likely be more convenient.
