### ISSUE TITLE
Legend and caption don't honour a plot's style option

### ISSUE THREAD

**Issue by flother** [observablehq/plot#662]
Thanks for releasing Plot into the wild, it's quite spectacular software. Yesterday evening I created a plot with code like this:

```js
Plot.plot({
  caption: "Blah",
  color: {
    legend: true,
  },
  style: {
    fontFamily: "Georgia",
    fontSize: "14px",
    color: "#666",
  },
  ...
});
```

I expected the generated colour legend to inherit the plot's style, but it doesn't. I've created a [minimal example on observablehq.com](https://observablehq.com/@flother/uk-iceland-covid) to show that the legend actually uses  the `system-ui` font at 10px.  The generated HTML there looks like this (I've simplified it a bit to make the problem more obvious):

```html
<figure>
  <div class="plot-3bd8c18ff5d768">
    <style>
      .plot-3bd8c18ff5d768 {
        font-family: system-ui, sans-serif;
        font-size: 10px;
      }
    </style>
    <span>Legend item 1</span>
    <span>Legend item 2</span>
  </div>
  <svg
      class="plot-8f2a464d421128"
      font-family="system-ui, sans-serif"
      font-size="10"
      style="font-family: Georgia; font-size: 14px; color: rgb(102, 102, 102);">
    <!-- ... -->
  </svg>
  <figcaption><span>Blah</span></figcaption>
</figure>
```

Because the plot's style is only applied to the `svg` element, the legend's `div` element doesn't take on my custom font, font size, and colour. But the default style for Plot _is_ applied (`font-family: system-ui, sans-serif; font-size: 10px;`). The same is true for the caption, except it's left unstyled and so it will at least inherit the page's default style.

When a legend is generated by a plot I would expect it to inherit the plot's custom style. Here, I would want my font family/size/colour to be picked up by the legend.

**Comment by Fil** [comment]
You can style the caption directly with
~~~
caption: html`<p style="font-family: Georgia, font-size: 12px">Source: <a href="https://covid.ourworldindata.org/">Our World in Data</a>`,
~~~

but this doesn't solve the legend.

There are two ways to solve this: 1. would be to have the styles apply to the figure (but we might want different stylings for the legend, the caption, and the chart); 2. would be a method to pass styles to the legend (but in some cases, like the font-family, it means we'd have to repeat ourselves in several places).

Note: this issue is also partially described in https://github.com/observablehq/plot/issues/397

**Comment by flother** [comment]
I've had some success styling the legend by separating it out from the chart, giving it a custom class name, and using a more specific selector to style it.

```js
const chart = Plot.plot({ ... });
const legend = chart.legend("color", { className: "legend" });
const el = document.getElementById("chart");

el.appendChild(legend);
el.appendChild(chart);
```

```css
div.legend {
  font-family: Georgia; font-size: 12px
}
```

That works well — especially outside of the Observable environment — but I'd prefer to be able to keep the code all in one call to `Plot.plot()`. As you mention, though, there's no obvious compromise-free solution to this.

**Comment by mbostock** [comment]
I think this is sufficiently covered by #397, so closing this as duplicate. I’m not sure yet what the answer is here. It’s tricky to have too many options and also think about interactions with external stylesheets.
