### ISSUE TITLE
Is it possible to create Sankey diagram with this library?

### ISSUE THREAD

**Issue by datlife** [observablehq/plot#698]
Hello,

Thank you for making this library. I am amazed how easy it is to create visualization in this video [1] by Anjana, I am curious if it is possible to generate Sankey Diagram on this library yet? I understand it is possible with D3, but not sure about this library.

Particularly, I am hoping to generate something similar like this [2].

[1] https://www.youtube.com/watch?v=bXneu8fY5ew&t=1017s
[2] https://bl.ocks.org/emeeks/e9d64d27f286e61493c9

**Comment by Fil** [comment]
Thanks for your interest. But no, we haven't started tackling graphs / networks / hierarchies (issue https://github.com/observablehq/plot/issues/136).
