### ISSUE TITLE
Module parse failed: Unexpected token (plot.js 100:45)

### ISSUE THREAD

**Issue by tesla-cat** [observablehq/plot#742]
- using `react-scripts`
```
./node_modules/@observablehq/plot/src/plot.js 100:45
Module parse failed: Unexpected token (100:45)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|   for (const mark of marks) {
>     const channels = markChannels.get(mark) ?? [];
|     const values = applyScales(channels, scales);
|     const index = filter(markIndex.get(mark), channels, values);

```

**Comment by mbostock** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Comment by quanphan2906** [comment]
Same problem in vue 3:
```
Uncaught Error: Module parse failed: Unexpected token (100:45)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   for (const mark of marks) {
>     const channels = markChannels.get(mark) ?? [];
|     const values = applyScales(channels, scales);
|     let index = markIndex.get(mark);
```
When I use ```??``` directly in my code, there is no error. Maybe a problem within observable plot?

**Comment by mbostock** [comment]
> Maybe a problem within observable plot?

No, this is a problem with your tool chain (webpack, based on the error message you quoted). If you are transpiling Observable Plot you’ll need a transpiler that supports the nullish coalescing operator (`??`).

**Comment by quanphan2906** [comment]
> > Maybe a problem within observable plot?
> 
> No, this is a problem with your tool chain (webpack, based on the error message you quoted). If you are transpiling Observable Plot you’ll need a transpiler that supports the nullish coalescing operator (`??`).

Yes, this is correct. Vue 3 project created with ```vue create app``` need to be configured to transpile Observable Plot. Refer to this SO thread for more information: https://stackoverflow.com/questions/58386898/vue-cli-3-app-not-loading-in-ie-with-some-npm-packages.

Thank you @mbostock

**Comment by sharmun** [comment]
thanks
