### ISSUE TITLE
Clarify format for Plot.plot() style options

### ISSUE THREAD

**Issue by ropeladder** [observablehq/plot#767]
It's not obvious that the `Plot.plot({style: ... })` options such as `width` or `margin` must be specified as e.g. `"20px"` instead of `"20"` or simply `20`. Adding an example and specifying the required format would help clarify.

**Comment by mbostock** [comment]
Automatically promoting `20` to `"20px"` is a React-ism; it isn’t something provided by the standard [setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty). But sure, I can clarify that in the docs.

**Comment by mbostock** [comment]
Also, it looks like Safari and Chrome _do_ support unitless numeric values e.g. `style: {padding: 20}`, but Firefox does not. So support is browser-dependent.
