### ISSUE TITLE
Easier sorting of bins by weight?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#769]
In a case like this ([data](https://observablehq.com/@af96e6f2b5626d88/us_energy_production)), where I want the first categorical color to be assigned to the most prominent category, and so on by descending prominence, it’d be nice to have an easier shorthand for referencing the height (y2 - y1) of the rects:

<img width="1166" alt="Screen Shot 2022-02-19 at 12 55 38 PM" src="https://user-images.githubusercontent.com/230541/154818758-fde6d483-5075-464e-904e-d2d4e667668d.png">

```js
Plot.plot({
  width,
  x: { tickFormat: "" },
  color: { legend: true },
  marks: [
    Plot.rectY(overview, {
      x: "Year",
      y: "Value",
      fill: "Type",
      interval: 1,
      sort: {
        color: "data",
        reduce: (D) => -d3.mean(D, (d) => d.Value)
      }
    }),
    Plot.ruleY([0])
  ]
})
```

The challenge is that I can’t say `sort: {color: "y"}` because in this context _y_ refers to the midpoint of _y1_ and _y2_. And we don’t support expressions such as `sort: {color: "y2 - y1"}`. Perhaps we could support some magic shorthand for “dy” and “dx” though?

**Comment by Fil** [comment]
You can use the strokeOpacity channel, which has no effect since there is no stroke:

```
      strokeOpacity: (d) => -d["Value"],
      sort: { color: "strokeOpacity" }
```

this maybe indicates a need to allow the user to add custom channels

**Comment by mbostock** [comment]
I’m not sure that creating a custom channel is helpful here, since I can effectively do that already by using a reducer on the data. My point here is that the height or width of a rect (or bar etc.) is visually salient and so it would be nice to have some easy access to it for sorting (such as by having implicit “dx” and “dy” channels).

**Comment by mbostock** [comment]
Actually I think I’m getting confused between scales and channels. When I say `sort: {color: "y"}` is that referencing the channel “y” or the scale “y”? I think it’s maybe referencing the scale but we need to reference a channel here.

(And it’s extra confusing here because I’ve declared a “y” channel, but it’s being remapped to a “y2” channel internally. )

**Comment by Fil** [comment]
As soon as we'd have _x1_ and _x2_ we would derive _x_ and _width_? Currently this happens in the stackX transform (https://github.com/observablehq/plot/blob/main/src/transforms/stack.js#L10), but it would be nice to generalize.

**Comment by mbostock** [comment]
Okay, this is the thing I forgot about:

https://github.com/observablehq/plot/blob/9d7d9c2bf8bb0aa0da2084078d85a10e6dd9350e/src/transforms/stack.js#L62-L70
