### ISSUE TITLE
Write a roadmap for Plot.carto

### ISSUE THREAD

**Issue by espinielli** [observablehq/plot#796]
**Is your feature request related to a problem? Please describe.**
Geographical maps are a powerful tool for data exploration, visualisation and information delivery.
The `Plot` library is lowering more and more the technical barrier to non (super) experts in D3 & Javascript arcana.
I am an early (and happy [thanks @Fil]) user of [`Plot.carto`](https://observablehq.com/@fil/plot-carto-0-5) which brings *some* facilities to geographical map production but is still not an official *production-like* feature of the `Plot` family.
 

**Describe the solution you'd like**
I am pretty sure at Observable the `Plot.carto` line of development is pretty close to the list of features to deliver, but I would like to understand whether you have a roadmap, a timeline, a community involvement plan,...

Among the missing features (well, just things _I_ would love to be able to do in Observable) of what is today available via `Plot.carto` I see:
* support for insets (geo mini maps or logos or tables/legends...)
  - [Legend example](https://observablehq.com/@jake-low/how-well-does-population-density-predict-u-s-voting-outcome?collection=@observablehq/maps#population_map)
  - [Legend and metadata example](https://observablehq.com/@joewdavies/mapping-with-pie-charts-most-common-causes-of-death-in-europ?collection=@observablehq/maps#map)
  - [insets example](https://observablehq.com/@joewdavies/eurostat-map-js#cell-9)
  - [minimap inset example](https://github.com/Robinlovelace/geocompr/issues/532#issuecomment-621471116)
* Support/Example for arrows in maps just for visual indication of direction (think of invasion flows in the [sad] war to Ukraine)
  - like [arrow example](https://observablehq.com/@neocartocnrs/arrows) but for maps (maybe on a great circle arc, or possibly intermediate geo points to smoothly pass thru?)
  - [geographical flows example](https://observablehq.com/@bayre/spatially-situated-sankey) (apart from the sankey case, just the flows from P1 to P2)
* pattern matching filling, like in the NO FIR zone in [this notebook](https://observablehq.com/@xoolive/flight-information-regions#header) which @Fil helped with (still it looks really black magic)
* scale bar like in [here](https://observablehq.com/@harrystevens/introducing-d3-geo-scale-bar) (I used it with Plot.carto in [this notebook of mine](https://observablehq.com/@espinielli/base-map-eurocontrol#MAP) but it took a lot of time to understand and get it done)

**Describe alternatives you've considered**
I have tried to have [my own composite projection](https://observablehq.com/@espinielli/base-map-eurocontrol) (but stuck in trying to understand the magic to move the insets somewhere else...) or simply given up due to the steep learning curve and lack of time.

**Additional context**
This is of course no criticism of what is available, on the contrary it is a recognition of the greatness of Observable notebooks/Plot library which can build on top of the excellent d3-geo facilities to make the geographical mapping more accessible.
Also maybe some of the above is possible today...it is then a matter of documentation/examples/...
(Personally i have searched far and large but got limited success)

**Comment by espinielli** [comment]
> These are great ideas, than you Enrico for the suggestions and support!
> 
> I'd be happy to have a workshop in which we could discuss what features Plot.carto should cover. The general goal is certainly not to support each and every type of map, but we want to support the most common primitives.
> 
> Here's an example of a map with an inset: https://observablehq.com/@fil/inset-map ; it would certainly be nice to simplify this a bit, but it's already possible :)

Eh, eh, I knew it was possible!
Now I have to _study_ and *understand* what is going on 😃 !

I also subscribe to the desire to support a reasonable set of map types/features and a core set of primitives: it is the usual sane tradeoff aiming at reducing complexity/maintainability and feature explosion.
I am pretty fine with common things to be _easy_ and less common ones to be possible in maybe a non straightforward way (with examples I can learn from and brutally copy & paste ;-)

That is the reason I listed some of my desiderata; maybe they will make it in the core if there is enough interest, but I would also be happy to have example I can learn from (and this "example was" is the thing I always loved from D3/bl.ocks.org/Observable).

Again, a great appreciation for the technical and community-oriented environment you are working on!

**Comment by mbostock** [comment]
We do not plan on sharing a public roadmap for Plot development, but I welcome discussion on what features would be more useful/desirable.
