### ISSUE TITLE
funciri do not work in the swatches color legend

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#805]
see https://observablehq.com/@observablehq/cheysson-plot

**Comment by mbostock** [comment]
To add more detail: color swatches are rendered as HTML, with the color applied as a CSS background. It’ll need to be rendered as SVG instead if we want to support patterns.

https://github.com/observablehq/plot/blob/66142e2c096439cffea0ed390de13c6cf1545388/src/legends/swatches.js#L147-L152
