### ISSUE TITLE
symbol reducer and scale hint

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#806]
on the [mbostock/reinitialize](https://github.com/observablehq/plot/tree/mbostock/reinitialize) branch, the symbol reducer crashes at inferSymbolHint (ordinal.js:121:32) with `Cannot read properties of undefined (reading 'fill')`

~~~js
import * as Plot from "@observablehq/plot";
import * as d3 from "d3";

export default async function() {
  const penguins = await d3.csv("data/penguins.csv", d3.autoType);
  return Plot.plot({
    grid: true,
    marks: [
      Plot.dot(penguins, Plot.hexbin({r: "count", symbol: "mode"}, {
        radius: 20, 
        symbol: "sex",
        x: "culmen_depth_mm",
        y: "culmen_length_mm"
      }))
    ],
    symbol: {legend: true}
  });
}
~~~

I've tried to fix this here https://github.com/observablehq/plot/pull/804#pullrequestreview-907457109

**Comment by mbostock** [comment]
Thanks for finding this bug and sharing a reproduction!
