### ISSUE TITLE
Polar coordinates for Observable's Plot ?

### ISSUE THREAD

**Issue by pachevalier** [observablehq/plot#820]
Observable's plot is very similar in the spirit to GGplot and it's great. There is a nice feature in ggplot which is not available in Plot. You can add `coord` parameter to the plot. For instance, you can use [coord_polar](https://ggplot2.tidyverse.org/reference/coord_polar.html) to use polar coordinates instead of cartesian coordinates. Are you planning to add this feature to Observable's plot ?

**Comment by Fil** [comment]
We are definitely planning to make radial marks (see the issue https://github.com/observablehq/plot/issues/133 and an early prototype https://observablehq.com/@observablehq/arc-mark-pie-transform-80 (#80, #85)).

However, we're not sure yet how this would work. Changing the coordinates system or using more generic "geographic" projections is a possibility. 

I'm closing this as a duplicate, but we welcome your comments on the linked issues!

**Comment by pachevalier** [comment]
Thanks for the feedback and sorry for the duplicate.
