### ISSUE TITLE
Font size style example in cheatsheet uses quirky lengths and doesn’t work in Firefox

### ISSUE THREAD

**Issue by jtrimm007** [observablehq/plot#839]
I am currently using the D3 Plot library for a capstone project and ran across this issue. If you can point me to the file where the style/fontSize is defined, I will try to fix it. Or if there is already a fix, it would be nice to know. 

Thanks for the help. 

Page Example: 
https://observablehq.com/@observablehq/plot-cheatsheets-layouts 

**Not working**
![image](https://user-images.githubusercontent.com/16611773/161779575-cec72201-5f6f-44b6-8cd3-c1aadce13740.png)

**Comment by Fil** [comment]
Interestingly Firefox seems to support quirky lengths for the svg font-size _attribute_ (not style).

This is what we use in several test plots:
* test/plots/letter-frequency-cloud.js:      Plot.text(alphabet, {x: random, y: random, text: "letter", fontSize: d => 10 + 200 * (d.frequency / max)})
* test/plots/moby-dick.js:      Plot.text([mobydick], {fontSize: 14, lineWidth: 40, lineHeight: 1.2, frameAnchor: "top-left"})
* test/plots/word-cloud.js:        fontSize: d => 4 * Math.sqrt(d.length)
* test/plots/letter-frequency-wheel.js:        fontSize: 8,

And they are mapped to the attribute font-style="8" etc.

Do we have to anticipate that this will break too at some point? I couldn't find a reference. 🤔

**Comment by jtrimm007** [comment]
Awesome! Thanks @mkfreeman and @mbostock, that was super fast!

**Comment by mbostock** [comment]
> Do we have to anticipate that this will break too at some point?

No, unitless numbers are fine for the SVG attributes. It’s just for styles where you should always specify units.
