### ISSUE TITLE
Vue example

### ISSUE THREAD

**Issue by jparish3** [observablehq/plot#846]
I added  @observablehq/plot to  vue.config.js & the example :Plot.rectY(athletes, Plot.binX({y: "count"}, {x: "weight", fill: "sex"})).plot() appears to read the data, but cannot figure out how to render following this following this [codebox](https://codesandbox.io/s/nlhuc?file=/src/components/HelloWorld.vue:1177-1186) example. It would be helpful to have a Vue example like React one. Thanks

**Comment by Fil** [comment]
Yes. I also have an example integration with [astro](https://github.com/withastro/astro): https://github.com/withastro/astro/issues/2451

**Comment by joakimnl** [comment]
+1 for Astro example

**Comment by tophtucker** [comment]
There's now a Vue example in the main "Getting started" docs: https://observablehq.com/plot/getting-started#plot-in-vue
