### ISSUE TITLE
Shorthand version of Plot.areaY is no longer working since 0.4.3

### ISSUE THREAD

**Issue by stas-sl** [observablehq/plot#850]
Hello, thanks for the awesome library. I was reading your tutorial (https://observablehq.com/@observablehq/plot-shorthand) and noticed that `Plot.areaY` is broken:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/4602302/163899582-e9ebe04c-065e-4bbf-9c61-c3f37ed529c9.png">

**Comment by mbostock** [comment]
Oops! I’ll fix shortly. Thanks for the report.
