### ISSUE TITLE
Time scale labels don't adjust to font size.

### ISSUE THREAD

**Issue by reubano** [observablehq/plot#859]
As seen below, increasing the font size makes the time scale labels overlap.

```js
style: {
    fontFamily: "system-ui",
    fontSize: "16px",
    overflow: "visible"
},
```

<img width="324" alt="Screen Shot 2022-04-30 at 19 45 59" src="https://user-images.githubusercontent.com/157864/166127439-4ffe35c1-396f-4198-ab59-a9f96cd1ce25.png">

```js
style: {
    fontFamily: "system-ui",
    fontSize: "24px",
    overflow: "visible"
},
```

<img width="315" alt="Screen Shot 2022-04-30 at 19 46 14" src="https://user-images.githubusercontent.com/157864/166127444-e0399f50-1024-4e1c-b605-985d1c4e29d0.png">

**Comment by mbostock** [comment]
Yes, that’s how it works. Plot does not consider text metrics when laying out axes.

**Comment by reubano** [comment]
So what's the work-a-round for this?

**Comment by mbostock** [comment]
You can specify a different number of ticks using the scale.ticks option (e.g., `x: {ticks: 4}`) or you can rotate the ticks using scale.tickRotate option (e.g., `x: {tickRotate: 90}`) and then increasing marginBottom.

**Comment by reubano** [comment]
```js
var graph = Plot.plot({
    x: {
        ticks: 4,
        tickRotate: -45,
    },
    width: 640,
    height: 400,
    marginLeft: 100,
    marginTop: 105,
    marginBottom: 100,
});
```
