### ISSUE TITLE
performance nit: unnecessary copy in coerceArray?

### ISSUE THREAD

**Issue by skybrian** [observablehq/plot#862]
I'm animating a graph using Plot. This isn't what it's intended for, but I'm still getting 60 frames per second, so not bad.

It uses more CPU than I'd like. I did JavaScript profile in Chrome looking for performance issues and noticed that 230 milliseconds or 8.5% of the time is in [coerceArray](https://github.com/observablehq/plot/blob/81f17eac8013e9269ae962ea726e5ea8d1eeba1f/src/scales.js#L360).

It's being called [from Scale](https://github.com/observablehq/plot/blob/81f17eac8013e9269ae962ea726e5ea8d1eeba1f/src/scales.js#L174) to convert to a Float64Array, and this case it already is one, because that's what I passed in. Maybe an unnecessary copy could be avoided?

**Comment by mbostock** [comment]
Also mentioned here, along with a potential optimization of the `range` helper: https://github.com/observablehq/plot/pull/801#issuecomment-1119103573

Short-circuiting coercion to Float64Array when the input is already a typed array definitely sounds like an easy win. Let’s do it.
