### ISSUE TITLE
Interpret stroke parameter in more ways for a categorical color domain

### ISSUE THREAD

**Issue by skybrian** [observablehq/plot#864]
I'm trying to render different colored lines, along with a legend saying what each color means. This works if I specify each color using a number, but then the labels in the color legend are numbers. If I change the domain to get the labels right, the lines disappear.

```
Plot.plot({
  color: {
    type: "categorical",
    legend: true,
    // domain: ["first", "second"], // changes labels but lines disappear

  },
  marks: [
    Plot.lineY(firstColumn, {stroke: 0}),
    Plot.lineY(secondColumn, {stroke: 1})
  ]
})
```

See:  https://observablehq.com/d/82a706f5e7521d3b

Changing the stroke argument to a string doesn't help, because it has other meanings. Plot interprets a string as column name or CSS color, not as an entry into the color domain. Since the columns don't exist and they're not colors, the lines are still gone.

## Possible improvements:

Maybe add more interpretations of the stroke argument?

* If the stroke argument is a non-negative integer and it's not an entry in the color domain, maybe treat it as an *index* into the color domain instead?

* If the stroke argument is a string, isn't a column, and isn't a CSS color, maybe look in the color domain to see if there's a match?

Or maybe there could be a way to override the names used in the color legend without changing the domain? This would be convenient if you wanted to put longer descriptions there.

## Workarounds: 

You can get past the default interpretation of strings by passing in a function that returns a constant:

```
Plot.plot({
  color: {
    type: "categorical",
    legend: true,
    domain: ["first", "second"],
  },
  marks: [
    Plot.lineY(firstColumn, {stroke: (_) => "first"}),
    Plot.lineY(secondColumn, {stroke: (_) => "second"})
  ]
})
```

Alternately, render the legend separately.

**Comment by Fil** [comment]
You could create a helper such as `constant = d => () => d;` then write 
```
    Plot.lineY(firstColumn, {stroke: constant("first")}),
    Plot.lineY(secondColumn, {stroke: constant("second")})
```

You could also want to use tickFormat to make the legend match the numbers:
```
Plot.plot({
  color: {
    type: "categorical",
    legend: true,
    tickFormat: i => ["first", "second"][i],
  },
  marks: [
    Plot.lineY(firstColumn, {stroke: 0}),
    Plot.lineY(secondColumn, {stroke: 1})
  ]
})
```

The first suggestion is interesting but seems quite specific, I don't see us doing that.

Re: the second suggestion, Plot has no specific notion of what is a column—we only transform (non-color-like) strings into property accessors (`"foo"` becomes `d => d["foo"]`), but have no way of knowing if it is expected or not that some, or all, or none of the returned values are something other than `undefined`.

**Comment by skybrian** [comment]
*tickFormat* seems like an unfortunate name for this functionality. (What are "ticks" for a categorical color legend?)

I see it there now, but when reading the documentation I skipped past it as irrelevant.
