### ISSUE TITLE
Idea: expose API to get swatch colors, for creating your own legend

### ISSUE THREAD

**Issue by skybrian** [observablehq/plot#865]
I'm implementing a UI with a plot that has colored lines, along with a button group to turn the lines on and off, one button for each line.

These buttons will take place of the legend, so I'd like to draw a color swatch on each button. The question is, how to calculate the color?

Given a scheme (such as the "turbo" scheme) and the number of lines there will be on the graph, I'd like to be able to get the swatch color for each button. I could probably reimplement it from d3.interpolateTurbo, but this duplicates code and also hard-codes the color scheme.

That's an okay workaround in my case, but perhaps Plot could expose an API to get the swatch colors that it will use?

**Comment by mbostock** [comment]
You can call plot.scale(“color”) to get the color scale for a given plot and then use the apply function to get the color for a given data value. See the README for details.

**Comment by skybrian** [comment]
Okay, thanks!

For the record, here is a way to get a color range out of Plot:

```
const colorDomain = new Array(10).fill(0).map((_, i) => i);

const colorScale = Plot.scale({color: {
  type: "categorical",
  scheme: "tableau10",
  domain: colorDomain
}});

const colorRange = colorDomain.map((d) => colorScale.apply(d));
```

(Although in retrospect, I could have saved some time by hard-coding a constant array of colors and setting colors directly, as the stroke for each mark.)

**Comment by mbostock** [comment]
If you call Plot.scale (with a capital P) rather than _plot_.scale (where _plot_ is a plot previously generated by calling Plot.plot), then you are creating a standalone scale. I recommend using _plot_.scale instead so that you can ensure that the returned scale object is consistent with what the plot actually uses. Also, that means you can then refer to _scale_.domain and _scale_.range to get the domain and range respectively.

Demo: https://observablehq.com/d/52d5a2856654afef

**Comment by skybrian** [comment]
Yep, good point! But I need a bit more color manipulation, so I'm going with a different approach: [code generation](https://observablehq.com/@skybrian/serialviz-colors).

It seems like a promising way to use d3 for manipulating colors without ending up with a separate runtime dependency on d3 (besides the one already in Plot).
