### ISSUE TITLE
avoid showing a count in group labels when the count is 1?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#876]
ref. https://talk.observablehq.com/t/unspecified-number-appearing-at-the-end-of-plot-tooltips/6511/2

**Comment by mbostock** [comment]
I think the question here is how “global” the count = 1 check would be. Would you want a tooltip like this?

```
Apple (3)
Banana (2)
Orange
```

Or would you want one mark to have a tooltip like this?

```
Apple (3)
```

And another to have this?

```
Orange
```
