### ISSUE TITLE
Default Plot.windowY?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#877]
Just an idea: since “window is something you want to do…almost always”, Plot.lineY could call this transform by default, with _k_ set to 0. Adding _k: 14_ would smooth the line.

Note: my own personal preference is array-blur, which doesn't introduce NaN at the extremes—OTOH it only allows a “mean” reducer.

**Comment by mbostock** [comment]
> window is something you want to do… almost always

I don’t follow this; can you clarify why you almost always want a window transform? It feels pretty rare to me.

**Comment by Fil** [comment]
It came up in a conversation with @eagereyes ; going to close for now.
