### ISSUE TITLE
Plot.rectY rendering gliches with non-integer x and interval

### ISSUE THREAD

**Issue by skybrian** [observablehq/plot#887]
Demo is [here](https://observablehq.com/@skybrian/plot-recty-with-varying-numbers-of-bins).

If you move the slider to increase the bin count, the rendering glitch happens at: 7, 13, 14, 25, 26, 27, 28, 31, 35, 37 [...].

I don't see an obvious pattern, other than it's not divisible by 360, so x and the interval aren't integers. At every "nice" bin count I pick it looks fine.

A workaround is to set x1 and x2 instead of x and interval.

**Comment by mbostock** [comment]
Yes, I don’t recommend using non-integer intervals generally speaking. You can see what the interval transform does here:

https://github.com/observablehq/plot/blob/8757c028e12ba434ff2f199f8789e338140170fd/src/transforms/interval.js#L14

**Comment by skybrian** [comment]
Okay, to expand on that explanation for anyone who reads this:

A number is turned into a set of intervals by starting at zero and counting off equal-length intervals of the size given. (I had a different mental model of what it does, because I was going by other people's examples.)

The glitch is due to floating point imprecision. The value of "theta" in the input is at the beginning of the interval, but calculated slightly differently, so sometimes the number is slightly outside the desired interval as calculated by Plot. So another way to fix the glitch is to add a small amount to theta:  `x: d => d.theta + 0.01`.
