### ISSUE TITLE
Filtering could be smarter?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#919]
as reported by @yurivish:
> filter happens after computing channel values, ie. you can't filter out guys that you know will produce an error with filter.
<img width="697" alt="image (2)" src="https://user-images.githubusercontent.com/7001/172473913-25cc3200-e7e7-4468-9a24-78dc1afe4e92.png">

it makes me think that if it is possible to do it in the reverse order, we could have huge performance gains when a filtering operation such as Plot.selectFirst is called. However I doubt that this would work, since we have to make Plot.selectMaxX work too—it's not going to be as simple as that.

**Comment by mbostock** [comment]
I don’t think this will work (based on the design of filtering as being purely on operation on the index and not on channels). Better to call data.filter(…) outside of Plot than to use the filter transform in this case.

If it helps, you can use optional chaining: `(d) => d?.a`.

**Comment by mbostock** [comment]
Closing as “I don’t think this will work” but we can re-open or continue to discuss.
