### ISSUE TITLE
a href issues

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#935]
- [ ] a link added to a Plot, without a target=_blank, will crash the observable iframe in Chrome (it works in Safari and Firefox)
- [ ] the constant fill color of a text link anchor is overridden by the default link:visited color.

reported by @yurivish @ https://observablehq.com/d/02cab844233728fb

**Comment by mbostock** [comment]
For the second issue, we probably need a rule like `svg.plot a { fill: inherit; }`? 😬
