### ISSUE TITLE
[a11y] Accessibility issue with plot rect

### ISSUE THREAD

**Issue by dennismphil** [observablehq/plot#944]
By including Plot, looks like our accessibility score dropped with a reason \``[aria-*]` attributes do not match their roles\`

![](https://user-images.githubusercontent.com/4141366/174142704-28467184-6ec6-44df-9461-b22123f948ae.png)

**Comment by mbostock** [comment]
Is this a bug in the validator? [SVG elements have the implicit role=graphics-documents](https://www.w3.org/TR/html-aria/#el-svg) for which global aria-* attributes are valid, including aria-label. And according to [SVG AAM](https://www.w3.org/TR/svg-aam-1.0/#include_elements), SVG G elements are eligible for inclusion in the accessibility tree if “it has a non-empty (after trimming whitespace) ‘[aria-label](https://w3c.github.io/aria/#aria-label)’ attribute or ‘[aria-roledescription](https://w3c.github.io/aria/#aria-roledescription)’ attribute.”

I’m happy to make changes here, but it looks like the validator you are using doesn’t match what I’m reading in the SVG Accessibility API Mappings specification, so I’m not sure how to appease it. If you can be more specific about how to solve this problem I would be happy to investigate further.

**Comment by dennismphil** [comment]
The validator I am using is Chrome browser's lighthouse report, in case that helps.

**Comment by mbostock** [comment]
Lighthouse doesn’t seem to recognize the `aria-description` attribute, so, I’m not sure how much I trust its validation of SVG. It looks like adding `role="graphics-object"` to the various places we use `aria-label` would silence the other error, but I don’t actually know whether that is desirable from an accessibility perspective.

**Comment by dennismphil** [comment]
Adding a role I believe makes lighthouse and axe devTools remove the error. Can we move forward in that path?
